export const MANAGEMENT_COPY = {
  'zh-CN': {
    title: '菜单管理',
    subtitle: '统一管理菜单分类和菜单项。分类支持编辑、删除和重排，默认对象菜单会保持锁定。',
    actions: {
      save: '保存',
      reload: '重新加载',
      addCategory: '新增分类',
      manageTranslations: '更多语言',
      moveUp: '上移',
      moveDown: '下移',
      delete: '删除',
    },
    sections: {
      categories: '菜单分类',
      categoriesHint: '左侧分类支持分页和拖拽排序。默认分类可调整名称、图标、显示状态和顺序。',
      entries: '菜单项',
      entriesHint: '右侧菜单项支持分页和拖拽排序。对象菜单默认锁定，普通菜单项可以重新分组和排序。',
    },
    fields: {
      categoryCode: '分类编码',
      categoryName: '分类名称',
      categoryNameZh: '中文名称',
      categoryNameEn: 'English Name',
      icon: '图标',
      order: '排序',
      visible: '显示',
    },
    columns: {
      group: '所属分类',
      order: '排序',
      visible: '显示',
    },
    tags: {
      default: '默认',
      custom: '自定义',
      locked: '硬锁',
      static: '系统页',
      object: '对象',
    },
    labels: {
      entries: '条目',
      dragHandle: '拖拽排序',
    },
    placeholders: {
      categoryName: '请输入分类名称',
      categoryNameZh: '请输入中文分类名称',
      categoryNameEn: 'Enter English category name',
      icon: '选择图标',
      search: '按名称、编码或路由搜索',
    },
    messages: {
      loadFailed: '加载菜单管理数据失败',
      saveSuccess: '菜单配置已保存',
      saveFailed: '菜单配置保存失败',
      duplicateCategory: '分类编码不能重复',
      invalidCategoryName: '请同时填写分类中文名称和 English Name',
      invalidCategory: '分类编码不能为空，且只能包含字母、数字、下划线和中划线',
      categoryInUse: '该分类下仍有菜单项，不能删除',
      saveBeforeTranslations: '请先保存分类，再到翻译模块补充更多语言。',
      confirmDeleteTitle: '删除分类',
      confirmDeleteMessage: '确认删除分类“{name}”吗？删除后不会自动迁移其下菜单项。',
      translationHint: '其他语言默认回退到英文，可在翻译模块继续补充。',
    },
    detail: { kicker: '项详情', entryCode: '菜单编码' },
    focusMode: { current: '当前分类', all: '查看全部' },
    visibility: { visible: '显示', hidden: '隐藏' },
    emptyGroup: {
      title: '暂无菜单项',
      hint: '可直接拖入到该分类，或通过分类选择器切换归属。',
    },
    toggles: { expand: '展开', collapse: '收起' },
  },
  'en-US': {
    title: 'Menu Management',
    subtitle: 'Manage categories and entries together. Categories can be edited, reordered, and cleaned up while default object entries stay locked.',
    actions: {
      save: 'Save',
      reload: 'Reload',
      addCategory: 'Add Category',
      manageTranslations: 'More Languages',
      moveUp: 'Up',
      moveDown: 'Down',
      delete: 'Delete',
    },
    sections: {
      categories: 'Categories',
      categoriesHint: 'The category list supports pagination and drag sorting. Default categories can still update labels, icons, visibility, and order.',
      entries: 'Entries',
      entriesHint: 'The entry board supports pagination and drag sorting. Default object entries remain locked while regular entries can be regrouped.',
    },
    fields: {
      categoryCode: 'Category Code',
      categoryName: 'Category Name',
      categoryNameZh: 'Chinese Name',
      categoryNameEn: 'English Name',
      icon: 'Icon',
      order: 'Order',
      visible: 'Visible',
    },
    columns: {
      group: 'Category',
      order: 'Order',
      visible: 'Visible',
    },
    tags: {
      default: 'Default',
      custom: 'Custom',
      locked: 'Locked',
      static: 'Static',
      object: 'Object',
    },
    labels: {
      entries: 'Entries',
      dragHandle: 'Drag to reorder',
    },
    placeholders: {
      categoryName: 'Enter category name',
      categoryNameZh: 'Enter Chinese category name',
      categoryNameEn: 'Enter English category name',
      icon: 'Choose an icon',
      search: 'Search by name, code, or route',
    },
    messages: {
      loadFailed: 'Failed to load menu management data',
      saveSuccess: 'Menu configuration saved',
      saveFailed: 'Failed to save menu configuration',
      duplicateCategory: 'Category code must be unique',
      invalidCategoryName: 'Please fill in both the Chinese and English category names',
      invalidCategory: 'Category code is required and may only contain letters, numbers, underscores, and hyphens',
      categoryInUse: 'This category still has menu entries and cannot be deleted',
      saveBeforeTranslations: 'Save the category first, then add more languages in the Translation module.',
      confirmDeleteTitle: 'Delete Category',
      confirmDeleteMessage: 'Delete category "{name}"? Entries will not be migrated automatically.',
      translationHint: 'Other languages fall back to English by default. Add extra translations in the Translation module.',
    },
    detail: { kicker: 'Entry Detail', entryCode: 'Entry Code' },
    focusMode: { current: 'Current Category', all: 'View All' },
    visibility: { visible: 'Visible', hidden: 'Hidden' },
    emptyGroup: {
      title: 'No entries yet',
      hint: 'Drop menu items here, or move them with the category selector.',
    },
    toggles: { expand: 'Expand', collapse: 'Collapse' },
  },
} as const
