# Generated by Django 5.0.1 on 2026-01-18 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('code', models.CharField(db_index=True, help_text="Unique category code (e.g., '2001' for computer equipment)", max_length=50)),
                ('name', models.CharField(help_text='Category display name', max_length=200)),
                ('full_name', models.CharField(editable=False, help_text="Full path name (e.g., 'Computer Equipment > Desktop')", max_length=500)),
                ('level', models.IntegerField(default=0, editable=False, help_text='Tree level (0=root, 1=first child, ...)')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order within same level')),
                ('is_custom', models.BooleanField(default=False, help_text='True=user-created, False=system predefined')),
                ('is_active', models.BooleanField(default=True, help_text='Category status (can be deactivated without deletion)')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line Method'), ('double_declining', 'Double Declining Balance'), ('sum_of_years', 'Sum of Years Digits'), ('no_depreciation', 'No Depreciation')], default='straight_line', max_length=50)),
                ('default_useful_life', models.IntegerField(default=60, help_text='Default useful life in months')),
                ('residual_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Default residual value rate (%)', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for tree structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_category',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['organization', 'code'], name='asset_categ_organiz_45ecbe_idx'), models.Index(fields=['organization', 'parent'], name='asset_categ_organiz_2c2116_idx'), models.Index(fields=['organization', 'is_deleted', 'is_active'], name='asset_categ_organiz_860dbd_idx')],
            },
        ),
    ]
