# Generated by Django 5.0.1 on 2026-01-18 06:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
        ("organizations", "0002_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique asset code (auto-generated: ZCYYYYMMNNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(help_text="Asset name", max_length=200),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True, help_text="Specification/model", max_length=200
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, help_text="Brand", max_length=100),
                ),
                (
                    "model",
                    models.CharField(blank=True, help_text="Model", max_length=100),
                ),
                (
                    "unit",
                    models.CharField(
                        default="台", help_text="Unit of measurement", max_length=20
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, help_text="Serial number", max_length=100
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original purchase price",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current net value",
                        max_digits=14,
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Accumulated depreciation",
                        max_digits=14,
                    ),
                ),
                ("purchase_date", models.DateField(help_text="Purchase date")),
                (
                    "depreciation_start_date",
                    models.DateField(
                        blank=True, help_text="Depreciation start date", null=True
                    ),
                ),
                (
                    "useful_life",
                    models.IntegerField(default=60, help_text="Useful life in months"),
                ),
                (
                    "residual_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Residual value rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "supplier_order_no",
                    models.CharField(
                        blank=True, help_text="Supplier order number", max_length=100
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True, help_text="Invoice number", max_length=100
                    ),
                ),
                (
                    "asset_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Entry"),
                            ("in_use", "In Use"),
                            ("idle", "Idle"),
                            ("maintenance", "Under Maintenance"),
                            ("lost", "Lost"),
                            ("scrapped", "Scrapped"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Asset status",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="QR code (auto-generated UUID)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "rfid_code",
                    models.CharField(
                        blank=True,
                        help_text="RFID code",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="Asset images"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True, default=list, help_text="Attachment list"
                    ),
                ),
                ("remarks", models.TextField(blank=True, help_text="Remarks")),
                (
                    "asset_category",
                    models.ForeignKey(
                        help_text="Asset category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        help_text="Custodian",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custodian_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Using department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="organizations.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Actual user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="using_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "loan_no",
                    models.CharField(
                        db_index=True,
                        help_text="Loan order number (auto-generated: LN+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("borrow_date", models.DateField(help_text="Borrow date")),
                (
                    "expected_return_date",
                    models.DateField(help_text="Expected return date"),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True, help_text="Actual return date", null=True
                    ),
                ),
                (
                    "loan_reason",
                    models.TextField(blank=True, help_text="Reason for loan"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("borrowed", "Borrowed"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Loan order status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Approval timestamp", null=True
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, help_text="Approval comment"),
                ),
                (
                    "lent_at",
                    models.DateTimeField(
                        blank=True, help_text="Lend confirmation timestamp", null=True
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, help_text="Return confirmation timestamp", null=True
                    ),
                ),
                (
                    "asset_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("minor_damage", "Minor Damage"),
                            ("major_damage", "Major Damage"),
                            ("lost", "Lost"),
                        ],
                        help_text="Asset condition upon return",
                        max_length=20,
                    ),
                ),
                (
                    "return_comment",
                    models.TextField(blank=True, help_text="Return comment"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        help_text="Borrower",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "lent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who confirmed lending",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lent_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "return_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who confirmed return",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_loan_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Loan Order",
                "verbose_name_plural": "Asset Loan Orders",
                "db_table": "asset_loans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetPickup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "pickup_no",
                    models.CharField(
                        db_index=True,
                        help_text="Pickup order number (auto-generated: LY+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("pickup_date", models.DateField(help_text="Pickup date")),
                (
                    "pickup_reason",
                    models.TextField(blank=True, help_text="Reason for pickup"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Pickup order status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Approval timestamp", null=True
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, help_text="Approval comment"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Completion timestamp", null=True
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Applicant who requests the pickup",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickup_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_pickups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Pickup department",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="department_pickups",
                        to="organizations.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Pickup Order",
                "verbose_name_plural": "Asset Pickup Orders",
                "db_table": "asset_pickups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetStatusLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(help_text="Previous status", max_length=20),
                ),
                ("new_status", models.CharField(help_text="New status", max_length=20)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for status change"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Related asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Status Log",
                "verbose_name_plural": "Asset Status Logs",
                "db_table": "asset_status_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "transfer_no",
                    models.CharField(
                        db_index=True,
                        help_text="Transfer order number (auto-generated: TF+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("transfer_date", models.DateField(help_text="Transfer date")),
                (
                    "transfer_reason",
                    models.TextField(blank=True, help_text="Reason for transfer"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("out_approved", "Out Department Approved"),
                            ("approved", "Both Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Transfer order status",
                        max_length=20,
                    ),
                ),
                (
                    "from_approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Source approval timestamp", null=True
                    ),
                ),
                (
                    "from_approve_comment",
                    models.TextField(blank=True, help_text="Source approval comment"),
                ),
                (
                    "to_approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Target approval timestamp", null=True
                    ),
                ),
                (
                    "to_approve_comment",
                    models.TextField(blank=True, help_text="Target approval comment"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Completion timestamp", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "from_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source department approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="out_approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        help_text="Source department",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="organizations.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "to_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target department approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="in_approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        help_text="Target department",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="organizations.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Transfer Order",
                "verbose_name_plural": "Asset Transfer Orders",
                "db_table": "asset_transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remark")),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being borrowed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_items",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="Parent loan order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assets.assetloan",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Item",
                "verbose_name_plural": "Loan Items",
                "db_table": "loan_items",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                ("name", models.CharField(help_text="Location name", max_length=200)),
                (
                    "path",
                    models.CharField(
                        help_text="Full path (e.g., Building A > Floor 1 > Room 101)",
                        max_length=500,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0, help_text="Tree level (0=root, 1=first child, ...)"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("floor", "Floor"),
                            ("room", "Room"),
                            ("area", "Area"),
                            ("warehouse", "Warehouse"),
                            ("other", "Other"),
                        ],
                        default="area",
                        help_text="Location type",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent location for tree structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="assets.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "locations",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="AssetReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "return_no",
                    models.CharField(
                        db_index=True,
                        help_text="Return order number (auto-generated: RT+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("return_date", models.DateField(help_text="Return date")),
                (
                    "return_reason",
                    models.TextField(blank=True, help_text="Reason for return"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("approved", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Return order status",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="Confirmation timestamp", null=True
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, help_text="Rejection reason"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Completion timestamp", null=True
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text=" confirmer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "returner",
                    models.ForeignKey(
                        help_text="User returning the asset",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_location",
                    models.ForeignKey(
                        help_text="Storage location for returned assets",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_returns",
                        to="assets.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Return Order",
                "verbose_name_plural": "Asset Return Orders",
                "db_table": "asset_returns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Storage location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assets.location",
            ),
        ),
        migrations.CreateModel(
            name="PickupItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="Quantity",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remark")),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset to pick up",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickup_items",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        help_text="Parent pickup order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assets.assetpickup",
                    ),
                ),
                (
                    "snapshot_original_custodian",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original custodian snapshot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot_original_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original location snapshot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assets.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pickup Item",
                "verbose_name_plural": "Pickup Items",
                "db_table": "pickup_items",
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "asset_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("maintenance", "Needs Maintenance"),
                            ("scrapped", "Needs Scrapping"),
                        ],
                        default="idle",
                        help_text="Asset status after return",
                        max_length=20,
                    ),
                ),
                (
                    "condition_description",
                    models.TextField(
                        blank=True, help_text="Asset condition description"
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remark")),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being returned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="assets.asset",
                    ),
                ),
                (
                    "asset_return",
                    models.ForeignKey(
                        help_text="Parent return order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assets.assetreturn",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Item",
                "verbose_name_plural": "Return Items",
                "db_table": "return_items",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique supplier code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Supplier name", max_length=200)),
                (
                    "contact",
                    models.CharField(
                        blank=True, help_text="Contact person", max_length=100
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Supplier address")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "suppliers",
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_assets",
                to="assets.supplier",
            ),
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remark")),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset to transfer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "from_custodian",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original custodian snapshot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original location snapshot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assets.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target location",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_in_locations",
                        to="assets.location",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        help_text="Parent transfer order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assets.assettransfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Item",
                "verbose_name_plural": "Transfer Items",
                "db_table": "transfer_items",
            },
        ),
        migrations.AddIndex(
            model_name="assetloan",
            index=models.Index(
                fields=["organization", "loan_no"],
                name="asset_loans_organiz_cf2b83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetloan",
            index=models.Index(
                fields=["organization", "borrower"],
                name="asset_loans_organiz_6becd9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetloan",
            index=models.Index(
                fields=["organization", "status"], name="asset_loans_organiz_dcef2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetpickup",
            index=models.Index(
                fields=["organization", "pickup_no"],
                name="asset_picku_organiz_e7f1c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetpickup",
            index=models.Index(
                fields=["organization", "applicant"],
                name="asset_picku_organiz_1a5a58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetpickup",
            index=models.Index(
                fields=["organization", "department"],
                name="asset_picku_organiz_89885f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetpickup",
            index=models.Index(
                fields=["organization", "status"], name="asset_picku_organiz_a8ef89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetstatuslog",
            index=models.Index(
                fields=["organization", "asset", "-created_at"],
                name="asset_statu_organiz_2f4fe7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransfer",
            index=models.Index(
                fields=["organization", "transfer_no"],
                name="asset_trans_organiz_aa8cb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransfer",
            index=models.Index(
                fields=["organization", "from_department"],
                name="asset_trans_organiz_abd3a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransfer",
            index=models.Index(
                fields=["organization", "to_department"],
                name="asset_trans_organiz_5253b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransfer",
            index=models.Index(
                fields=["organization", "status"], name="asset_trans_organiz_f1a3f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanitem",
            index=models.Index(
                fields=["loan", "asset"], name="loan_items_loan_id_8ba922_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["organization", "path"], name="locations_organiz_c7744c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetreturn",
            index=models.Index(
                fields=["organization", "return_no"],
                name="asset_retur_organiz_426e52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetreturn",
            index=models.Index(
                fields=["organization", "returner"],
                name="asset_retur_organiz_24aab4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetreturn",
            index=models.Index(
                fields=["organization", "status"], name="asset_retur_organiz_17e1c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickupitem",
            index=models.Index(
                fields=["pickup", "asset"], name="pickup_item_pickup__8d8939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnitem",
            index=models.Index(
                fields=["asset_return", "asset"], name="return_item_asset_r_e0bce3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["organization", "code"], name="suppliers_organiz_d606e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "asset_code"], name="assets_organiz_830b6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "asset_category"],
                name="assets_organiz_ccc8b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "custodian"], name="assets_organiz_44c39d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "qr_code"], name="assets_organiz_09e65e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "asset_status"],
                name="assets_organiz_3c6eba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["organization", "department"], name="assets_organiz_658385_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transferitem",
            index=models.Index(
                fields=["transfer", "asset"], name="transfer_it_transfe_d2a254_idx"
            ),
        ),
    ]
