# Generated by Django 5.2.10 on 2026-01-21 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_fix_department_foreign_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(db_index=True, default='pending', help_text='Asset status (references Dictionary: ASSET_STATUS)', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='unit',
            field=models.CharField(default='unit', help_text='Unit of measurement (references Dictionary: UNIT)', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetloan',
            name='borrower',
            field=models.ForeignKey(help_text='Borrower', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetloan',
            name='loan_no',
            field=models.CharField(db_index=True, help_text='Loan order number (auto-generated: JY+YYYYMM+NNNN)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assetloan',
            name='status',
            field=models.CharField(db_index=True, default='draft', help_text='Loan order status (references Dictionary: LOAN_STATUS)', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetpickup',
            name='status',
            field=models.CharField(db_index=True, default='draft', help_text='Pickup order status (references Dictionary: PICKUP_STATUS)', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='return_no',
            field=models.CharField(db_index=True, help_text='Return order number (auto-generated: GH+YYYYMM+NNNN)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='returner',
            field=models.ForeignKey(help_text='User who returns the assets', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='status',
            field=models.CharField(db_index=True, default='draft', help_text='Return order status (references Dictionary: RETURN_STATUS)', max_length=50),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='status',
            field=models.CharField(db_index=True, default='draft', help_text='Transfer order status (references Dictionary: TRANSFER_STATUS)', max_length=50),
        ),
    ]
