# Generated by Django 5.2.10 on 2026-01-21 02:54

from django.db import migrations


def migrate_units(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    
    mapping = {
        '台': 'unit',
        '个': 'piece',
        '套': 'set',
        '批': 'batch',
        '箱': 'box',
        '瓶': 'bottle',
        '包': 'pack',
        '米': 'meter',
        '千克': 'kg',
        'KG': 'kg',
        'kg': 'kg'
    }

    for text_val, code_val in mapping.items():
        Asset.objects.filter(unit=text_val).update(unit=code_val)

def reverse_migrate_units(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_asset_status_alter_asset_unit_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_units, reverse_migrate_units),
    ]
