# Generated by Django 5.0.1 on 2026-03-11 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0008_backfill_asset_systemfile_links"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loanitem",
            unique_together={("loan", "asset")},
        ),
        migrations.AlterUniqueTogether(
            name="pickupitem",
            unique_together={("pickup", "asset")},
        ),
        migrations.AlterUniqueTogether(
            name="returnitem",
            unique_together={("asset_return", "asset")},
        ),
        migrations.AlterUniqueTogether(
            name="transferitem",
            unique_together={("transfer", "asset")},
        ),
    ]
