# Generated by Django 5.0.1 on 2026-03-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0003_assetwarranty'),
        ('assets', '0009_alter_loanitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_purchase_request',
            field=models.ForeignKey(blank=True, help_text='Source purchase request', null=True, on_delete=models.deletion.SET_NULL, related_name='generated_assets', to='lifecycle.purchaserequest'),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_receipt',
            field=models.ForeignKey(blank=True, help_text='Source asset receipt', null=True, on_delete=models.deletion.SET_NULL, related_name='generated_assets', to='lifecycle.assetreceipt'),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_receipt_item',
            field=models.ForeignKey(blank=True, help_text='Source asset receipt item', null=True, on_delete=models.deletion.SET_NULL, related_name='generated_assets', to='lifecycle.assetreceiptitem'),
        ),
    ]
