# Generated by Django 5.0.1 on 2026-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0012_asset_tag_system"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assettag",
            new_name="asset_tags_organiz_3ee556_idx",
            old_name="asset_tag_org_code_idx",
        ),
        migrations.RenameIndex(
            model_name="assettag",
            new_name="asset_tags_organiz_b8efb7_idx",
            old_name="asset_tag_org_group_idx",
        ),
        migrations.RenameIndex(
            model_name="assettag",
            new_name="asset_tags_organiz_b1793e_idx",
            old_name="asset_tag_org_active_idx",
        ),
        migrations.RenameIndex(
            model_name="assettagrelation",
            new_name="asset_tag_r_organiz_263762_idx",
            old_name="asset_tag_rel_org_asset_idx",
        ),
        migrations.RenameIndex(
            model_name="assettagrelation",
            new_name="asset_tag_r_organiz_a75ece_idx",
            old_name="asset_tag_rel_org_tag_idx",
        ),
        migrations.RenameIndex(
            model_name="assettagrelation",
            new_name="asset_tag_r_organiz_5bd6a5_idx",
            old_name="asset_tag_rel_org_tagged_idx",
        ),
        migrations.RenameIndex(
            model_name="returnitem",
            new_name="return_item_organiz_9ca5fd_idx",
            old_name="return_item_organiz_ebd0f4_idx",
        ),
        migrations.RenameIndex(
            model_name="taggroup",
            new_name="asset_tag_g_organiz_2deb08_idx",
            old_name="asset_tag_group_org_code_idx",
        ),
        migrations.RenameIndex(
            model_name="taggroup",
            new_name="asset_tag_g_organiz_67cf76_idx",
            old_name="asset_tag_group_org_active_idx",
        ),
        migrations.RenameIndex(
            model_name="taggroup",
            new_name="asset_tag_g_organiz_3cf168_idx",
            old_name="asset_tag_group_org_sort_idx",
        ),
        migrations.AddField(
            model_name="assetpickup",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                help_text="Current workflow approval status of this document",
                max_length=20,
                verbose_name="Approval Status",
            ),
        ),
        migrations.AddField(
            model_name="assetpickup",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the document was submitted for approval",
                null=True,
                verbose_name="Submitted At",
            ),
        ),
        migrations.AddField(
            model_name="assetpickup",
            name="workflow_instance_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="ID of the linked WorkflowInstance",
                null=True,
                verbose_name="Workflow Instance ID",
            ),
        ),
        migrations.AlterField(
            model_name="assetpickup",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the document was approved",
                null=True,
                verbose_name="Approved At",
            ),
        ),
    ]
