# Generated by Django 5.0.1 on 2026-01-19 17:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0002_asset_assetloan_assetpickup_assetstatuslog_and_more"),
        ("organizations", "0004_delete_department_department_userdepartment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "task_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique task code (auto-generated: PD+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("task_name", models.CharField(help_text="Task name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Task description"),
                ),
                (
                    "inventory_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Inventory"),
                            ("partial", "Partial Inventory"),
                            ("department", "Department Inventory"),
                            ("category", "Category Inventory"),
                        ],
                        db_index=True,
                        default="full",
                        help_text="Inventory type",
                        max_length=20,
                    ),
                ),
                (
                    "sample_ratio",
                    models.IntegerField(
                        blank=True,
                        help_text="Sample ratio for partial inventory (1-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MinValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Task status",
                        max_length=20,
                    ),
                ),
                ("planned_date", models.DateField(help_text="Planned inventory date")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual start time", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Completion time", null=True
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(
                        default=0, help_text="Total assets to inventory"
                    ),
                ),
                (
                    "scanned_count",
                    models.IntegerField(default=0, help_text="Scanned assets count"),
                ),
                (
                    "normal_count",
                    models.IntegerField(default=0, help_text="Normal assets count"),
                ),
                (
                    "surplus_count",
                    models.IntegerField(default=0, help_text="Surplus assets count"),
                ),
                (
                    "missing_count",
                    models.IntegerField(default=0, help_text="Missing assets count"),
                ),
                (
                    "damaged_count",
                    models.IntegerField(default=0, help_text="Damaged assets count"),
                ),
                (
                    "location_changed_count",
                    models.IntegerField(
                        default=0, help_text="Location changed assets count"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Inventory notes")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for category inventory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_tasks",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department for department inventory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_tasks",
                        to="organizations.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Task",
                "verbose_name_plural": "Inventory Tasks",
                "db_table": "inventory_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(help_text="Asset code (snapshot)", max_length=50),
                ),
                (
                    "asset_name",
                    models.CharField(help_text="Asset name (snapshot)", max_length=200),
                ),
                (
                    "asset_category_id",
                    models.CharField(
                        help_text="Asset category ID (snapshot)", max_length=50
                    ),
                ),
                (
                    "asset_category_name",
                    models.CharField(
                        help_text="Asset category name (snapshot)", max_length=200
                    ),
                ),
                (
                    "location_id",
                    models.CharField(
                        blank=True,
                        help_text="Location ID (snapshot)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, help_text="Location name (snapshot)", max_length=200
                    ),
                ),
                (
                    "custodian_id",
                    models.CharField(
                        blank=True,
                        help_text="Custodian user ID (snapshot)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "custodian_name",
                    models.CharField(
                        blank=True,
                        help_text="Custodian name (snapshot)",
                        max_length=200,
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        blank=True,
                        help_text="Department ID (snapshot)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        blank=True,
                        help_text="Department name (snapshot)",
                        max_length=200,
                    ),
                ),
                (
                    "asset_status",
                    models.CharField(
                        help_text="Asset status (snapshot)", max_length=20
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete snapshot data (JSON)",
                    ),
                ),
                (
                    "scanned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether asset has been scanned",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True, help_text="First scan timestamp", null=True
                    ),
                ),
                (
                    "scan_count",
                    models.IntegerField(default=0, help_text="Number of times scanned"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Related asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_snapshots",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Related inventory task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="inventory.inventorytask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Snapshot",
                "verbose_name_plural": "Inventory Snapshots",
                "db_table": "inventory_snapshots",
                "ordering": ["task", "asset_code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        db_index=True, help_text="Scanned QR code", max_length=100
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(db_index=True, help_text="Scan timestamp"),
                ),
                (
                    "scan_method",
                    models.CharField(
                        choices=[
                            ("qr", "QR Code"),
                            ("rfid", "RFID"),
                            ("manual", "Manual"),
                        ],
                        default="qr",
                        help_text="Scan method",
                        max_length=20,
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("damaged", "Damaged"),
                            ("missing", "Missing"),
                            ("location_changed", "Location Changed"),
                            ("custodian_changed", "Custodian Changed"),
                            ("surplus", "Surplus"),
                        ],
                        db_index=True,
                        default="normal",
                        help_text="Scan result status",
                        max_length=20,
                    ),
                ),
                (
                    "original_location_id",
                    models.CharField(
                        blank=True,
                        help_text="Original location ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "original_location_name",
                    models.CharField(
                        blank=True, help_text="Original location name", max_length=200
                    ),
                ),
                (
                    "original_custodian_id",
                    models.CharField(
                        blank=True,
                        help_text="Original custodian ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "original_custodian_name",
                    models.CharField(
                        blank=True, help_text="Original custodian name", max_length=200
                    ),
                ),
                (
                    "actual_location_id",
                    models.CharField(
                        blank=True,
                        help_text="Actual location ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "actual_location_name",
                    models.CharField(
                        blank=True, help_text="Actual location name", max_length=200
                    ),
                ),
                (
                    "actual_custodian_id",
                    models.CharField(
                        blank=True,
                        help_text="Actual custodian ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "actual_custodian_name",
                    models.CharField(
                        blank=True, help_text="Actual custodian name", max_length=200
                    ),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, help_text="Photo URLs"),
                ),
                ("remark", models.TextField(blank=True, help_text="Scan remark")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scanned asset (null for surplus)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_scans",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        help_text="Scanner operator",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Related inventory task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="inventory.inventorytask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Scan",
                "verbose_name_plural": "Inventory Scans",
                "db_table": "inventory_scans",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryDifference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "difference_type",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("surplus", "Surplus"),
                            ("damaged", "Damaged"),
                            ("location_mismatch", "Location Mismatch"),
                            ("custodian_mismatch", "Custodian Mismatch"),
                        ],
                        db_index=True,
                        help_text="Type of difference",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Difference description")),
                (
                    "expected_quantity",
                    models.IntegerField(default=1, help_text="Expected quantity"),
                ),
                (
                    "actual_quantity",
                    models.IntegerField(default=0, help_text="Actual quantity"),
                ),
                (
                    "quantity_difference",
                    models.IntegerField(default=0, help_text="Quantity difference"),
                ),
                (
                    "expected_location",
                    models.CharField(
                        blank=True, help_text="Expected location", max_length=200
                    ),
                ),
                (
                    "actual_location",
                    models.CharField(
                        blank=True, help_text="Actual location", max_length=200
                    ),
                ),
                (
                    "expected_custodian",
                    models.CharField(
                        blank=True, help_text="Expected custodian", max_length=200
                    ),
                ),
                (
                    "actual_custodian",
                    models.CharField(
                        blank=True, help_text="Actual custodian", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Resolution status",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, help_text="Resolution description"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="Resolution timestamp", null=True
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related asset (null for surplus)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_differences",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who resolved the difference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_differences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Related inventory task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="differences",
                        to="inventory.inventorytask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Difference",
                "verbose_name_plural": "Inventory Differences",
                "db_table": "inventory_differences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTaskExecutor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary executor indicator"
                    ),
                ),
                (
                    "completed_count",
                    models.IntegerField(
                        default=0, help_text="Completed scan count by this executor"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        help_text="Task executor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Inventory task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executors_relation",
                        to="inventory.inventorytask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Task Executor",
                "verbose_name_plural": "Inventory Task Executors",
                "db_table": "inventory_task_executors",
            },
        ),
        migrations.AddIndex(
            model_name="inventorytask",
            index=models.Index(
                fields=["organization", "task_code"],
                name="inventory_t_organiz_df63d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytask",
            index=models.Index(
                fields=["organization", "status"], name="inventory_t_organiz_d59982_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytask",
            index=models.Index(
                fields=["organization", "inventory_type"],
                name="inventory_t_organiz_b036e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytask",
            index=models.Index(
                fields=["organization", "planned_date"],
                name="inventory_t_organiz_217520_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytask",
            index=models.Index(
                fields=["-created_at"], name="inventory_t_created_ea54b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorysnapshot",
            index=models.Index(
                fields=["task", "asset"], name="inventory_s_task_id_4e4354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorysnapshot",
            index=models.Index(
                fields=["task", "asset_code"], name="inventory_s_task_id_98d5cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorysnapshot",
            index=models.Index(
                fields=["task", "scanned"], name="inventory_s_task_id_cf8fec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorysnapshot",
            unique_together={("task", "asset")},
        ),
        migrations.AddIndex(
            model_name="inventoryscan",
            index=models.Index(
                fields=["task", "asset"], name="inventory_s_task_id_263a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryscan",
            index=models.Index(
                fields=["task", "scanned_by"], name="inventory_s_task_id_344a42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryscan",
            index=models.Index(
                fields=["task", "-scanned_at"], name="inventory_s_task_id_bad941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryscan",
            index=models.Index(
                fields=["scan_status"], name="inventory_s_scan_st_ab6a41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryscan",
            index=models.Index(
                fields=["qr_code"], name="inventory_s_qr_code_a72028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydifference",
            index=models.Index(
                fields=["task", "asset"], name="inventory_d_task_id_bb8dc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydifference",
            index=models.Index(
                fields=["task", "difference_type"],
                name="inventory_d_task_id_006ad3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydifference",
            index=models.Index(
                fields=["task", "status"], name="inventory_d_task_id_540a0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydifference",
            index=models.Index(
                fields=["-created_at"], name="inventory_d_created_962aac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytaskexecutor",
            index=models.Index(
                fields=["task", "executor"], name="inventory_t_task_id_1672cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytaskexecutor",
            index=models.Index(
                fields=["executor", "-created_at"],
                name="inventory_t_executo_0c544b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorytaskexecutor",
            unique_together={("task", "executor")},
        ),
    ]
