# Generated by Django 5.0.1 on 2026-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryscan",
            name="scanned_at",
            field=models.DateTimeField(
                blank=True, db_index=True, help_text="Scan timestamp", null=True
            ),
        ),
    ]
