# Generated by Django 5.0.1 on 2026-03-11 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_alter_loanitem_unique_together_and_more"),
        ("inventory", "0004_add_base_model_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorysnapshot",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Related asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_snapshots",
                to="assets.asset",
            ),
        ),
    ]
