# Generated by Django 5.0.1 on 2026-03-26 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_inventorysnapshot_asset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorydifference",
            name="approved_at",
            field=models.DateTimeField(blank=True, help_text="Approval timestamp", null=True),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved the difference resolution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_inventory_differences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who closed the difference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_inventory_differences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="closure_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="Difference closure timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="closure_notes",
            field=models.TextField(blank=True, help_text="Closure notes"),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="closure_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("location_correction", "Location Correction"),
                    ("custodian_correction", "Custodian Correction"),
                    ("repair", "Repair"),
                    ("disposal", "Disposal"),
                    ("create_asset_card", "Create Asset Card"),
                    ("financial_adjustment", "Financial Adjustment"),
                    ("invalid_difference", "Invalid Difference"),
                ],
                help_text="Closure type for the difference",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="evidence_refs",
            field=models.JSONField(
                blank=True, default=list, help_text="Evidence references for the difference closure"
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="linked_action_code",
            field=models.CharField(
                blank=True, help_text="Linked downstream action code", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned owner for difference handling",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_inventory_differences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="Review submission timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="inventorydifference",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted or reviewed the difference resolution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_inventory_differences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inventorydifference",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("in_review", "In Review"),
                    ("approved", "Approved"),
                    ("executing", "Executing"),
                    ("resolved", "Resolved"),
                    ("ignored", "Ignored"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="pending",
                help_text="Resolution status",
                max_length=20,
            ),
        ),
    ]
