# Generated by Django 5.0.1 on 2026-03-27 06:26

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_datetime


def backfill_inventory_follow_ups(apps, schema_editor):
    """Create follow-up ledger rows for legacy manual follow-up differences."""
    InventoryDifference = apps.get_model('inventory', 'InventoryDifference')
    InventoryFollowUp = apps.get_model('inventory', 'InventoryFollowUp')

    existing_difference_ids = set(
        InventoryFollowUp.objects.values_list('difference_id', flat=True)
    )
    differences = InventoryDifference.objects.filter(
        is_deleted=False,
    ).exclude(
        status='closed',
    )

    prefix = timezone.now().strftime('%Y%m')
    sequence = InventoryFollowUp.objects.filter(
        follow_up_code__startswith=f'IFU{prefix}'
    ).count()

    for diff in differences.iterator():
        if diff.id in existing_difference_ids:
            continue
        custom_fields = diff.custom_fields or {}
        execution_state = custom_fields.get('linked_action_execution') if isinstance(custom_fields, dict) else None
        if not isinstance(execution_state, dict):
            continue
        if not execution_state.get('can_send_follow_up'):
            continue

        sequence += 1
        last_notified_at = parse_datetime(str(execution_state.get('follow_up_last_sent_at') or ''))
        InventoryFollowUp.objects.create(
            id=uuid.uuid4(),
            organization_id=diff.organization_id,
            created_by_id=diff.created_by_id,
            updated_by_id=diff.updated_by_id,
            follow_up_code=f'IFU{prefix}{sequence:04d}',
            task_id=diff.task_id,
            difference_id=diff.id,
            asset_id=diff.asset_id,
            title=f'Inventory difference manual follow-up ({execution_state.get("action_code") or diff.linked_action_code or "manual"})',
            closure_type=diff.closure_type or '',
            linked_action_code=str(execution_state.get('action_code') or diff.linked_action_code or ''),
            status='pending',
            assignee_id=execution_state.get('follow_up_assignee_id') or diff.owner_id or diff.created_by_id,
            assigned_at=diff.resolved_at or diff.updated_at or diff.created_at,
            completed_at=None,
            completion_notes='',
            evidence_refs=[],
            follow_up_notification_id=str(execution_state.get('follow_up_notification_id') or ''),
            follow_up_notification_url=str(execution_state.get('follow_up_notification_url') or ''),
            last_notified_at=last_notified_at,
            reminder_count=int(execution_state.get('follow_up_sent_count') or 0),
        )


def noop_reverse(apps, schema_editor):
    """No-op reverse migration for seeded follow-up tasks."""
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0011_returnitem_project_allocation"),
        ("inventory", "0006_inventorydifference_approved_at_and_more"),
        ("organizations", "0005_add_base_model_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryFollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "follow_up_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique manual follow-up code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(help_text="Follow-up task title", max_length=255)),
                (
                    "closure_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("location_correction", "Location Correction"),
                            ("custodian_correction", "Custodian Correction"),
                            ("repair", "Repair"),
                            ("disposal", "Disposal"),
                            ("create_asset_card", "Create Asset Card"),
                            ("financial_adjustment", "Financial Adjustment"),
                            ("invalid_difference", "Invalid Difference"),
                        ],
                        help_text="Closure type that triggered the follow-up",
                        max_length=50,
                    ),
                ),
                (
                    "linked_action_code",
                    models.CharField(
                        blank=True, help_text="Linked downstream action code", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Follow-up task status",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, help_text="Time when the follow-up was assigned", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Time when the follow-up was completed", null=True
                    ),
                ),
                ("completion_notes", models.TextField(blank=True, help_text="Completion notes")),
                (
                    "evidence_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Evidence references for the follow-up completion",
                    ),
                ),
                (
                    "follow_up_notification_id",
                    models.CharField(
                        blank=True, help_text="Latest follow-up notification ID", max_length=100
                    ),
                ),
                (
                    "follow_up_notification_url",
                    models.CharField(
                        blank=True,
                        help_text="Notification center route for the follow-up",
                        max_length=255,
                    ),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True, help_text="Time when the latest reminder was sent", null=True
                    ),
                ),
                (
                    "reminder_count",
                    models.PositiveIntegerField(default=0, help_text="Reminder count"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_follow_up_tasks",
                        to="assets.asset",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Follow-up assignee",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_inventory_follow_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed the follow-up",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_inventory_follow_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who soft deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "difference",
                    models.ForeignKey(
                        help_text="Related inventory difference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_tasks",
                        to="inventory.inventorydifference",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Related inventory task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_tasks",
                        to="inventory.inventorytask",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Follow-up",
                "verbose_name_plural": "Inventory Follow-ups",
                "db_table": "inventory_follow_ups",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "follow_up_code"],
                        name="inventory_f_organiz_671653_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"], name="inventory_f_organiz_3a09a3_idx"
                    ),
                    models.Index(
                        fields=["organization", "assignee"], name="inventory_f_organiz_e484f8_idx"
                    ),
                    models.Index(fields=["task", "status"], name="inventory_f_task_id_8cf36b_idx"),
                    models.Index(
                        fields=["difference", "status"], name="inventory_f_differe_039542_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_inventory_follow_ups, noop_reverse),
    ]
