# Generated by Django 5.0.1 on 2026-03-29 09:30

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_inventoryfollowup"),
        ("organizations", "0005_add_base_model_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "reconciliation_no",
                    models.CharField(
                        db_index=True,
                        help_text="Unique reconciliation number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "normal_count",
                    models.IntegerField(default=0, help_text="Normal item count in reconciliation"),
                ),
                (
                    "abnormal_count",
                    models.IntegerField(default=0, help_text="Abnormal item count in reconciliation"),
                ),
                (
                    "difference_count",
                    models.IntegerField(default=0, help_text="Difference count in reconciliation"),
                ),
                (
                    "adjustment_count",
                    models.IntegerField(default=0, help_text="Adjustment count in reconciliation"),
                ),
                (
                    "adjustments",
                    models.JSONField(blank=True, default=list, help_text="Adjustment detail rows"),
                ),
                ("note", models.TextField(blank=True, help_text="Reconciliation note")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Reconciliation status",
                        max_length=20,
                    ),
                ),
                (
                    "reconciled_at",
                    models.DateTimeField(blank=True, help_text="Reconciliation time", null=True),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, help_text="Reconciliation submission time", null=True),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, help_text="Reconciliation approval time", null=True),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, help_text="Reconciliation rejection time", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current reconciliation approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_inventory_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who soft deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the reconciliation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Related inventory task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="inventory.inventorytask",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Reconciliation",
                "verbose_name_plural": "Inventory Reconciliations",
                "db_table": "inventory_reconciliations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "reconciliation_no"],
                        name="inventory_r_organiz_7eeb56_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="inventory_r_organiz_539d13_idx",
                    ),
                    models.Index(fields=["task", "status"], name="inventory_r_task_id_4e9391_idx"),
                    models.Index(fields=["reconciled_at"], name="inventory_r_reconci_1b973f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        db_index=True,
                        help_text="Unique inventory report number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "template_id",
                    models.CharField(blank=True, help_text="Selected report template ID", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Inventory report status",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, help_text="Top-level report summary"),
                ),
                (
                    "report_data",
                    models.JSONField(blank=True, default=dict, help_text="Structured report payload"),
                ),
                (
                    "approvals",
                    models.JSONField(blank=True, default=list, help_text="Approval history payload"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(blank=True, help_text="Report generation time", null=True),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, help_text="Report submission time", null=True),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, help_text="Report approval time", null=True),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, help_text="Report rejection time", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current report approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_inventory_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who soft deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_inventory_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Related inventory task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="inventory.inventorytask",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Report",
                "verbose_name_plural": "Inventory Reports",
                "db_table": "inventory_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "report_no"],
                        name="inventory_r_organiz_3d8ec5_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="inventory_r_organiz_8f84c1_idx",
                    ),
                    models.Index(fields=["task", "status"], name="inventory_r_task_id_67652c_idx"),
                    models.Index(fields=["generated_at"], name="inventory_r_generat_1f3490_idx"),
                ],
            },
        ),
    ]
