# Generated by Django 5.0.1 on 2026-03-30 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_inventoryreconciliation_inventoryreport"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inventoryreconciliation",
            new_name="inventory_r_organiz_69e920_idx",
            old_name="inventory_r_organiz_7eeb56_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryreconciliation",
            new_name="inventory_r_organiz_571a70_idx",
            old_name="inventory_r_organiz_539d13_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryreconciliation",
            new_name="inventory_r_task_id_18c23a_idx",
            old_name="inventory_r_task_id_4e9391_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryreconciliation",
            new_name="inventory_r_reconci_515b90_idx",
            old_name="inventory_r_reconci_1b973f_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryreport",
            new_name="inventory_r_organiz_9e4d67_idx",
            old_name="inventory_r_organiz_3d8ec5_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryreport",
            new_name="inventory_r_organiz_03b39f_idx",
            old_name="inventory_r_organiz_8f84c1_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryreport",
            new_name="inventory_r_task_id_acb195_idx",
            old_name="inventory_r_task_id_67652c_idx",
        ),
        migrations.RenameIndex(
            model_name="inventoryreport",
            new_name="inventory_r_generat_4798c1_idx",
            old_name="inventory_r_generat_1f3490_idx",
        ),
    ]
