# Generated by Django 5.0.1 on 2026-03-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0009_rename_inventory_r_organiz_7eeb56_idx_inventory_r_organiz_69e920_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytask",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                help_text="Current workflow approval status of this document",
                max_length=20,
                verbose_name="Approval Status",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the document was approved",
                null=True,
                verbose_name="Approved At",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the document was submitted for approval",
                null=True,
                verbose_name="Submitted At",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="workflow_instance_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="ID of the linked WorkflowInstance",
                null=True,
                verbose_name="Workflow Instance ID",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytask",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                help_text="Task status",
                max_length=20,
            ),
        ),
    ]
