# Generated by Django 5.0.1 on 2026-01-18 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0002_asset_assetloan_assetpickup_assetstatuslog_and_more"),
        ("organizations", "0002_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "request_no",
                    models.CharField(
                        db_index=True,
                        help_text="Request number (auto-generated: DS+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("appraising", "Appraising"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                (
                    "disposal_type",
                    models.CharField(
                        choices=[
                            ("scrap", "Scrap"),
                            ("sale", "Sale"),
                            ("donation", "Donation"),
                            ("transfer", "Transfer"),
                            ("destroy", "Destroy"),
                        ],
                        default="scrap",
                        help_text="Disposal type",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateField(help_text="Request date")),
                ("disposal_reason", models.TextField(help_text="Disposal reason")),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("damage", "Damaged Beyond Repair"),
                            ("obsolete", "Obsolete"),
                            ("expired", "Expired"),
                            ("excess", "Excess"),
                            ("other", "Other"),
                        ],
                        help_text="Reason type",
                        max_length=50,
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Applicant",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_disposal_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Applicant department",
                        limit_choices_to={"org_type": "department"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposal Request",
                "verbose_name_plural": "Disposal Requests",
                "db_table": "lifecycle_disposal_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisposalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=1, help_text="Sequence number"),
                ),
                (
                    "original_value",
                    models.DecimalField(
                        decimal_places=2, help_text="Original value", max_digits=15
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Accumulated depreciation",
                        max_digits=15,
                    ),
                ),
                (
                    "net_value",
                    models.DecimalField(
                        decimal_places=2, help_text="Net value", max_digits=15
                    ),
                ),
                (
                    "appraisal_result",
                    models.TextField(
                        blank=True, help_text="Appraisal result", null=True
                    ),
                ),
                (
                    "residual_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated residual value",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "appraised_at",
                    models.DateTimeField(
                        blank=True, help_text="Appraisal time", null=True
                    ),
                ),
                (
                    "disposal_executed",
                    models.BooleanField(default=False, help_text="Disposal executed"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, help_text="Execution time", null=True
                    ),
                ),
                (
                    "actual_residual_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual residual value",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "buyer_info",
                    models.TextField(
                        blank=True, help_text="Buyer information", null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remarks")),
                (
                    "appraised_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Appraiser",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraised_disposal_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset to dispose",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_items",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "disposal_request",
                    models.ForeignKey(
                        help_text="Disposal request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lifecycle.disposalrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposal Item",
                "verbose_name_plural": "Disposal Items",
                "db_table": "lifecycle_disposal_item",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "maintenance_no",
                    models.CharField(
                        db_index=True,
                        help_text="Maintenance number (auto-generated: MT+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("assigned", "Assigned"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="reported",
                        help_text="Maintenance status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level",
                        max_length=20,
                    ),
                ),
                ("report_time", models.DateTimeField(help_text="Report time")),
                ("fault_description", models.TextField(help_text="Fault description")),
                (
                    "fault_photo_urls",
                    models.JSONField(
                        blank=True, default=list, help_text="Fault photo URLs"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, help_text="Assignment time", null=True
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, help_text="Start time", null=True),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, help_text="End time", null=True),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Work hours",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "fault_cause",
                    models.TextField(blank=True, help_text="Fault cause", null=True),
                ),
                (
                    "repair_method",
                    models.TextField(blank=True, help_text="Repair method", null=True),
                ),
                (
                    "replaced_parts",
                    models.TextField(blank=True, help_text="Replaced parts", null=True),
                ),
                (
                    "repair_result",
                    models.TextField(blank=True, help_text="Repair result", null=True),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Labor cost",
                        max_digits=10,
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Material cost",
                        max_digits=10,
                    ),
                ),
                (
                    "other_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Other cost",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost",
                        max_digits=12,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Verification time", null=True
                    ),
                ),
                (
                    "verification_result",
                    models.TextField(
                        blank=True, help_text="Verification result", null=True
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being maintained",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="Reporter",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned technician",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verifier",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "db_table": "lifecycle_maintenance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                ("plan_name", models.CharField(help_text="Plan name", max_length=200)),
                (
                    "plan_code",
                    models.CharField(
                        db_index=True, help_text="Plan code", max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Plan status",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("category", "By Category"),
                            ("asset", "By Asset"),
                            ("location", "By Location"),
                        ],
                        default="category",
                        help_text="Target type",
                        max_length=20,
                    ),
                ),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        help_text="Cycle type",
                        max_length=20,
                    ),
                ),
                (
                    "cycle_value",
                    models.IntegerField(default=1, help_text="Cycle value"),
                ),
                ("start_date", models.DateField(help_text="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="End date", null=True),
                ),
                (
                    "remind_days_before",
                    models.IntegerField(default=3, help_text="Remind days before"),
                ),
                (
                    "maintenance_content",
                    models.TextField(help_text="Maintenance content"),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=1, help_text="Estimated hours", max_digits=5
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "asset_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Asset categories",
                        related_name="maintenance_plans",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific assets",
                        related_name="maintenance_plans",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "remind_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Remind users",
                        related_name="maintenance_plans_reminded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Plan",
                "verbose_name_plural": "Maintenance Plans",
                "db_table": "lifecycle_maintenance_plan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "task_no",
                    models.CharField(
                        db_index=True,
                        help_text="Task number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        help_text="Task status",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(help_text="Scheduled date")),
                ("deadline_date", models.DateField(help_text="Deadline date")),
                (
                    "start_time",
                    models.DateTimeField(blank=True, help_text="Start time", null=True),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, help_text="End time", null=True),
                ),
                (
                    "execution_content",
                    models.TextField(
                        blank=True, help_text="Execution content", null=True
                    ),
                ),
                (
                    "execution_photo_urls",
                    models.JSONField(
                        blank=True, default=list, help_text="Execution photo URLs"
                    ),
                ),
                (
                    "finding",
                    models.TextField(blank=True, help_text="Findings", null=True),
                ),
                (
                    "next_maintenance_suggestion",
                    models.TextField(
                        blank=True, help_text="Next maintenance suggestion", null=True
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Verification time", null=True
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tasks",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Executor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Maintenance plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="lifecycle.maintenanceplan",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verifier",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_maintenance_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Task",
                "verbose_name_plural": "Maintenance Tasks",
                "db_table": "lifecycle_maintenance_task",
                "ordering": ["scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "request_no",
                    models.CharField(
                        db_index=True,
                        help_text="Request number (auto-generated: PR+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateField(help_text="Request date")),
                ("expected_date", models.DateField(help_text="Expected delivery date")),
                ("reason", models.TextField(help_text="Request reason")),
                (
                    "budget_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Approval time", null=True
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, help_text="Approval comment"),
                ),
                (
                    "m18_purchase_order_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="M18 purchase order number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "pushed_to_m18_at",
                    models.DateTimeField(
                        blank=True, help_text="Time pushed to M18", null=True
                    ),
                ),
                (
                    "m18_sync_status",
                    models.CharField(
                        blank=True,
                        help_text="M18 sync status",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Request applicant",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current approver",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_purchase_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Applicant department",
                        limit_choices_to={"org_type": "department"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Request",
                "verbose_name_plural": "Purchase Requests",
                "db_table": "lifecycle_purchase_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(
                        db_index=True,
                        help_text="Receipt number (auto-generated: RC+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("inspecting", "Inspecting"),
                            ("passed", "Passed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Receipt status",
                        max_length=20,
                    ),
                ),
                (
                    "m18_purchase_order_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="M18 purchase order number",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("receipt_date", models.DateField(help_text="Receipt date")),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("transfer", "Transfer"),
                            ("return", "Return"),
                        ],
                        default="purchase",
                        help_text="Receipt type",
                        max_length=20,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, help_text="Supplier name", max_length=200, null=True
                    ),
                ),
                (
                    "delivery_no",
                    models.CharField(
                        blank=True,
                        help_text="Delivery number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "inspection_result",
                    models.TextField(
                        blank=True, help_text="Inspection result", null=True
                    ),
                ),
                (
                    "passed_at",
                    models.DateTimeField(
                        blank=True, help_text="Passed time", null=True
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Inspector",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspected_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="Receiver",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked purchase request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="lifecycle.purchaserequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Receipt",
                "verbose_name_plural": "Asset Receipts",
                "db_table": "lifecycle_asset_receipt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=1, help_text="Sequence number"),
                ),
                ("item_name", models.CharField(help_text="Item name", max_length=200)),
                (
                    "specification",
                    models.TextField(blank=True, help_text="Specification"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, help_text="Brand", max_length=100),
                ),
                ("quantity", models.IntegerField(help_text="Quantity")),
                ("unit", models.CharField(help_text="Unit", max_length=20)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Unit price", max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount", max_digits=15
                    ),
                ),
                (
                    "suggested_supplier",
                    models.CharField(
                        blank=True, help_text="Suggested supplier", max_length=200
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remarks")),
                (
                    "asset_category",
                    models.ForeignKey(
                        help_text="Asset category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_request_items",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        help_text="Purchase request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lifecycle.purchaserequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Request Item",
                "verbose_name_plural": "Purchase Request Items",
                "db_table": "lifecycle_purchase_request_item",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="AssetReceiptItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=1, help_text="Sequence number"),
                ),
                ("item_name", models.CharField(help_text="Item name", max_length=200)),
                (
                    "specification",
                    models.TextField(blank=True, help_text="Specification"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, help_text="Brand", max_length=100),
                ),
                ("ordered_quantity", models.IntegerField(help_text="Ordered quantity")),
                (
                    "received_quantity",
                    models.IntegerField(help_text="Received quantity"),
                ),
                (
                    "qualified_quantity",
                    models.IntegerField(default=0, help_text="Qualified quantity"),
                ),
                (
                    "defective_quantity",
                    models.IntegerField(default=0, help_text="Defective quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Unit price", max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount", max_digits=15
                    ),
                ),
                (
                    "asset_generated",
                    models.BooleanField(
                        default=False, help_text="Asset cards generated"
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remarks")),
                (
                    "asset_category",
                    models.ForeignKey(
                        help_text="Asset category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_items",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "asset_receipt",
                    models.ForeignKey(
                        help_text="Asset receipt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lifecycle.assetreceipt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Receipt Item",
                "verbose_name_plural": "Asset Receipt Items",
                "db_table": "lifecycle_asset_receipt_item",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["organization", "asset_receipt"],
                        name="lifecycle_a_organiz_8decc3_idx",
                    ),
                    models.Index(
                        fields=["organization", "asset_category"],
                        name="lifecycle_a_organiz_1c36b6_idx",
                    ),
                ],
                "unique_together": {("asset_receipt", "sequence")},
            },
        ),
        migrations.AddIndex(
            model_name="disposalrequest",
            index=models.Index(
                fields=["organization", "request_no"],
                name="lifecycle_d_organiz_86f6c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disposalrequest",
            index=models.Index(
                fields=["organization", "status"], name="lifecycle_d_organiz_97f9ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disposalrequest",
            index=models.Index(
                fields=["organization", "disposal_type"],
                name="lifecycle_d_organiz_235507_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disposalitem",
            index=models.Index(
                fields=["organization", "disposal_request"],
                name="lifecycle_d_organiz_4b1e39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disposalitem",
            index=models.Index(
                fields=["organization", "asset"], name="lifecycle_d_organiz_0dcd1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="disposalitem",
            unique_together={("disposal_request", "sequence")},
        ),
        migrations.AddIndex(
            model_name="maintenance",
            index=models.Index(
                fields=["organization", "maintenance_no"],
                name="lifecycle_m_organiz_03eb87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenance",
            index=models.Index(
                fields=["organization", "status"], name="lifecycle_m_organiz_3bde20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenance",
            index=models.Index(
                fields=["organization", "asset"], name="lifecycle_m_organiz_d7b629_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenance",
            index=models.Index(
                fields=["organization", "priority"],
                name="lifecycle_m_organiz_f0127c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceplan",
            index=models.Index(
                fields=["organization", "plan_code"],
                name="lifecycle_m_organiz_488383_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceplan",
            index=models.Index(
                fields=["organization", "status"], name="lifecycle_m_organiz_80deb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["organization", "task_no"],
                name="lifecycle_m_organiz_af1d41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["organization", "status"], name="lifecycle_m_organiz_279a80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["organization", "plan"], name="lifecycle_m_organiz_cc228e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancetask",
            index=models.Index(
                fields=["organization", "asset"], name="lifecycle_m_organiz_df1deb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["organization", "request_no"],
                name="lifecycle_p_organiz_abb78b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["organization", "status"], name="lifecycle_p_organiz_0412c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["organization", "applicant"],
                name="lifecycle_p_organiz_38b22d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["organization", "department"],
                name="lifecycle_p_organiz_1fd168_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetreceipt",
            index=models.Index(
                fields=["organization", "receipt_no"],
                name="lifecycle_a_organiz_45afdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetreceipt",
            index=models.Index(
                fields=["organization", "status"], name="lifecycle_a_organiz_fa74c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetreceipt",
            index=models.Index(
                fields=["organization", "purchase_request"],
                name="lifecycle_a_organiz_1cdfd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequestitem",
            index=models.Index(
                fields=["organization", "purchase_request"],
                name="lifecycle_p_organiz_7f709c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequestitem",
            index=models.Index(
                fields=["organization", "asset_category"],
                name="lifecycle_p_organiz_385388_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaserequestitem",
            unique_together={("purchase_request", "sequence")},
        ),
    ]
