# Generated by Django 5.2.10 on 2026-03-08 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_backfill_asset_systemfile_links'),
        ('lifecycle', '0002_add_base_model_fields'),
        ('organizations', '0005_add_base_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetWarranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('warranty_no', models.CharField(db_index=True, help_text='Warranty number (auto-generated: WR+YYYYMM+NNNN)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expiring', 'Expiring Soon'), ('expired', 'Expired'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Warranty status', max_length=20)),
                ('warranty_type', models.CharField(choices=[('manufacturer', 'Manufacturer Warranty'), ('extended', 'Extended Warranty'), ('third_party', 'Third-Party Warranty'), ('service_contract', 'Service Contract')], default='manufacturer', help_text='Warranty type', max_length=30)),
                ('start_date', models.DateField(help_text='Warranty start date')),
                ('end_date', models.DateField(help_text='Warranty end date')),
                ('coverage_description', models.TextField(blank=True, help_text='Warranty coverage description')),
                ('warranty_provider', models.CharField(help_text='Warranty provider name', max_length=200)),
                ('provider_contact', models.CharField(blank=True, help_text='Provider contact person', max_length=100)),
                ('provider_phone', models.CharField(blank=True, help_text='Provider phone number', max_length=50)),
                ('provider_email', models.EmailField(blank=True, help_text='Provider email', max_length=254)),
                ('warranty_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Warranty cost', max_digits=12, null=True)),
                ('contract_no', models.CharField(blank=True, help_text='Warranty contract number', max_length=100)),
                ('document_urls', models.JSONField(blank=True, default=list, help_text='Warranty document URLs')),
                ('claim_count', models.PositiveIntegerField(default=0, help_text='Number of claims made')),
                ('last_claim_date', models.DateField(blank=True, help_text='Date of last claim', null=True)),
                ('remark', models.TextField(blank=True, help_text='Additional remarks')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Activation time', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Expiration time', null=True)),
                ('asset', models.ForeignKey(help_text='Warranted asset', on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('purchase_request', models.ForeignKey(blank=True, help_text='Associated purchase request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='lifecycle.purchaserequest')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Asset Warranty',
                'verbose_name_plural': 'Asset Warranties',
                'db_table': 'lifecycle_asset_warranty',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'warranty_no'], name='lifecycle_a_organiz_7dd5e6_idx'), models.Index(fields=['organization', 'status'], name='lifecycle_a_organiz_294f36_idx'), models.Index(fields=['organization', 'asset'], name='lifecycle_a_organiz_fb0b75_idx'), models.Index(fields=['organization', 'end_date'], name='lifecycle_a_organiz_ddfde5_idx')],
            },
        ),
    ]
