# Generated by Django 5.0.1 on 2026-01-18 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0002_asset_assetloan_assetpickup_assetstatuslog_and_more"),
        ("organizations", "0002_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumableCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Category code (unique)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
                (
                    "level",
                    models.IntegerField(
                        default=1, help_text="Hierarchy level (1=top level)"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Category path for display",
                        max_length=500,
                    ),
                ),
                (
                    "enable_alert",
                    models.BooleanField(
                        default=True, help_text="Enable stock alert for this category"
                    ),
                ),
                (
                    "min_stock",
                    models.IntegerField(
                        default=10, help_text="Minimum stock level for alert"
                    ),
                ),
                (
                    "max_stock",
                    models.IntegerField(default=100, help_text="Maximum stock level"),
                ),
                (
                    "reorder_point",
                    models.IntegerField(
                        default=20, help_text="Reorder point to trigger purchase"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="件", help_text="Default unit of measure", max_length=20
                    ),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reference purchase price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether category is active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "default_supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default supplier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumable_categories",
                        to="assets.supplier",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="consumables.consumablecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumable Category",
                "verbose_name_plural": "Consumable Categories",
                "db_table": "consumable_categories",
                "ordering": ["path", "code"],
            },
        ),
        migrations.CreateModel(
            name="Consumable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Consumable code (unique)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Consumable name", max_length=200)),
                (
                    "specification",
                    models.CharField(
                        blank=True, help_text="Specification or model", max_length=200
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, help_text="Brand", max_length=100),
                ),
                (
                    "unit",
                    models.CharField(
                        default="件", help_text="Unit of measure", max_length=20
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, help_text="Current stock quantity"),
                ),
                (
                    "available_stock",
                    models.IntegerField(
                        default=0, help_text="Available stock (not locked)"
                    ),
                ),
                (
                    "locked_stock",
                    models.IntegerField(
                        default=0, help_text="Locked stock (pending orders)"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Last purchase price",
                        max_digits=10,
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weighted average price",
                        max_digits=10,
                    ),
                ),
                (
                    "min_stock",
                    models.IntegerField(default=10, help_text="Minimum stock level"),
                ),
                (
                    "max_stock",
                    models.IntegerField(default=100, help_text="Maximum stock level"),
                ),
                (
                    "reorder_point",
                    models.IntegerField(default=20, help_text="Reorder point"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                        ],
                        db_index=True,
                        default="normal",
                        help_text="Stock status",
                        max_length=20,
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default warehouse location",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumables",
                        to="assets.location",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumables",
                        to="consumables.consumablecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumable",
                "verbose_name_plural": "Consumables",
                "db_table": "consumables",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ConsumableIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "issue_no",
                    models.CharField(
                        db_index=True,
                        help_text="Issue order number (auto-generated: CI+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("issue_date", models.DateField(help_text="Issue date")),
                (
                    "issue_reason",
                    models.TextField(blank=True, help_text="Reason for issue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("issued", "Issued"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Issue order status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Approval timestamp", null=True
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, help_text="Approval comment"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, help_text="Issuance timestamp", null=True
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Applicant",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumable_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who approved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumable_issues",
                        to="organizations.organization",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who issued items",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_consumables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Order",
                "verbose_name_plural": "Issue Orders",
                "db_table": "consumable_issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsumablePurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "purchase_no",
                    models.CharField(
                        db_index=True,
                        help_text="Purchase order number (auto-generated: CP+YYYYMM+NNNN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("purchase_date", models.DateField(help_text="Purchase date")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total purchase amount",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("received", "Received"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Purchase order status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Approval timestamp", null=True
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, help_text="Approval comment"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, help_text="Receiving timestamp", null=True
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who approved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who received goods",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumable_purchases",
                        to="assets.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "db_table": "consumable_purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsumableStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("issue", "Issue"),
                            ("return", "Return"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("inventory_add", "Inventory Addition"),
                            ("inventory_reduce", "Inventory Reduction"),
                            ("adjustment", "Adjustment"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity (positive for in, negative for out)"
                    ),
                ),
                (
                    "before_stock",
                    models.IntegerField(
                        default=0, help_text="Stock before transaction"
                    ),
                ),
                (
                    "after_stock",
                    models.IntegerField(default=0, help_text="Stock after transaction"),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="Source type (purchase/issue/etc)",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, help_text="Source record ID", max_length=100
                    ),
                ),
                (
                    "source_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Source document number",
                        max_length=100,
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, help_text="Transaction remarks"),
                ),
                (
                    "consumable",
                    models.ForeignKey(
                        help_text="Consumable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_logs",
                        to="consumables.consumable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who handled transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction",
                "verbose_name_plural": "Stock Transactions",
                "db_table": "consumable_stock_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Issue quantity")),
                (
                    "snapshot_before_stock",
                    models.IntegerField(
                        default=0, help_text="Stock before issuance (snapshot)"
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remarks")),
                (
                    "consumable",
                    models.ForeignKey(
                        help_text="Consumable",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="consumables.consumable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        help_text="Issue order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="consumables.consumableissue",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Item",
                "verbose_name_plural": "Issue Items",
                "db_table": "consumable_issue_items",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Purchase quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Unit price", max_digits=10
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount (quantity * unit_price)",
                        max_digits=12,
                    ),
                ),
                ("remark", models.TextField(blank=True, help_text="Item remarks")),
                (
                    "consumable",
                    models.ForeignKey(
                        help_text="Consumable",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="consumables.consumable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        help_text="Purchase order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="consumables.consumablepurchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Item",
                "verbose_name_plural": "Purchase Items",
                "db_table": "consumable_purchase_items",
            },
        ),
        migrations.AddIndex(
            model_name="consumablecategory",
            index=models.Index(
                fields=["organization", "code"], name="consumable__organiz_b3ec4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumablecategory",
            index=models.Index(
                fields=["organization", "parent"], name="consumable__organiz_9a9109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumablecategory",
            index=models.Index(
                fields=["organization", "is_active"],
                name="consumable__organiz_bbe027_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumable",
            index=models.Index(
                fields=["organization", "code"], name="consumables_organiz_f0d423_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumable",
            index=models.Index(
                fields=["organization", "category"],
                name="consumables_organiz_0b89f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumable",
            index=models.Index(
                fields=["organization", "status"], name="consumables_organiz_6e055c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumable",
            index=models.Index(
                fields=["organization", "warehouse"],
                name="consumables_organiz_ebb4a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumableissue",
            index=models.Index(
                fields=["organization", "issue_no"],
                name="consumable__organiz_2c3e66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumableissue",
            index=models.Index(
                fields=["organization", "applicant"],
                name="consumable__organiz_38ce43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumableissue",
            index=models.Index(
                fields=["organization", "department"],
                name="consumable__organiz_f42edd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumableissue",
            index=models.Index(
                fields=["organization", "status"], name="consumable__organiz_d20a62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumableissue",
            index=models.Index(
                fields=["organization", "issue_date"],
                name="consumable__organiz_f8e7e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumablepurchase",
            index=models.Index(
                fields=["organization", "purchase_no"],
                name="consumable__organiz_a61a7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumablepurchase",
            index=models.Index(
                fields=["organization", "supplier"],
                name="consumable__organiz_c86529_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumablepurchase",
            index=models.Index(
                fields=["organization", "status"], name="consumable__organiz_0eb667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumablepurchase",
            index=models.Index(
                fields=["organization", "purchase_date"],
                name="consumable__organiz_e87034_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumablestock",
            index=models.Index(
                fields=["organization", "consumable", "-created_at"],
                name="consumable__organiz_44f3e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumablestock",
            index=models.Index(
                fields=["organization", "transaction_type"],
                name="consumable__organiz_4c782a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consumablestock",
            index=models.Index(
                fields=["organization", "source_type", "source_id"],
                name="consumable__organiz_c93d03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issueitem",
            index=models.Index(
                fields=["organization", "issue"], name="consumable__organiz_184621_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issueitem",
            index=models.Index(
                fields=["organization", "consumable"],
                name="consumable__organiz_7e45c4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issueitem",
            unique_together={("issue", "consumable")},
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(
                fields=["organization", "purchase"],
                name="consumable__organiz_4aa650_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseitem",
            index=models.Index(
                fields=["organization", "consumable"],
                name="consumable__organiz_4c4ade_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseitem",
            unique_together={("purchase", "consumable")},
        ),
    ]
