# Generated by Django 5.2.10 on 2026-01-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0003_seed_dictionaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='status',
            field=models.CharField(db_index=True, default='normal', help_text='Stock status', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='unit',
            field=models.CharField(default='unit', help_text='Unit of measure', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumablecategory',
            name='unit',
            field=models.CharField(default='unit', help_text='Default unit of measure', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumableissue',
            name='status',
            field=models.CharField(db_index=True, default='draft', help_text='Issue order status', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumablepurchase',
            name='status',
            field=models.CharField(db_index=True, default='draft', help_text='Purchase order status', max_length=50),
        ),
    ]
