# Generated by Django 5.2.10 on 2026-03-20 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0010_asset_source_traceability"),
        ("organizations", "0005_add_base_model_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetProject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(db_comment="Soft delete flag, records are filtered out by default", db_index=True, default=False, verbose_name="Is Deleted")),
                ("deleted_at", models.DateTimeField(blank=True, db_comment="Timestamp when record was soft deleted", null=True, verbose_name="Deleted At")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="Timestamp when record was created", verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, db_comment="Timestamp when record was last updated", verbose_name="Updated At")),
                ("custom_fields", models.JSONField(blank=True, db_comment="Dynamic fields for metadata-driven extensions", default=dict, verbose_name="Custom Fields")),
                ("project_code", models.CharField(db_index=True, help_text="Project code (auto-generated: XM+YYYYMM+NNNN)", max_length=50, unique=True)),
                ("project_name", models.CharField(help_text="Project name", max_length=200)),
                ("project_alias", models.CharField(blank=True, help_text="Project alias or short name", max_length=100)),
                ("project_type", models.CharField(choices=[("research", "Research"), ("development", "Development"), ("infrastructure", "Infrastructure"), ("implementation", "Implementation"), ("other", "Other")], default="development", help_text="Project type", max_length=20)),
                ("status", models.CharField(choices=[("planning", "Planning"), ("active", "Active"), ("suspended", "Suspended"), ("completed", "Completed"), ("cancelled", "Cancelled")], db_index=True, default="planning", help_text="Project status", max_length=20)),
                ("start_date", models.DateField(help_text="Planned start date")),
                ("end_date", models.DateField(blank=True, help_text="Planned end date", null=True)),
                ("actual_start_date", models.DateField(blank=True, help_text="Actual start date", null=True)),
                ("actual_end_date", models.DateField(blank=True, help_text="Actual end date", null=True)),
                ("planned_budget", models.DecimalField(blank=True, decimal_places=2, help_text="Planned budget amount", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ("actual_cost", models.DecimalField(decimal_places=2, default=0, help_text="Actual incurred cost", max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("asset_cost", models.DecimalField(decimal_places=2, default=0, help_text="Allocated asset cost", max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("description", models.TextField(blank=True, help_text="Project description")),
                ("technical_requirements", models.TextField(blank=True, help_text="Technical requirements")),
                ("total_assets", models.IntegerField(default=0, help_text="Total allocated assets")),
                ("active_assets", models.IntegerField(default=0, help_text="Currently active allocated assets")),
                ("completed_milestones", models.IntegerField(default=0, help_text="Completed milestone count")),
                ("total_milestones", models.IntegerField(default=0, help_text="Total milestone count")),
                ("created_by", models.ForeignKey(blank=True, db_comment="User who created this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, db_comment="User who soft deleted this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_deleted", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("department", models.ForeignKey(help_text="Owning department", on_delete=django.db.models.deletion.PROTECT, related_name="asset_projects", to="organizations.department")),
                ("organization", models.ForeignKey(blank=True, db_comment="Organization for multi-tenant data isolation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization", verbose_name="Organization")),
                ("project_manager", models.ForeignKey(help_text="Project manager", on_delete=django.db.models.deletion.PROTECT, related_name="managed_asset_projects", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, db_comment="User who last updated this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
            ],
            options={
                "verbose_name": "Asset Project",
                "verbose_name_plural": "Asset Projects",
                "db_table": "asset_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(db_comment="Soft delete flag, records are filtered out by default", db_index=True, default=False, verbose_name="Is Deleted")),
                ("deleted_at", models.DateTimeField(blank=True, db_comment="Timestamp when record was soft deleted", null=True, verbose_name="Deleted At")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="Timestamp when record was created", verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, db_comment="Timestamp when record was last updated", verbose_name="Updated At")),
                ("custom_fields", models.JSONField(blank=True, db_comment="Dynamic fields for metadata-driven extensions", default=dict, verbose_name="Custom Fields")),
                ("allocation_no", models.CharField(db_index=True, help_text="Allocation number (auto-generated: FP+YYYYMM+NNNN)", max_length=50, unique=True)),
                ("allocation_date", models.DateField(default=django.utils.timezone.now, help_text="Allocation date")),
                ("allocation_type", models.CharField(choices=[("permanent", "Permanent"), ("temporary", "Temporary"), ("shared", "Shared")], default="permanent", help_text="Allocation type", max_length=20)),
                ("return_date", models.DateField(blank=True, help_text="Planned return date", null=True)),
                ("actual_return_date", models.DateField(blank=True, help_text="Actual return date", null=True)),
                ("return_status", models.CharField(choices=[("in_use", "In Use"), ("returned", "Returned"), ("transferred", "Transferred")], default="in_use", help_text="Asset return status", max_length=20)),
                ("allocation_cost", models.DecimalField(decimal_places=2, default=0, help_text="Asset cost snapshot at allocation time", max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("depreciation_rate", models.DecimalField(decimal_places=4, default=Decimal("1.0000"), help_text="Depreciation share ratio", max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ("monthly_depreciation", models.DecimalField(decimal_places=2, default=0, help_text="Monthly depreciation amount allocated to the project", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("purpose", models.TextField(blank=True, help_text="Usage purpose")),
                ("usage_location", models.CharField(blank=True, help_text="Usage location", max_length=200)),
                ("asset_snapshot", models.JSONField(blank=True, default=dict, help_text="Asset snapshot at allocation time")),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("allocated_by", models.ForeignKey(help_text="User who allocated the asset", on_delete=django.db.models.deletion.PROTECT, related_name="project_assets_allocated", to=settings.AUTH_USER_MODEL)),
                ("asset", models.ForeignKey(help_text="Allocated asset", on_delete=django.db.models.deletion.PROTECT, related_name="project_allocations", to="assets.asset")),
                ("created_by", models.ForeignKey(blank=True, db_comment="User who created this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("custodian", models.ForeignKey(blank=True, help_text="Current custodian", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="project_assets_custodied", to=settings.AUTH_USER_MODEL)),
                ("deleted_by", models.ForeignKey(blank=True, db_comment="User who soft deleted this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_deleted", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("organization", models.ForeignKey(blank=True, db_comment="Organization for multi-tenant data isolation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization", verbose_name="Organization")),
                ("project", models.ForeignKey(help_text="Assigned project", on_delete=django.db.models.deletion.PROTECT, related_name="project_assets", to="projects.assetproject")),
                ("updated_by", models.ForeignKey(blank=True, db_comment="User who last updated this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
            ],
            options={
                "verbose_name": "Project Asset",
                "verbose_name_plural": "Project Assets",
                "db_table": "project_assets",
                "ordering": ["-allocation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_deleted", models.BooleanField(db_comment="Soft delete flag, records are filtered out by default", db_index=True, default=False, verbose_name="Is Deleted")),
                ("deleted_at", models.DateTimeField(blank=True, db_comment="Timestamp when record was soft deleted", null=True, verbose_name="Deleted At")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="Timestamp when record was created", verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, db_comment="Timestamp when record was last updated", verbose_name="Updated At")),
                ("custom_fields", models.JSONField(blank=True, db_comment="Dynamic fields for metadata-driven extensions", default=dict, verbose_name="Custom Fields")),
                ("role", models.CharField(choices=[("manager", "Manager"), ("member", "Member"), ("observer", "Observer")], default="member", help_text="Project role", max_length=20)),
                ("is_primary", models.BooleanField(default=False, help_text="Whether the user is the primary member")),
                ("join_date", models.DateField(default=django.utils.timezone.now, help_text="Join date")),
                ("leave_date", models.DateField(blank=True, help_text="Leave date", null=True)),
                ("is_active", models.BooleanField(default=True, help_text="Whether the membership is active")),
                ("responsibilities", models.TextField(blank=True, help_text="Responsibility summary")),
                ("can_allocate_asset", models.BooleanField(default=False, help_text="Whether the member can allocate assets")),
                ("can_view_cost", models.BooleanField(default=False, help_text="Whether the member can view cost data")),
                ("created_by", models.ForeignKey(blank=True, db_comment="User who created this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("deleted_by", models.ForeignKey(blank=True, db_comment="User who soft deleted this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_deleted", to=settings.AUTH_USER_MODEL, verbose_name="Deleted By")),
                ("organization", models.ForeignKey(blank=True, db_comment="Organization for multi-tenant data isolation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization", verbose_name="Organization")),
                ("project", models.ForeignKey(help_text="Associated project", on_delete=django.db.models.deletion.CASCADE, related_name="members", to="projects.assetproject")),
                ("updated_by", models.ForeignKey(blank=True, db_comment="User who last updated this record", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Updated By")),
                ("user", models.ForeignKey(help_text="Project member", on_delete=django.db.models.deletion.PROTECT, related_name="project_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "db_table": "project_members",
                "ordering": ["-is_primary", "join_date", "created_at"],
                "unique_together": {("project", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="assetproject",
            index=models.Index(fields=["organization", "project_code"], name="asset_proje_organiz_efbe85_idx"),
        ),
        migrations.AddIndex(
            model_name="assetproject",
            index=models.Index(fields=["organization", "status"], name="asset_proje_organiz_bae58e_idx"),
        ),
        migrations.AddIndex(
            model_name="assetproject",
            index=models.Index(fields=["organization", "project_type"], name="asset_proje_organiz_12d95f_idx"),
        ),
        migrations.AddIndex(
            model_name="assetproject",
            index=models.Index(fields=["organization", "department"], name="asset_proje_organiz_02f7e5_idx"),
        ),
        migrations.AddIndex(
            model_name="assetproject",
            index=models.Index(fields=["organization", "project_manager"], name="asset_proje_organiz_9409aa_idx"),
        ),
        migrations.AddIndex(
            model_name="assetproject",
            index=models.Index(fields=["organization", "start_date", "end_date"], name="asset_proje_organiz_e73b7b_idx"),
        ),
        migrations.AddIndex(
            model_name="projectasset",
            index=models.Index(fields=["organization", "project"], name="project_asse_organiz_5ff95a_idx"),
        ),
        migrations.AddIndex(
            model_name="projectasset",
            index=models.Index(fields=["organization", "asset"], name="project_asse_organiz_a1d9c8_idx"),
        ),
        migrations.AddIndex(
            model_name="projectasset",
            index=models.Index(fields=["organization", "return_status"], name="project_asse_organiz_5e0abc_idx"),
        ),
        migrations.AddIndex(
            model_name="projectasset",
            index=models.Index(fields=["organization", "allocation_date"], name="project_asse_organiz_356c73_idx"),
        ),
        migrations.AddIndex(
            model_name="projectasset",
            index=models.Index(fields=["organization", "custodian"], name="project_asse_organiz_6036b6_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(fields=["organization", "project"], name="project_memb_organiz_e5e996_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(fields=["organization", "user"], name="project_memb_organiz_d292ef_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(fields=["organization", "is_active"], name="project_memb_organiz_25374c_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(fields=["organization", "role"], name="project_memb_organiz_8082ca_idx"),
        ),
    ]
