# Generated by Django 5.0.1 on 2026-03-30 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assetproject",
            new_name="asset_proje_organiz_de8757_idx",
            old_name="asset_proje_organiz_efbe85_idx",
        ),
        migrations.RenameIndex(
            model_name="assetproject",
            new_name="asset_proje_organiz_00d9f2_idx",
            old_name="asset_proje_organiz_bae58e_idx",
        ),
        migrations.RenameIndex(
            model_name="assetproject",
            new_name="asset_proje_organiz_691330_idx",
            old_name="asset_proje_organiz_12d95f_idx",
        ),
        migrations.RenameIndex(
            model_name="assetproject",
            new_name="asset_proje_organiz_a1a695_idx",
            old_name="asset_proje_organiz_02f7e5_idx",
        ),
        migrations.RenameIndex(
            model_name="assetproject",
            new_name="asset_proje_organiz_4d8284_idx",
            old_name="asset_proje_organiz_9409aa_idx",
        ),
        migrations.RenameIndex(
            model_name="assetproject",
            new_name="asset_proje_organiz_0c160a_idx",
            old_name="asset_proje_organiz_e73b7b_idx",
        ),
        migrations.RenameIndex(
            model_name="projectasset",
            new_name="project_ass_organiz_d07568_idx",
            old_name="project_asse_organiz_5ff95a_idx",
        ),
        migrations.RenameIndex(
            model_name="projectasset",
            new_name="project_ass_organiz_a58598_idx",
            old_name="project_asse_organiz_a1d9c8_idx",
        ),
        migrations.RenameIndex(
            model_name="projectasset",
            new_name="project_ass_organiz_193194_idx",
            old_name="project_asse_organiz_5e0abc_idx",
        ),
        migrations.RenameIndex(
            model_name="projectasset",
            new_name="project_ass_organiz_2bfd18_idx",
            old_name="project_asse_organiz_356c73_idx",
        ),
        migrations.RenameIndex(
            model_name="projectasset",
            new_name="project_ass_organiz_bd93c7_idx",
            old_name="project_asse_organiz_6036b6_idx",
        ),
        migrations.RenameIndex(
            model_name="projectmember",
            new_name="project_mem_organiz_2adf65_idx",
            old_name="project_memb_organiz_e5e996_idx",
        ),
        migrations.RenameIndex(
            model_name="projectmember",
            new_name="project_mem_organiz_f68e56_idx",
            old_name="project_memb_organiz_d292ef_idx",
        ),
        migrations.RenameIndex(
            model_name="projectmember",
            new_name="project_mem_organiz_8e2125_idx",
            old_name="project_memb_organiz_25374c_idx",
        ),
        migrations.RenameIndex(
            model_name="projectmember",
            new_name="project_mem_organiz_0f34eb_idx",
            old_name="project_memb_organiz_8082ca_idx",
        ),
    ]
