# Generated by Django 5.0.1 on 2026-01-19 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_delete_department_department_userdepartment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="Unique workflow code identifier",
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Workflow Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Human-readable workflow name",
                        max_length=200,
                        verbose_name="Workflow Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_comment="Detailed description of the workflow",
                        verbose_name="Description",
                    ),
                ),
                (
                    "business_object_code",
                    models.CharField(
                        db_comment="Associated business object (e.g., asset_pickup, asset_transfer)",
                        db_index=True,
                        max_length=50,
                        verbose_name="Business Object Code",
                    ),
                ),
                (
                    "graph_data",
                    models.JSONField(
                        blank=True,
                        db_comment="Complete workflow graph data in LogicFlow format (nodes, edges)",
                        default=dict,
                        verbose_name="Graph Data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_comment="Workflow status: draft, published, archived, deprecated",
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        db_comment="Workflow version number, auto-incremented on publish",
                        default=1,
                        verbose_name="Version",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Whether this workflow definition is active for use",
                        default=True,
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when workflow was first published",
                        null=True,
                        verbose_name="Published At",
                    ),
                ),
                (
                    "form_permissions",
                    models.JSONField(
                        blank=True,
                        db_comment="Field-level permissions for each workflow node",
                        default=dict,
                        verbose_name="Form Permissions",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_comment="Workflow category for grouping and filtering",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        db_comment="Tags for workflow classification and search",
                        default=list,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who published this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Published By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Definition",
                "verbose_name_plural": "Workflow Definitions",
                "db_table": "workflow_definitions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="Unique template code identifier",
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Template Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Human-readable template name",
                        max_length=200,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_comment="Detailed description of the template",
                        verbose_name="Description",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("system", "System Template"),
                            ("custom", "Custom Template"),
                            ("user_created", "User Created"),
                        ],
                        db_comment="Type of template: system, custom, or user_created",
                        default="custom",
                        max_length=20,
                        verbose_name="Template Type",
                    ),
                ),
                (
                    "business_object_code",
                    models.CharField(
                        db_comment="Associated business object (e.g., asset_pickup, asset_transfer)",
                        db_index=True,
                        max_length=50,
                        verbose_name="Business Object Code",
                    ),
                ),
                (
                    "graph_data",
                    models.JSONField(
                        blank=True,
                        db_comment="Complete workflow graph data in LogicFlow format",
                        default=dict,
                        verbose_name="Graph Data",
                    ),
                ),
                (
                    "form_permissions",
                    models.JSONField(
                        blank=True,
                        db_comment="Default field permissions for workflow nodes",
                        default=dict,
                        verbose_name="Form Permissions",
                    ),
                ),
                (
                    "preview_image",
                    models.TextField(
                        blank=True,
                        db_comment="Base64 or URL of workflow preview image",
                        verbose_name="Preview Image",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_comment="Template category for grouping",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        db_comment="Tags for template classification",
                        default=list,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        db_comment="Number of times this template has been used",
                        default=0,
                        verbose_name="Usage Count",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_comment="Whether this template is featured/promoted",
                        default=False,
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_comment="Whether this template is available to all organizations",
                        default=False,
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_comment="Display order in template list",
                        default=0,
                        verbose_name="Sort Order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Template",
                "verbose_name_plural": "Workflow Templates",
                "db_table": "workflow_templates",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowOperationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("restore", "Restore"),
                            ("publish", "Publish"),
                            ("unpublish", "Unpublish"),
                            ("duplicate", "Duplicate/Clone"),
                            ("import", "Import"),
                            ("export", "Export"),
                            ("validate", "Validate"),
                            ("activate", "Activate"),
                            ("deactivate", "Deactivate"),
                        ],
                        db_comment="Type of operation performed",
                        max_length=20,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("workflow_definition", "Workflow Definition"),
                            ("workflow_template", "Workflow Template"),
                            ("workflow_instance", "Workflow Instance"),
                        ],
                        db_comment="Type of object the operation was performed on",
                        max_length=50,
                        verbose_name="Target Type",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True,
                        db_comment="Name of the target object (for reference)",
                        max_length=200,
                        verbose_name="Target Name",
                    ),
                ),
                (
                    "target_code",
                    models.CharField(
                        blank=True,
                        db_comment="Code of the target object (for reference)",
                        max_length=50,
                        verbose_name="Target Code",
                    ),
                ),
                (
                    "operation_details",
                    models.JSONField(
                        blank=True,
                        db_comment="Details about the operation (changes made, parameters, etc.)",
                        default=dict,
                        verbose_name="Operation Details",
                    ),
                ),
                (
                    "previous_state",
                    models.JSONField(
                        blank=True,
                        db_comment="State of the object before the operation",
                        default=dict,
                        verbose_name="Previous State",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("partial", "Partial Success"),
                        ],
                        db_comment="Result of the operation",
                        default="success",
                        max_length=20,
                        verbose_name="Result",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        db_comment="Error details if operation failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_comment="IP address from which the request originated",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        db_comment="User agent string of the request",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "request_metadata",
                    models.JSONField(
                        blank=True,
                        db_comment="Additional request metadata",
                        default=dict,
                        verbose_name="Request Metadata",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who performed this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "workflow_definition",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Workflow definition affected by this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to="workflows.workflowdefinition",
                        verbose_name="Workflow Definition",
                    ),
                ),
                (
                    "workflow_template",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Workflow template affected by this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to="workflows.workflowtemplate",
                        verbose_name="Workflow Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Operation Log",
                "verbose_name_plural": "Workflow Operation Logs",
                "db_table": "workflow_operation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowdefinition",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                db_comment="Template this workflow was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instantiated_workflows",
                to="workflows.workflowtemplate",
                verbose_name="Source Template",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(fields=["code"], name="workflow_te_code_4f1588_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["business_object_code"], name="workflow_te_busines_5e7222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["template_type"], name="workflow_te_templat_dccf0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["category"], name="workflow_te_categor_87ecf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["is_featured", "is_public"],
                name="workflow_te_is_feat_d736e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["-created_at"], name="workflow_te_created_140c15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="workflow_op_actor_i_c50b6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["operation_type", "-created_at"],
                name="workflow_op_operati_f4f972_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["target_type", "-created_at"],
                name="workflow_op_target__c67314_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["result", "-created_at"], name="workflow_op_result_7ff471_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["workflow_definition", "-created_at"],
                name="workflow_op_workflo_1f82a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["workflow_template", "-created_at"],
                name="workflow_op_workflo_fbb089_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["-created_at"], name="workflow_op_created_17486d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdefinition",
            index=models.Index(fields=["code"], name="workflow_de_code_6e85ed_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowdefinition",
            index=models.Index(
                fields=["business_object_code"], name="workflow_de_busines_864f7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdefinition",
            index=models.Index(
                fields=["status", "is_active"], name="workflow_de_status_0fa94c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdefinition",
            index=models.Index(
                fields=["category"], name="workflow_de_categor_4adced_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdefinition",
            index=models.Index(
                fields=["-created_at"], name="workflow_de_created_a53f20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdefinition",
            index=models.Index(
                fields=["organization", "business_object_code", "is_active"],
                name="workflow_de_organiz_d4719a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowdefinition",
            constraint=models.CheckConstraint(
                check=models.Q(("version__gte", 1)),
                name="workflow_definition_version_gte_1",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowdefinition",
            unique_together={("code", "organization")},
        ),
    ]
