# Generated by Django 5.0.1 on 2026-01-19 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_delete_department_department_userdepartment_and_more"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowoperationlog",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("restore", "Restore"),
                    ("publish", "Publish"),
                    ("unpublish", "Unpublish"),
                    ("duplicate", "Duplicate/Clone"),
                    ("import", "Import"),
                    ("export", "Export"),
                    ("validate", "Validate"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("start", "Start"),
                    ("complete", "Complete"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("return", "Return"),
                    ("delegate", "Delegate"),
                    ("cancel", "Cancel"),
                    ("terminate", "Terminate"),
                    ("withdraw", "Withdraw"),
                ],
                db_comment="Type of operation performed",
                max_length=20,
                verbose_name="Operation Type",
            ),
        ),
        migrations.AlterField(
            model_name="workflowoperationlog",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("workflow_definition", "Workflow Definition"),
                    ("workflow_template", "Workflow Template"),
                    ("workflow_instance", "Workflow Instance"),
                    ("workflow_task", "Workflow Task"),
                ],
                db_comment="Type of object the operation was performed on",
                max_length=50,
                verbose_name="Target Type",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "instance_no",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this instance (e.g., WI-20240115-0001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Instance No",
                    ),
                ),
                (
                    "business_object_code",
                    models.CharField(
                        db_index=True,
                        help_text="Code of the business object type (e.g., asset_pickup, asset_return)",
                        max_length=50,
                        verbose_name="Business Object Code",
                    ),
                ),
                (
                    "business_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the business data being processed",
                        max_length=100,
                        verbose_name="Business ID",
                    ),
                ),
                (
                    "business_no",
                    models.CharField(
                        blank=True,
                        help_text="Business document number (e.g., LY-2024-001)",
                        max_length=100,
                        null=True,
                        verbose_name="Business No",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the workflow instance",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_node_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the current node in the workflow graph",
                        max_length=50,
                        null=True,
                        verbose_name="Current Node ID",
                    ),
                ),
                (
                    "current_node_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the current node for display",
                        max_length=200,
                        null=True,
                        verbose_name="Current Node Name",
                    ),
                ),
                (
                    "total_tasks",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of tasks in this workflow",
                        verbose_name="Total Tasks",
                    ),
                ),
                (
                    "completed_tasks",
                    models.IntegerField(
                        default=0,
                        help_text="Number of completed tasks",
                        verbose_name="Completed Tasks",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the workflow was started",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the workflow was completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "terminated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the workflow was terminated",
                        null=True,
                        verbose_name="Terminated At",
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for workflow termination",
                        null=True,
                        verbose_name="Termination Reason",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Workflow variables and form data",
                        verbose_name="Variables",
                    ),
                ),
                (
                    "graph_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of workflow graph at instance creation",
                        verbose_name="Graph Snapshot",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title for this instance",
                        max_length=200,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description or notes for this instance",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level of this workflow instance",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Estimated hours to complete this workflow",
                        max_digits=5,
                        null=True,
                        verbose_name="Estimated Hours",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        help_text="The workflow definition this instance is based on",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflows.workflowdefinition",
                        verbose_name="Workflow Definition",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        help_text="User who initiated this workflow",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_instances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "terminated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who terminated the workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminated_instances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Terminated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Instance",
                "verbose_name_plural": "Workflow Instances",
                "db_table": "workflow_instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowoperationlog",
            name="workflow_instance",
            field=models.ForeignKey(
                blank=True,
                db_comment="Workflow instance affected by this operation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="workflows.workflowinstance",
                verbose_name="Workflow Instance",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the node in the workflow graph",
                        max_length=50,
                        verbose_name="Node ID",
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        help_text="Display name of the node",
                        max_length=200,
                        verbose_name="Node Name",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("approval", "Approval"),
                            ("condition", "Condition"),
                            ("cc", "Carbon Copy"),
                            ("notify", "Notify"),
                            ("parallel", "Parallel Gateway"),
                            ("end", "End"),
                        ],
                        default="approval",
                        help_text="Type of the workflow node",
                        max_length=20,
                        verbose_name="Node Type",
                    ),
                ),
                (
                    "approve_type",
                    models.CharField(
                        choices=[
                            ("or", "Or Sign - Any One"),
                            ("and", "Countersign - All Must"),
                            ("sequence", "Sequential"),
                        ],
                        default="or",
                        help_text="How multiple approvers interact (or/and/sequence)",
                        max_length=20,
                        verbose_name="Approve Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                            ("terminated", "Terminated"),
                            ("delegated", "Delegated"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0,
                        help_text="Order in sequence (0 for non-sequential)",
                        verbose_name="Sequence",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for task completion",
                        null=True,
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was cancelled",
                        null=True,
                        verbose_name="Cancelled At",
                    ),
                ),
                (
                    "terminated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was terminated",
                        null=True,
                        verbose_name="Terminated At",
                    ),
                ),
                (
                    "delegated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was delegated",
                        null=True,
                        verbose_name="Delegated At",
                    ),
                ),
                (
                    "delegation_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for task delegation",
                        null=True,
                        verbose_name="Delegation Reason",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Priority level of this task",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "node_properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of node properties at task creation",
                        verbose_name="Node Properties",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        help_text="User assigned to this task",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignee",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed the task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "delegated_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who delegated this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_by_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegated From",
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User this task was delegated to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegated To",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        help_text="The workflow instance this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workflows.workflowinstance",
                        verbose_name="Workflow Instance",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Task",
                "verbose_name_plural": "Workflow Tasks",
                "db_table": "workflow_tasks",
                "ordering": ["instance", "sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("return", "Return"),
                            ("delegate", "Delegate"),
                            ("withdraw", "Withdraw"),
                        ],
                        db_index=True,
                        help_text="The approval action taken",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Comment or reason for this approval action",
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "attachment",
                    models.CharField(
                        blank=True,
                        help_text="Optional attachment URL for this approval",
                        max_length=500,
                        null=True,
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the approval was made",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/user agent of the approval device",
                        max_length=500,
                        null=True,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        help_text="Task status before this action",
                        max_length=20,
                        null=True,
                        verbose_name="Previous Status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        help_text="Task status after this action",
                        max_length=20,
                        null=True,
                        verbose_name="New Status",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken to process the action in milliseconds",
                        null=True,
                        verbose_name="Processing Time (ms)",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        help_text="User who performed this approval action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who received the delegation (for delegate actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_workflow_delegations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Delegated To",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="The task this approval belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="workflows.workflowtask",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Approval",
                "verbose_name_plural": "Workflow Approvals",
                "db_table": "workflow_approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workflowoperationlog",
            name="workflow_task",
            field=models.ForeignKey(
                blank=True,
                db_comment="Workflow task affected by this operation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="workflows.workflowtask",
                verbose_name="Workflow Task",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["workflow_instance", "-created_at"],
                name="workflow_op_workflo_25375d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoperationlog",
            index=models.Index(
                fields=["workflow_task", "-created_at"],
                name="workflow_op_workflo_4fa036_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["instance_no"], name="workflow_in_instanc_620520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(fields=["status"], name="workflow_in_status_a4291a_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["business_object_code", "business_id"],
                name="workflow_in_busines_c836d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["initiator"], name="workflow_in_initiat_f9fa28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["definition"], name="workflow_in_definit_78cf96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["-created_at"], name="workflow_in_created_37ea31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["started_at"], name="workflow_in_started_11cbcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["completed_at"], name="workflow_in_complet_1adaa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["instance", "status"], name="workflow_ta_instanc_fb4301_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["assignee", "status"], name="workflow_ta_assigne_e31f1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(fields=["status"], name="workflow_ta_status_9b2394_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["due_date"], name="workflow_ta_due_dat_97fce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["node_id"], name="workflow_ta_node_id_799e99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["-created_at"], name="workflow_ta_created_22d9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapproval",
            index=models.Index(
                fields=["task", "-created_at"], name="workflow_ap_task_id_415f24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapproval",
            index=models.Index(
                fields=["approver", "-created_at"],
                name="workflow_ap_approve_5f40d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapproval",
            index=models.Index(fields=["action"], name="workflow_ap_action_61cadf_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowapproval",
            index=models.Index(
                fields=["-created_at"], name="workflow_ap_created_741077_idx"
            ),
        ),
    ]
