# Generated by Django 5.0.1 on 2026-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_add_base_model_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowoperationlog",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("restore", "Restore"),
                    ("publish", "Publish"),
                    ("unpublish", "Unpublish"),
                    ("duplicate", "Duplicate/Clone"),
                    ("import", "Import"),
                    ("export", "Export"),
                    ("validate", "Validate"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("start", "Start"),
                    ("complete", "Complete"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("return", "Return"),
                    ("delegate", "Delegate"),
                    ("cancel", "Cancel"),
                    ("terminate", "Terminate"),
                    ("withdraw", "Withdraw"),
                    ("status_change", "Status Change"),
                ],
                db_comment="Type of operation performed",
                max_length=20,
                verbose_name="Operation Type",
            ),
        ),
    ]
