# Generated by Django 5.0.1 on 2026-01-18 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('code', models.CharField(db_comment='Business object code (unique identifier)', db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_comment='Business object name', max_length=100)),
                ('name_en', models.CharField(blank=True, db_comment='English name', max_length=100)),
                ('description', models.TextField(blank=True, db_comment='Description')),
                ('enable_workflow', models.BooleanField(db_comment='Enable workflow/approval process', default=False)),
                ('enable_version', models.BooleanField(db_comment='Enable version control', default=True)),
                ('enable_soft_delete', models.BooleanField(db_comment='Enable soft delete for dynamic data', default=True)),
                ('table_name', models.CharField(blank=True, db_comment='Custom table name (default: dynamic_data_{code})', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Business Object',
                'verbose_name_plural': 'Business Objects',
                'db_table': 'business_objects',
            },
        ),
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('data_no', models.CharField(db_comment='Auto-generated data number (e.g., ASSET202401010001)', db_index=True, max_length=50)),
                ('status', models.CharField(db_comment='Data status (draft, submitted, approved, etc.)', db_index=True, default='draft', max_length=50)),
                ('dynamic_fields', models.JSONField(db_comment='Dynamic field data stored as PostgreSQL JSONB', default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='Submission timestamp', null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_comment='Approval timestamp', null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_comment='User who approved this data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dynamic_data', to=settings.AUTH_USER_MODEL)),
                ('business_object', models.ForeignKey(db_comment='Business object this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_data_set', to='system.businessobject')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Dynamic Data',
                'verbose_name_plural': 'Dynamic Data',
                'db_table': 'dynamic_data',
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('code', models.CharField(db_comment='Field code (unique within business object)', max_length=50)),
                ('name', models.CharField(db_comment='Field display name', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('currency', 'Currency'), ('percent', 'Percentage'), ('date', 'Date'), ('datetime', 'Date Time'), ('boolean', 'Boolean'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('user', 'User'), ('department', 'Department'), ('reference', 'Reference'), ('asset', 'Asset'), ('formula', 'Formula'), ('sub_table', 'Sub Table'), ('file', 'File'), ('image', 'Image'), ('rich_text', 'Rich Text'), ('qr_code', 'QR Code'), ('barcode', 'Barcode'), ('location', 'Location')], db_comment='Field type', default='text', max_length=20)),
                ('is_required', models.BooleanField(db_comment='Is field required', default=False)),
                ('is_unique', models.BooleanField(db_comment='Is field value unique', default=False)),
                ('is_readonly', models.BooleanField(db_comment='Is field read-only', default=False)),
                ('is_system', models.BooleanField(db_comment='Is system field (cannot be deleted)', default=False)),
                ('is_searchable', models.BooleanField(db_comment='Is field searchable in global search', default=False)),
                ('show_in_list', models.BooleanField(db_comment='Show in list view', default=False)),
                ('show_in_detail', models.BooleanField(db_comment='Show in detail view', default=True)),
                ('show_in_filter', models.BooleanField(db_comment='Show as filter option', default=False)),
                ('sort_order', models.IntegerField(db_comment='Display order', default=0)),
                ('column_width', models.IntegerField(blank=True, db_comment='Column width in pixels', null=True)),
                ('min_column_width', models.IntegerField(blank=True, db_comment='Minimum column width', null=True)),
                ('fixed', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], db_comment='Fixed column position', max_length=10)),
                ('sortable', models.BooleanField(db_comment='Is column sortable', default=True)),
                ('default_value', models.TextField(blank=True, db_comment='Default value (supports variables: {current_user}, {today}, {now})')),
                ('options', models.JSONField(blank=True, db_comment='Options for select fields: [{"value": "v1", "label": "Option1"}]', default=list)),
                ('reference_object', models.CharField(blank=True, db_comment='Referenced business object code (for reference type)', max_length=50)),
                ('reference_display_field', models.CharField(blank=True, db_comment='Display field for reference', default='name', max_length=50)),
                ('decimal_places', models.IntegerField(db_comment='Decimal places for number/currency fields', default=0)),
                ('min_value', models.DecimalField(blank=True, db_comment='Minimum value', decimal_places=4, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, db_comment='Maximum value', decimal_places=4, max_digits=20, null=True)),
                ('max_length', models.IntegerField(db_comment='Maximum length for text fields', default=255)),
                ('placeholder', models.CharField(blank=True, db_comment='Placeholder text', max_length=200)),
                ('regex_pattern', models.CharField(blank=True, db_comment='Regex validation pattern', max_length=500)),
                ('formula', models.TextField(blank=True, db_comment='Formula expression (e.g., {field1} + {field2})')),
                ('sub_table_fields', models.JSONField(blank=True, db_comment='Sub-table field definitions', default=list)),
                ('business_object', models.ForeignKey(db_comment='Business object this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='system.businessobject')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Field Definition',
                'verbose_name_plural': 'Field Definitions',
                'db_table': 'field_definitions',
            },
        ),
        migrations.CreateModel(
            name='DynamicSubTableData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('row_order', models.IntegerField(db_comment='Row display order', default=0)),
                ('row_data', models.JSONField(db_comment='Row data stored as PostgreSQL JSONB', default=dict)),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('parent_data', models.ForeignKey(db_comment='Parent dynamic data record', on_delete=django.db.models.deletion.CASCADE, related_name='sub_table_rows', to='system.dynamicdata')),
                ('field_definition', models.ForeignKey(db_comment='Field definition (sub-table type)', on_delete=django.db.models.deletion.CASCADE, related_name='sub_table_data', to='system.fielddefinition')),
            ],
            options={
                'verbose_name': 'Dynamic Sub-Table Data',
                'verbose_name_plural': 'Dynamic Sub-Table Data',
                'db_table': 'dynamic_sub_table_data',
            },
        ),
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('layout_code', models.CharField(db_comment='Layout code (unique within business object)', max_length=50)),
                ('layout_name', models.CharField(db_comment='Layout display name', max_length=100)),
                ('layout_type', models.CharField(choices=[('form', 'Form'), ('list', 'List'), ('detail', 'Detail'), ('search', 'Search')], db_comment='Layout type', default='form', max_length=20)),
                ('layout_config', models.JSONField(db_comment='JSON layout configuration', default=dict)),
                ('is_default', models.BooleanField(db_comment='Is this the default layout for its type', default=False)),
                ('is_active', models.BooleanField(db_comment='Is layout active', default=True)),
                ('business_object', models.ForeignKey(db_comment='Business object this layout belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='page_layouts', to='system.businessobject')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Page Layout',
                'verbose_name_plural': 'Page Layouts',
                'db_table': 'page_layouts',
            },
        ),
        migrations.AddField(
            model_name='businessobject',
            name='default_form_layout',
            field=models.ForeignKey(blank=True, db_comment='Default form layout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_form', to='system.pagelayout'),
        ),
        migrations.AddField(
            model_name='businessobject',
            name='default_list_layout',
            field=models.ForeignKey(blank=True, db_comment='Default list layout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_list', to='system.pagelayout'),
        ),
        migrations.AddIndex(
            model_name='dynamicdata',
            index=models.Index(fields=['organization', 'business_object'], name='dynamic_dat_organiz_a43f29_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdata',
            index=models.Index(fields=['organization', 'business_object', 'created_by'], name='dynamic_dat_organiz_ad5085_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdata',
            index=models.Index(fields=['organization', 'business_object', 'status'], name='dynamic_dat_organiz_86cd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdata',
            index=models.Index(fields=['data_no'], name='dynamic_dat_data_no_7ddea2_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdata',
            index=models.Index(fields=['status'], name='dynamic_dat_status_61b31b_idx'),
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['organization', 'business_object', 'code'], name='field_defin_organiz_afde48_idx'),
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['organization', 'field_type'], name='field_defin_organiz_afb493_idx'),
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['sort_order'], name='field_defin_sort_or_9987e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together={('organization', 'business_object', 'code')},
        ),
        migrations.AddIndex(
            model_name='dynamicsubtabledata',
            index=models.Index(fields=['organization', 'parent_data', 'field_definition'], name='dynamic_sub_organiz_3b731c_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsubtabledata',
            index=models.Index(fields=['parent_data', 'row_order'], name='dynamic_sub_parent__443b80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicsubtabledata',
            unique_together={('parent_data', 'field_definition', 'row_order')},
        ),
        migrations.AddIndex(
            model_name='pagelayout',
            index=models.Index(fields=['organization', 'business_object', 'layout_code'], name='page_layout_organiz_d92c99_idx'),
        ),
        migrations.AddIndex(
            model_name='pagelayout',
            index=models.Index(fields=['organization', 'business_object', 'layout_type'], name='page_layout_organiz_55d5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='pagelayout',
            index=models.Index(fields=['is_active'], name='page_layout_is_acti_57bd8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagelayout',
            unique_together={('organization', 'business_object', 'layout_code')},
        ),
        migrations.AddIndex(
            model_name='businessobject',
            index=models.Index(fields=['code'], name='business_ob_code_ff4b92_idx'),
        ),
        migrations.AddIndex(
            model_name='businessobject',
            index=models.Index(fields=['organization', 'code'], name='business_ob_organiz_b5a1e8_idx'),
        ),
    ]
