# Generated by Django 5.2.10 on 2026-01-20 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        ('system', '0002_hybrid_architecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modelfielddefinition',
            new_name='model_field_organiz_2e4dbc_idx',
            old_name='org_obj_field_idx',
        ),
        migrations.RenameIndex(
            model_name='modelfielddefinition',
            new_name='model_field_organiz_2fb267_idx',
            old_name='org_obj_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='modelfielddefinition',
            new_name='model_field_field_t_56df70_idx',
            old_name='field_type_idx',
        ),
        migrations.AddField(
            model_name='businessobject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='businessobject',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='dynamicdata',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='dynamicdata',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='dynamicsubtabledata',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='dynamicsubtabledata',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='modelfielddefinition',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='modelfielddefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='business_object',
            field=models.ForeignKey(db_comment='Business object (hardcoded) this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='model_fields', to='system.businessobject'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='custom_fields',
            field=models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='decimal_places',
            field=models.IntegerField(blank=True, db_comment='Decimal places for number fields', null=True),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='django_field_type',
            field=models.CharField(db_comment='Original Django field type (e.g., CharField)', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='field_type',
            field=models.CharField(db_comment='Mapped field type (see DJANGO_FIELD_TYPE_MAP)', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='is_deleted',
            field=models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='is_readonly',
            field=models.BooleanField(db_comment='Is field read-only (not editable)', default=False),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='is_required',
            field=models.BooleanField(db_comment='Is field required (not null)', default=False),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='max_digits',
            field=models.IntegerField(blank=True, db_comment='Maximum digits for decimal fields', null=True),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='max_length',
            field=models.IntegerField(blank=True, db_comment='Maximum length for text fields', null=True),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='organization',
            field=models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='reference_model_path',
            field=models.CharField(blank=True, db_comment='Referenced model path for ForeignKey fields', max_length=200),
        ),
        migrations.AlterField(
            model_name='modelfielddefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterUniqueTogether(
            name='modelfielddefinition',
            unique_together={('organization', 'business_object', 'field_name')},
        ),
    ]
