# Generated by Django 5.2.10 on 2026-01-26 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        ('system', '0007_update_sequence_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('version', models.CharField(db_comment='Version number', max_length=20)),
                ('config_snapshot', models.JSONField(db_comment='Configuration snapshot at this version')),
                ('action', models.CharField(choices=[('publish', 'Publish'), ('update', 'Update'), ('rollback', 'Rollback')], db_comment='Action that created this history entry', default='publish', max_length=20)),
                ('change_summary', models.TextField(blank=True, db_comment='Summary of changes in this version')),
            ],
            options={
                'verbose_name': 'Layout History',
                'verbose_name_plural': 'Layout Histories',
                'db_table': 'layout_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='reference_filters',
            field=models.JSONField(blank=True, db_comment='Filters for reference fields: {"department": "current_user.department"}', default=dict),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='description',
            field=models.TextField(blank=True, db_comment='Layout description'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='parent_version',
            field=models.CharField(blank=True, db_comment='Parent version for version tracking', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='published_at',
            field=models.DateTimeField(blank=True, db_comment='Publication timestamp', null=True),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='published_by',
            field=models.ForeignKey(blank=True, db_comment='User who published this layout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_layouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_comment='Layout status', default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='version',
            field=models.CharField(db_comment='Version number', default='1.0.0', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pagelayout',
            index=models.Index(fields=['organization', 'business_object', 'layout_type', 'is_default'], name='page_layout_organiz_7aa794_idx'),
        ),
        migrations.AddIndex(
            model_name='pagelayout',
            index=models.Index(fields=['status'], name='page_layout_status_a98696_idx'),
        ),
        migrations.AddField(
            model_name='layouthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='layouthistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='layouthistory',
            name='layout',
            field=models.ForeignKey(db_comment='Associated layout', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='system.pagelayout'),
        ),
        migrations.AddField(
            model_name='layouthistory',
            name='organization',
            field=models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='layouthistory',
            name='published_by',
            field=models.ForeignKey(blank=True, db_comment='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layouthistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='layouthistory',
            index=models.Index(fields=['layout', 'version'], name='layout_hist_layout__a97b09_idx'),
        ),
        migrations.AddIndex(
            model_name='layouthistory',
            index=models.Index(fields=['layout', '-created_at'], name='layout_hist_layout__4f9828_idx'),
        ),
    ]
