# Generated by Django 5.2.10 on 2026-01-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_layouthistory_fielddefinition_reference_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessobject',
            name='actions',
            field=models.JSONField(blank=True, db_comment='Custom action definitions (e.g., buttons, triggers)', default=list),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='validation_rules',
            field=models.JSONField(blank=True, db_comment='Advanced validation rules (JSON logic)', default=list),
        ),
    ]
