# Generated by Django 5.2.10 on 2026-01-27 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        ('system', '0009_businessobject_actions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('name', models.CharField(db_comment='Configuration name (e.g., form_tabs, detail_tabs)', max_length=50)),
                ('position', models.CharField(choices=[('top', 'Top'), ('left', 'Left'), ('right', 'Right'), ('bottom', 'Bottom')], db_comment='Tab position', default='top', max_length=10)),
                ('type_style', models.CharField(choices=[('', 'Default'), ('card', 'Card'), ('border-card', 'Border Card')], db_comment='Tab style type', default='', max_length=20)),
                ('stretch', models.BooleanField(db_comment='Stretch tabs to fill width', default=False)),
                ('lazy', models.BooleanField(db_comment='Lazy load tab content', default=True)),
                ('animated', models.BooleanField(db_comment='Animated tab transitions', default=True)),
                ('addable', models.BooleanField(db_comment='Allow adding new tabs', default=False)),
                ('draggable', models.BooleanField(db_comment='Allow dragging to reorder tabs', default=False)),
                ('tabs_config', models.JSONField(db_comment='Tab definitions: [{id, title, icon, closable, disabled, content, ...}]', default=list)),
                ('is_active', models.BooleanField(db_comment='Is this configuration active', db_index=True, default=True)),
                ('business_object', models.ForeignKey(db_comment='Business object this config applies to', on_delete=django.db.models.deletion.CASCADE, related_name='tab_configs', to='system.businessobject')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Tab Configuration',
                'verbose_name_plural': 'Tab Configurations',
                'db_table': 'system_tab_config',
                'indexes': [models.Index(fields=['business_object', 'name', 'is_active'], name='system_tab__busines_5b6708_idx')],
                'unique_together': {('business_object', 'name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='UserColumnPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('object_code', models.CharField(db_comment='Business object code (e.g., asset, procurement_request)', db_index=True, max_length=50)),
                ('column_config', models.JSONField(db_comment='Column configuration (JSON): {columns: [...], columnOrder: [...]}', default=dict)),
                ('config_name', models.CharField(db_comment='Configuration name (allows multiple configs per object)', default='default', max_length=50)),
                ('is_default', models.BooleanField(db_comment='Is this the default configuration for this object', default=True)),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(db_comment='User who owns this preference', on_delete=django.db.models.deletion.CASCADE, related_name='column_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Column Preference',
                'verbose_name_plural': 'User Column Preferences',
                'db_table': 'system_user_column_preference',
                'indexes': [models.Index(fields=['user', 'object_code'], name='system_user_user_id_0248b6_idx'), models.Index(fields=['user', 'object_code', 'is_default'], name='system_user_user_id_6cabe2_idx')],
                'unique_together': {('user', 'object_code', 'config_name')},
            },
        ),
    ]
