# Generated by Django 5.0.1 on 2026-01-28 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        ('system', '0013_complete_menu_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('rule_code', models.CharField(db_comment='Rule code', max_length=50)),
                ('rule_name', models.CharField(db_comment='Rule display name', max_length=100)),
                ('description', models.TextField(blank=True, db_comment='Rule description')),
                ('rule_type', models.CharField(choices=[('validation', '校验规则'), ('visibility', '显示规则'), ('computed', '计算规则'), ('trigger', '触发规则'), ('linkage', '联动规则')], db_comment='Type of rule', default='validation', max_length=20)),
                ('priority', models.IntegerField(db_comment='Execution priority (higher=first)', default=0)),
                ('is_active', models.BooleanField(db_comment='Is rule currently active', default=True)),
                ('condition', models.JSONField(blank=True, db_comment='JSON Logic condition', default=dict)),
                ('action', models.JSONField(db_comment='Action to perform', default=dict)),
                ('target_field', models.CharField(blank=True, db_comment='Target field code', max_length=50)),
                ('trigger_events', models.JSONField(blank=True, db_comment='Trigger events', default=list)),
                ('error_message', models.CharField(blank=True, db_comment='Error message', max_length=500)),
                ('error_message_en', models.CharField(blank=True, db_comment='English error message', max_length=500)),
                ('business_object', models.ForeignKey(db_comment='Business object this rule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='business_rules', to='system.businessobject')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Business Rule',
                'verbose_name_plural': 'Business Rules',
                'db_table': 'business_rules',
                'ordering': ['-priority', 'rule_type', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('target_record_id', models.UUIDField(db_comment='ID of the record being evaluated')),
                ('target_record_type', models.CharField(db_comment='Business object code', max_length=50)),
                ('trigger_event', models.CharField(db_comment='Event that triggered execution', max_length=50)),
                ('input_data', models.JSONField(db_comment='Input data for evaluation', default=dict)),
                ('condition_result', models.BooleanField(db_comment='Whether condition was true')),
                ('action_executed', models.BooleanField(db_comment='Whether action executed', default=False)),
                ('execution_result', models.JSONField(db_comment='Execution result', default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_comment='Execution timestamp')),
                ('execution_time_ms', models.IntegerField(db_comment='Execution time in ms', null=True)),
                ('has_error', models.BooleanField(db_comment='Whether an error occurred', default=False)),
                ('error_message', models.TextField(blank=True, db_comment='Error message if failed')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('rule', models.ForeignKey(db_comment='The rule that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='system.businessrule')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Rule Execution',
                'verbose_name_plural': 'Rule Executions',
                'db_table': 'rule_executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['organization', 'business_object', 'rule_type'], name='business_ru_organiz_dba076_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrule',
            index=models.Index(fields=['organization', 'business_object', 'is_active'], name='business_ru_organiz_63a614_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessrule',
            unique_together={('organization', 'business_object', 'rule_code')},
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['rule', '-executed_at'], name='rule_execut_rule_id_73b907_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleexecution',
            index=models.Index(fields=['target_record_id'], name='rule_execut_target__f4b9c3_idx'),
        ),
    ]
