# Generated by Django 5.0.1 on 2026-01-28 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        ('system', '0014_add_business_rule_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('name', models.CharField(db_comment='Package name', max_length=100)),
                ('version', models.CharField(db_comment='Semantic version (e.g., 1.0.0)', max_length=20)),
                ('description', models.TextField(blank=True, db_comment='Package description')),
                ('package_type', models.CharField(choices=[('full', '完整导出'), ('partial', '部分导出'), ('diff', '差异导出')], db_comment='Type of package', default='full', max_length=20)),
                ('included_objects', models.JSONField(db_comment='List of business object codes included', default=list)),
                ('config_data', models.JSONField(db_comment='Serialized configuration data', default=dict)),
                ('exported_at', models.DateTimeField(auto_now_add=True, db_comment='Export timestamp')),
                ('source_environment', models.CharField(blank=True, db_comment='Source environment name (dev/staging/prod)', max_length=50)),
                ('checksum', models.CharField(blank=True, db_comment='SHA256 checksum of config_data for integrity', max_length=64)),
                ('is_valid', models.BooleanField(db_comment='Whether package passed validation', default=True)),
                ('validation_errors', models.JSONField(blank=True, db_comment='Validation error messages if any', default=list)),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('exported_by', models.ForeignKey(db_comment='User who exported this package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_packages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Configuration Package',
                'verbose_name_plural': 'Configuration Packages',
                'db_table': 'config_packages',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('imported_at', models.DateTimeField(auto_now_add=True, db_comment='Import timestamp')),
                ('target_environment', models.CharField(blank=True, db_comment='Target environment name', max_length=50)),
                ('import_strategy', models.CharField(choices=[('merge', '合并'), ('replace', '替换'), ('skip', '跳过已存在')], db_comment='Import strategy used', default='merge', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('rolled_back', '已回滚')], db_comment='Import status', default='pending', max_length=20)),
                ('import_result', models.JSONField(db_comment='Import result details', default=dict)),
                ('objects_created', models.IntegerField(db_comment='Number of objects created', default=0)),
                ('objects_updated', models.IntegerField(db_comment='Number of objects updated', default=0)),
                ('objects_skipped', models.IntegerField(db_comment='Number of objects skipped', default=0)),
                ('objects_failed', models.IntegerField(db_comment='Number of objects failed', default=0)),
                ('rollback_data', models.JSONField(blank=True, db_comment='Data snapshot for rollback', default=dict, null=True)),
                ('can_rollback', models.BooleanField(db_comment='Whether this import can be rolled back', default=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, db_comment='When rollback was performed', null=True)),
                ('error_message', models.TextField(blank=True, db_comment='Error message if import failed')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('imported_by', models.ForeignKey(db_comment='User who performed the import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_imports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('package', models.ForeignKey(db_comment='The package that was imported', on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='system.configpackage')),
            ],
            options={
                'verbose_name': 'Configuration Import Log',
                'verbose_name_plural': 'Configuration Import Logs',
                'db_table': 'config_import_logs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='configpackage',
            index=models.Index(fields=['organization', 'name'], name='config_pack_organiz_441572_idx'),
        ),
        migrations.AddIndex(
            model_name='configpackage',
            index=models.Index(fields=['organization', '-exported_at'], name='config_pack_organiz_28bfaf_idx'),
        ),
        migrations.AddIndex(
            model_name='configimportlog',
            index=models.Index(fields=['package', '-imported_at'], name='config_impo_package_dd5804_idx'),
        ),
        migrations.AddIndex(
            model_name='configimportlog',
            index=models.Index(fields=['organization', '-imported_at'], name='config_impo_organiz_389baf_idx'),
        ),
        migrations.AddIndex(
            model_name='configimportlog',
            index=models.Index(fields=['status'], name='config_impo_status_0f4842_idx'),
        ),
    ]
