# Generated by Django 5.0.1 on 2026-01-29 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_add_base_model_fields"),
        ("system", "0016_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemfile",
            name="field_code",
            field=models.CharField(
                blank=True,
                db_comment="Field code in the object (e.g., contract_files)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="systemfile",
            name="height",
            field=models.IntegerField(blank=True, db_comment="Image height in pixels", null=True),
        ),
        migrations.AddField(
            model_name="systemfile",
            name="instance_id",
            field=models.UUIDField(
                blank=True, db_comment="Business object instance ID", db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="systemfile",
            name="is_compressed",
            field=models.BooleanField(db_comment="Whether file has been compressed", default=False),
        ),
        migrations.AddField(
            model_name="systemfile",
            name="object_code",
            field=models.CharField(
                blank=True,
                db_comment="Business object code (e.g., contract, asset)",
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="systemfile",
            name="original_file_id",
            field=models.UUIDField(
                blank=True, db_comment="Original file ID if this is a compressed version", null=True
            ),
        ),
        migrations.AddField(
            model_name="systemfile",
            name="width",
            field=models.IntegerField(blank=True, db_comment="Image width in pixels", null=True),
        ),
        migrations.AddIndex(
            model_name="systemfile",
            index=models.Index(
                fields=["organization", "object_code", "instance_id"],
                name="system_file_organiz_382b8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemfile",
            index=models.Index(
                fields=["organization", "object_code", "instance_id", "field_code"],
                name="system_file_organiz_c8b97c_idx",
            ),
        ),
    ]
