# Generated by Django 5.2.10 on 2026-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_systemfile_field_code_systemfile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddefinition',
            name='is_reverse_relation',
            field=models.BooleanField(db_comment='True if this field represents a reverse relation (related_name)', default=False),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='relation_display_mode',
            field=models.CharField(choices=[('inline_editable', 'Inline Editable Table'), ('inline_readonly', 'Inline Read-Only Table'), ('tab_readonly', 'Tab Read-Only Table'), ('hidden', 'Hidden')], db_comment='How to display reverse relations', default='tab_readonly', max_length=20),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='reverse_relation_field',
            field=models.CharField(blank=True, db_comment='FK field name on related model (e.g., asset)', max_length=100),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='reverse_relation_model',
            field=models.CharField(blank=True, db_comment='Path to model that owns this relation (e.g., apps.lifecycle.models.Maintenance)', max_length=200),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='show_in_form',
            field=models.BooleanField(db_comment='Show in create/edit forms', default=True),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='context_type',
            field=models.CharField(blank=True, choices=[('form_create', 'Create Form'), ('form_edit', 'Edit Form'), ('detail', 'Detail View'), ('list', 'List View'), ('search', 'Search Form')], db_comment='Specific context within layout_type (e.g., form_create vs form_edit)', max_length=20),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='diff_config',
            field=models.JSONField(db_comment='\n        Differential configuration storing only changes from default layout.\n        Structure:\n        {\n            "fieldOrder": ["code", "name", "category"],  // Custom sort order\n            "sections": [\n                {\n                    "id": "section_basic",\n                    "fields": [\n                        {\n                            "fieldCode": "code",\n                            "span": 24,           // Custom column span\n                            "readonly": true,     // Override field definition\n                            "visible": false,     // Hide field\n                            "required": true      // Override required\n                        }\n                    ]\n                }\n            ]\n        }\n        ', default=dict),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='priority',
            field=models.CharField(choices=[('user', 'User Level'), ('role', 'Role Level'), ('org', 'Organization Level'), ('global', 'Global Level'), ('default', 'Default Layout')], db_comment='Layout priority level (user > role > org > global > default)', default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='systemfile',
            name='watermarked_path',
            field=models.CharField(blank=True, db_comment='Watermarked image path (for images)', max_length=500),
        ),
    ]
