# Generated by Django 5.2.10 on 2026-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_add_system_management_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='mode',
            field=models.CharField(blank=True, choices=[('edit', 'Edit'), ('readonly', 'Readonly'), ('search', 'Search')], db_comment='Layout display mode (edit/readonly/search)', default='edit', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagelayout',
            name='layout_type',
            field=models.CharField(choices=[('form', 'Form'), ('list', 'List'), ('detail', 'Detail'), ('search', 'Search')], db_comment='Layout type (deprecated: use mode instead)', default='form', max_length=20),
        ),
    ]
