# Generated by Django 5.0.1 on 2026-02-09 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0005_add_base_model_fields"),
        ("system", "0020_add_layout_mode_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="Language code (BCP 47 standard, e.g., zh-CN, en-US)",
                        db_index=True,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Language display name (e.g., Chinese (Simplified))",
                        max_length=50,
                    ),
                ),
                (
                    "native_name",
                    models.CharField(db_comment="Native language name (e.g., 简体中文)", max_length=50),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_comment="Is this the default language", db_index=True, default=False
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Is this language active", db_index=True, default=True
                    ),
                ),
                ("sort_order", models.IntegerField(db_comment="Display order", default=0)),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True, db_comment="Flag emoji (e.g., 🇨🇳, 🇺🇸)", max_length=10
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        db_comment="Locale code for frontend (e.g., zhCN, enUS)",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who soft deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "languages",
                "ordering": ["sort_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_default", "is_active"], name="languages_is_defa_ce4aae_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        db_comment="Translation namespace (e.g., asset, common, dictionary)",
                        db_index=True,
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        db_comment="Translation key (e.g., status.idle, button.save)",
                        db_index=True,
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        blank=True,
                        db_comment="Object ID for GenericForeignKey (UUID to match BaseModel)",
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        db_comment="Field name being translated (e.g., name, description)",
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_comment="Target language code (e.g., en-US, ja-JP)",
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(db_comment="Translated text")),
                (
                    "context",
                    models.CharField(
                        blank=True, db_comment="Context for disambiguation", max_length=200
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        db_comment="Translation type: label, message, enum, object_field",
                        default="label",
                        max_length=20,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_comment="Is this a system translation (not editable by users)",
                        default=False,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Content type for GenericForeignKey",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who soft deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
                "db_table": "translations",
                "indexes": [
                    models.Index(
                        fields=["namespace", "key", "language_code"],
                        name="translation_namespa_c852dc_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "language_code"],
                        name="translation_content_a53afb_idx",
                    ),
                    models.Index(
                        fields=["language_code", "type"], name="translation_languag_9d6745_idx"
                    ),
                    models.Index(fields=["is_system"], name="translation_is_syst_527ef6_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("key__gt", ""), ("namespace__gt", "")),
                fields=("namespace", "key", "language_code"),
                name="unique_namespace_key_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_type__isnull", False), ("object_id__isnull", False)),
                fields=("content_type", "object_id", "field_name", "language_code"),
                name="unique_gfk_field_lang",
            ),
        ),
    ]
