# Generated by Codex on 2026-02-25

from django.db import migrations


TARGET_OBJECTS = [
    {
        'code': 'FinanceVoucher',
        'name': '财务凭证',
        'django_model_path': 'apps.finance.models.FinanceVoucher',
    },
    {
        'code': 'VoucherTemplate',
        'name': '凭证模板',
        'django_model_path': 'apps.finance.models.VoucherTemplate',
    },
    {
        'code': 'DepreciationConfig',
        'name': '折旧配置',
        'django_model_path': 'apps.depreciation.models.DepreciationConfig',
    },
    {
        'code': 'DepreciationRecord',
        'name': '折旧记录',
        'django_model_path': 'apps.depreciation.models.DepreciationRecord',
    },
    {
        'code': 'DepreciationRun',
        'name': '折旧运行',
        'django_model_path': 'apps.depreciation.models.DepreciationRun',
    },
    {
        'code': 'ITAsset',
        'name': 'IT设备',
        'django_model_path': 'apps.it_assets.models.ITAssetInfo',
    },
    {
        'code': 'ITSoftware',
        'name': 'IT软件目录',
        'django_model_path': 'apps.it_assets.models.Software',
    },
    {
        'code': 'ITSoftwareLicense',
        'name': 'IT软件许可',
        'django_model_path': 'apps.it_assets.models.SoftwareLicense',
    },
    {
        'code': 'ITLicenseAllocation',
        'name': 'IT许可证分配',
        'django_model_path': 'apps.it_assets.models.LicenseAllocation',
    },
    {
        'code': 'ITMaintenanceRecord',
        'name': 'IT维护记录',
        'django_model_path': 'apps.it_assets.models.ITMaintenanceRecord',
    },
    {
        'code': 'ConfigurationChange',
        'name': '配置变更',
        'django_model_path': 'apps.it_assets.models.ConfigurationChange',
    },
    {
        'code': 'Software',
        'name': '软件目录',
        'django_model_path': 'apps.software_licenses.models.Software',
    },
    {
        'code': 'SoftwareLicense',
        'name': '软件许可',
        'django_model_path': 'apps.software_licenses.models.SoftwareLicense',
    },
    {
        'code': 'LicenseAllocation',
        'name': '许可证分配',
        'django_model_path': 'apps.software_licenses.models.LicenseAllocation',
    },
]


def backfill_business_objects(apps, schema_editor):
    BusinessObject = apps.get_model('system', 'BusinessObject')
    manager = BusinessObject._base_manager

    for row in TARGET_OBJECTS:
        code = row['code']
        obj = manager.filter(code=code).first()
        if obj:
            obj.name = row['name']
            obj.is_hardcoded = True
            obj.django_model_path = row['django_model_path']
            obj.enable_workflow = True
            obj.enable_version = True
            obj.enable_soft_delete = True
            obj.is_deleted = False
            obj.deleted_at = None
            obj.save(
                update_fields=[
                    'name',
                    'is_hardcoded',
                    'django_model_path',
                    'enable_workflow',
                    'enable_version',
                    'enable_soft_delete',
                    'is_deleted',
                    'deleted_at',
                    'updated_at',
                ]
            )
            continue

        manager.create(
            code=code,
            name=row['name'],
            is_hardcoded=True,
            django_model_path=row['django_model_path'],
            enable_workflow=True,
            enable_version=True,
            enable_soft_delete=True,
        )


def noop_reverse(apps, schema_editor):
    # Keep records to avoid deleting user-configured metadata in rollback scenarios.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_add_i18n_models'),
    ]

    operations = [
        migrations.RunPython(backfill_business_objects, noop_reverse),
    ]
