from django.db import migrations


def _i18n_name(zh_cn: str, en_us: str) -> dict:
    return {
        'zh-CN': zh_cn,
        'en-US': en_us,
        'default': zh_cn,
    }


def seed_relation_closed_loop_asset_domains(apps, schema_editor):
    ObjectRelationDefinition = apps.get_model('system', 'ObjectRelationDefinition')

    rows = [
        # Asset -> core lifecycle / operations
        {
            'parent_object_code': 'Asset',
            'relation_code': 'maintenance_records',
            'target_object_code': 'Maintenance',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '维修记录',
            'relation_name_en': 'Maintenance Records',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'pickup_orders',
            'target_object_code': 'AssetPickup',
            'relation_kind': 'through_line_item',
            'through_object_code': 'PickupItem',
            'through_parent_fk_field': 'asset',
            'through_target_fk_field': 'pickup',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '领用单据',
            'relation_name_en': 'Pickup Orders',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'transfer_orders',
            'target_object_code': 'AssetTransfer',
            'relation_kind': 'through_line_item',
            'through_object_code': 'TransferItem',
            'through_parent_fk_field': 'asset',
            'through_target_fk_field': 'transfer',
            'display_mode': 'inline_readonly',
            'sort_order': 30,
            'relation_name': '调拨单据',
            'relation_name_en': 'Transfer Orders',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'return_orders',
            'target_object_code': 'AssetReturn',
            'relation_kind': 'through_line_item',
            'through_object_code': 'ReturnItem',
            'through_parent_fk_field': 'asset',
            'through_target_fk_field': 'asset_return',
            'display_mode': 'inline_readonly',
            'sort_order': 40,
            'relation_name': '归还单据',
            'relation_name_en': 'Return Orders',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'loan_orders',
            'target_object_code': 'AssetLoan',
            'relation_kind': 'through_line_item',
            'through_object_code': 'LoanItem',
            'through_parent_fk_field': 'asset',
            'through_target_fk_field': 'loan',
            'display_mode': 'inline_readonly',
            'sort_order': 50,
            'relation_name': '借用单据',
            'relation_name_en': 'Loan Orders',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'disposal_requests',
            'target_object_code': 'DisposalRequest',
            'relation_kind': 'through_line_item',
            'through_object_code': 'DisposalItem',
            'through_parent_fk_field': 'asset',
            'through_target_fk_field': 'disposal_request',
            'display_mode': 'inline_readonly',
            'sort_order': 60,
            'relation_name': '处置申请',
            'relation_name_en': 'Disposal Requests',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'it_asset_profile',
            'target_object_code': 'ITAsset',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 70,
            'relation_name': 'IT资产档案',
            'relation_name_en': 'IT Asset Profile',
        },
        # Asset -> finance / insurance / leasing / IT extension
        {
            'parent_object_code': 'Asset',
            'relation_code': 'depreciation_records',
            'target_object_code': 'DepreciationRecord',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 80,
            'relation_name': '折旧记录',
            'relation_name_en': 'Depreciation Records',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'insurance_coverages',
            'target_object_code': 'InsuredAsset',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 90,
            'relation_name': '投保记录',
            'relation_name_en': 'Insurance Coverages',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'insurance_claims',
            'target_object_code': 'ClaimRecord',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 100,
            'relation_name': '理赔记录',
            'relation_name_en': 'Insurance Claims',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'lease_items',
            'target_object_code': 'LeaseItem',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 110,
            'relation_name': '租赁明细',
            'relation_name_en': 'Lease Items',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'lease_returns',
            'target_object_code': 'LeaseReturn',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 120,
            'relation_name': '租赁归还',
            'relation_name_en': 'Lease Returns',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'it_maintenance_records',
            'target_object_code': 'ITMaintenanceRecord',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 130,
            'relation_name': 'IT维护记录',
            'relation_name_en': 'IT Maintenance Records',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'configuration_changes',
            'target_object_code': 'ConfigurationChange',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 140,
            'relation_name': '配置变更',
            'relation_name_en': 'Configuration Changes',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'it_license_allocations',
            'target_object_code': 'ITLicenseAllocation',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 150,
            'relation_name': '软件许可分配',
            'relation_name_en': 'License Allocations',
        },

        # ITAsset -> related records
        {
            'parent_object_code': 'ITAsset',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'ITAsset',
            'relation_code': 'maintenance_records',
            'target_object_code': 'ITMaintenanceRecord',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'asset_id',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': 'IT维护记录',
            'relation_name_en': 'IT Maintenance Records',
        },
        {
            'parent_object_code': 'ITAsset',
            'relation_code': 'configuration_changes',
            'target_object_code': 'ConfigurationChange',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'asset_id',
            'display_mode': 'inline_readonly',
            'sort_order': 30,
            'relation_name': '配置变更',
            'relation_name_en': 'Configuration Changes',
        },
        {
            'parent_object_code': 'ITAsset',
            'relation_code': 'license_allocations',
            'target_object_code': 'ITLicenseAllocation',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'asset_id',
            'display_mode': 'inline_readonly',
            'sort_order': 40,
            'relation_name': '软件许可分配',
            'relation_name_en': 'License Allocations',
        },

        # Operation documents -> assets
        {
            'parent_object_code': 'AssetLoan',
            'relation_code': 'assets',
            'target_object_code': 'Asset',
            'relation_kind': 'through_line_item',
            'through_object_code': 'LoanItem',
            'through_parent_fk_field': 'loan',
            'through_target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '借用资产',
            'relation_name_en': 'Loan Assets',
        },
        {
            'parent_object_code': 'AssetPickup',
            'relation_code': 'assets',
            'target_object_code': 'Asset',
            'relation_kind': 'through_line_item',
            'through_object_code': 'PickupItem',
            'through_parent_fk_field': 'pickup',
            'through_target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '领用资产',
            'relation_name_en': 'Pickup Assets',
        },
        {
            'parent_object_code': 'AssetTransfer',
            'relation_code': 'assets',
            'target_object_code': 'Asset',
            'relation_kind': 'through_line_item',
            'through_object_code': 'TransferItem',
            'through_parent_fk_field': 'transfer',
            'through_target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '调拨资产',
            'relation_name_en': 'Transfer Assets',
        },
        {
            'parent_object_code': 'AssetReturn',
            'relation_code': 'assets',
            'target_object_code': 'Asset',
            'relation_kind': 'through_line_item',
            'through_object_code': 'ReturnItem',
            'through_parent_fk_field': 'asset_return',
            'through_target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '归还资产',
            'relation_name_en': 'Return Assets',
        },
        {
            'parent_object_code': 'DisposalRequest',
            'relation_code': 'assets',
            'target_object_code': 'Asset',
            'relation_kind': 'through_line_item',
            'through_object_code': 'DisposalItem',
            'through_parent_fk_field': 'disposal_request',
            'through_target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '处置资产',
            'relation_name_en': 'Disposal Assets',
        },

        # Record/detail object -> asset card (single relation)
        {
            'parent_object_code': 'Maintenance',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'DepreciationRecord',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'InsuredAsset',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'ClaimRecord',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'LeaseItem',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'LeaseReturn',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'ITMaintenanceRecord',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'ConfigurationChange',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
        {
            'parent_object_code': 'ITLicenseAllocation',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },
    ]

    for item in rows:
        key = {
            'parent_object_code': item['parent_object_code'],
            'relation_code': item['relation_code'],
        }
        defaults = {
            'target_object_code': item['target_object_code'],
            'relation_kind': item['relation_kind'],
            'target_fk_field': item.get('target_fk_field', ''),
            'through_object_code': item.get('through_object_code', ''),
            'through_parent_fk_field': item.get('through_parent_fk_field', ''),
            'through_target_fk_field': item.get('through_target_fk_field', ''),
            'derived_parent_key_field': item.get('derived_parent_key_field', ''),
            'derived_target_key_field': item.get('derived_target_key_field', ''),
            'display_mode': item.get('display_mode', 'inline_readonly'),
            'sort_order': item.get('sort_order', 0),
            'is_active': True,
            'relation_name': item.get('relation_name', ''),
            'relation_name_en': item.get('relation_name_en', ''),
        }
        relation, _ = ObjectRelationDefinition.objects.update_or_create(**key, defaults=defaults)

        next_extra = dict(relation.extra_config or {})
        next_extra['relation_name_i18n'] = _i18n_name(
            item.get('relation_name', '') or '',
            item.get('relation_name_en', '') or '',
        )
        if relation.extra_config != next_extra:
            relation.extra_config = next_extra
            relation.save(update_fields=['extra_config', 'updated_at'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_object_relation_definition'),
    ]

    operations = [
        migrations.RunPython(seed_relation_closed_loop_asset_domains, noop_reverse),
    ]
