from django.db import migrations


def _i18n_name(zh_cn: str, en_us: str) -> dict:
    return {
        'zh-CN': zh_cn,
        'en-US': en_us,
        'default': zh_cn,
    }


def seed_relation_closed_loop_inventory_consumables(apps, schema_editor):
    ObjectRelationDefinition = apps.get_model('system', 'ObjectRelationDefinition')

    rows = [
        # Asset -> inventory
        {
            'parent_object_code': 'Asset',
            'relation_code': 'inventory_snapshots',
            'target_object_code': 'InventorySnapshot',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 160,
            'relation_name': '盘点快照',
            'relation_name_en': 'Inventory Snapshots',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'inventory_items',
            'target_object_code': 'InventoryItem',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 170,
            'relation_name': '盘点差异',
            'relation_name_en': 'Inventory Differences',
        },
        {
            'parent_object_code': 'Asset',
            'relation_code': 'inventory_tasks',
            'target_object_code': 'InventoryTask',
            'relation_kind': 'through_line_item',
            'through_object_code': 'InventorySnapshot',
            'through_parent_fk_field': 'asset',
            'through_target_fk_field': 'task',
            'display_mode': 'inline_readonly',
            'sort_order': 180,
            'relation_name': '盘点任务',
            'relation_name_en': 'Inventory Tasks',
        },

        # InventoryTask / InventoryItem
        {
            'parent_object_code': 'InventoryTask',
            'relation_code': 'snapshots',
            'target_object_code': 'InventorySnapshot',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'task',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '盘点快照',
            'relation_name_en': 'Snapshots',
        },
        {
            'parent_object_code': 'InventoryTask',
            'relation_code': 'differences',
            'target_object_code': 'InventoryItem',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'task',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '盘点差异',
            'relation_name_en': 'Differences',
        },
        {
            'parent_object_code': 'InventoryTask',
            'relation_code': 'counted_assets',
            'target_object_code': 'Asset',
            'relation_kind': 'through_line_item',
            'through_object_code': 'InventorySnapshot',
            'through_parent_fk_field': 'task',
            'through_target_fk_field': 'asset',
            'display_mode': 'inline_readonly',
            'sort_order': 30,
            'relation_name': '盘点资产',
            'relation_name_en': 'Counted Assets',
        },
        {
            'parent_object_code': 'InventoryItem',
            'relation_code': 'task_card',
            'target_object_code': 'InventoryTask',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'task_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '盘点任务',
            'relation_name_en': 'Inventory Task',
        },
        {
            'parent_object_code': 'InventoryItem',
            'relation_code': 'asset_card',
            'target_object_code': 'Asset',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'asset_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '资产卡片',
            'relation_name_en': 'Asset Card',
        },

        # Consumables
        {
            'parent_object_code': 'Consumable',
            'relation_code': 'stock_transactions',
            'target_object_code': 'ConsumableStock',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'consumable',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '库存流水',
            'relation_name_en': 'Stock Transactions',
        },
        {
            'parent_object_code': 'Consumable',
            'relation_code': 'purchase_orders',
            'target_object_code': 'ConsumablePurchase',
            'relation_kind': 'through_line_item',
            'through_object_code': 'PurchaseItem',
            'through_parent_fk_field': 'consumable',
            'through_target_fk_field': 'purchase',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '采购单据',
            'relation_name_en': 'Purchase Orders',
        },
        {
            'parent_object_code': 'Consumable',
            'relation_code': 'issue_orders',
            'target_object_code': 'ConsumableIssue',
            'relation_kind': 'through_line_item',
            'through_object_code': 'IssueItem',
            'through_parent_fk_field': 'consumable',
            'through_target_fk_field': 'issue',
            'display_mode': 'inline_readonly',
            'sort_order': 30,
            'relation_name': '领用单据',
            'relation_name_en': 'Issue Orders',
        },
        {
            'parent_object_code': 'Consumable',
            'relation_code': 'category_card',
            'target_object_code': 'ConsumableCategory',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'category_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 40,
            'relation_name': '耗材分类',
            'relation_name_en': 'Consumable Category',
        },
        {
            'parent_object_code': 'ConsumablePurchase',
            'relation_code': 'consumables',
            'target_object_code': 'Consumable',
            'relation_kind': 'through_line_item',
            'through_object_code': 'PurchaseItem',
            'through_parent_fk_field': 'purchase',
            'through_target_fk_field': 'consumable',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '采购耗材',
            'relation_name_en': 'Purchased Consumables',
        },
        {
            'parent_object_code': 'ConsumablePurchase',
            'relation_code': 'supplier_card',
            'target_object_code': 'Supplier',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'supplier_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '供应商',
            'relation_name_en': 'Supplier',
        },
        {
            'parent_object_code': 'ConsumableIssue',
            'relation_code': 'consumables',
            'target_object_code': 'Consumable',
            'relation_kind': 'through_line_item',
            'through_object_code': 'IssueItem',
            'through_parent_fk_field': 'issue',
            'through_target_fk_field': 'consumable',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '领用耗材',
            'relation_name_en': 'Issued Consumables',
        },
        {
            'parent_object_code': 'ConsumableIssue',
            'relation_code': 'department_card',
            'target_object_code': 'Organization',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'department_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '领用部门',
            'relation_name_en': 'Issue Department',
        },
        {
            'parent_object_code': 'ConsumableCategory',
            'relation_code': 'consumables',
            'target_object_code': 'Consumable',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'category',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '分类耗材',
            'relation_name_en': 'Category Consumables',
        },
        {
            'parent_object_code': 'Supplier',
            'relation_code': 'consumable_purchases',
            'target_object_code': 'ConsumablePurchase',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'supplier',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '耗材采购',
            'relation_name_en': 'Consumable Purchases',
        },
        {
            'parent_object_code': 'Location',
            'relation_code': 'consumables',
            'target_object_code': 'Consumable',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'warehouse',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '仓位耗材',
            'relation_name_en': 'Warehouse Consumables',
        },

        # Insurance
        {
            'parent_object_code': 'InsurancePolicy',
            'relation_code': 'insured_assets',
            'target_object_code': 'InsuredAsset',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'policy',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '投保资产',
            'relation_name_en': 'Insured Assets',
        },
        {
            'parent_object_code': 'InsurancePolicy',
            'relation_code': 'premium_payments',
            'target_object_code': 'PremiumPayment',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'policy',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '保费支付',
            'relation_name_en': 'Premium Payments',
        },
        {
            'parent_object_code': 'InsurancePolicy',
            'relation_code': 'claim_records',
            'target_object_code': 'ClaimRecord',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'policy',
            'display_mode': 'inline_readonly',
            'sort_order': 30,
            'relation_name': '理赔记录',
            'relation_name_en': 'Claim Records',
        },
        {
            'parent_object_code': 'InsurancePolicy',
            'relation_code': 'renewals_original',
            'target_object_code': 'PolicyRenewal',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'original_policy',
            'display_mode': 'inline_readonly',
            'sort_order': 40,
            'relation_name': '续保记录（原保单）',
            'relation_name_en': 'Renewals (Original)',
        },
        {
            'parent_object_code': 'InsurancePolicy',
            'relation_code': 'renewals_renewed',
            'target_object_code': 'PolicyRenewal',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'renewed_policy',
            'display_mode': 'inline_readonly',
            'sort_order': 50,
            'relation_name': '续保记录（新保单）',
            'relation_name_en': 'Renewals (Renewed)',
        },
        {
            'parent_object_code': 'InsuredAsset',
            'relation_code': 'policy_card',
            'target_object_code': 'InsurancePolicy',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'policy_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '保单',
            'relation_name_en': 'Policy',
        },
        {
            'parent_object_code': 'PremiumPayment',
            'relation_code': 'policy_card',
            'target_object_code': 'InsurancePolicy',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'policy_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '保单',
            'relation_name_en': 'Policy',
        },
        {
            'parent_object_code': 'ClaimRecord',
            'relation_code': 'policy_card',
            'target_object_code': 'InsurancePolicy',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'policy_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '保单',
            'relation_name_en': 'Policy',
        },
        {
            'parent_object_code': 'PolicyRenewal',
            'relation_code': 'original_policy_card',
            'target_object_code': 'InsurancePolicy',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'original_policy_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '原保单',
            'relation_name_en': 'Original Policy',
        },
        {
            'parent_object_code': 'PolicyRenewal',
            'relation_code': 'renewed_policy_card',
            'target_object_code': 'InsurancePolicy',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'renewed_policy_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '新保单',
            'relation_name_en': 'Renewed Policy',
        },

        # Leasing
        {
            'parent_object_code': 'LeasingContract',
            'relation_code': 'lease_items',
            'target_object_code': 'LeaseItem',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'contract',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '租赁明细',
            'relation_name_en': 'Lease Items',
        },
        {
            'parent_object_code': 'LeasingContract',
            'relation_code': 'rent_payments',
            'target_object_code': 'RentPayment',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'contract',
            'display_mode': 'inline_readonly',
            'sort_order': 20,
            'relation_name': '租金支付',
            'relation_name_en': 'Rent Payments',
        },
        {
            'parent_object_code': 'LeasingContract',
            'relation_code': 'lease_returns',
            'target_object_code': 'LeaseReturn',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'contract',
            'display_mode': 'inline_readonly',
            'sort_order': 30,
            'relation_name': '租赁归还',
            'relation_name_en': 'Lease Returns',
        },
        {
            'parent_object_code': 'LeasingContract',
            'relation_code': 'lease_extensions',
            'target_object_code': 'LeaseExtension',
            'relation_kind': 'direct_fk',
            'target_fk_field': 'contract',
            'display_mode': 'inline_readonly',
            'sort_order': 40,
            'relation_name': '租约续期',
            'relation_name_en': 'Lease Extensions',
        },
        {
            'parent_object_code': 'LeaseItem',
            'relation_code': 'contract_card',
            'target_object_code': 'LeasingContract',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'contract_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '租赁合同',
            'relation_name_en': 'Lease Contract',
        },
        {
            'parent_object_code': 'LeaseReturn',
            'relation_code': 'contract_card',
            'target_object_code': 'LeasingContract',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'contract_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '租赁合同',
            'relation_name_en': 'Lease Contract',
        },
        {
            'parent_object_code': 'RentPayment',
            'relation_code': 'contract_card',
            'target_object_code': 'LeasingContract',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'contract_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '租赁合同',
            'relation_name_en': 'Lease Contract',
        },
        {
            'parent_object_code': 'LeaseExtension',
            'relation_code': 'contract_card',
            'target_object_code': 'LeasingContract',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'contract_id',
            'derived_target_key_field': 'id',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '租赁合同',
            'relation_name_en': 'Lease Contract',
        },

        # Finance / depreciation
        {
            'parent_object_code': 'DepreciationRun',
            'relation_code': 'depreciation_records',
            'target_object_code': 'DepreciationRecord',
            'relation_kind': 'derived_query',
            'derived_parent_key_field': 'period',
            'derived_target_key_field': 'period',
            'display_mode': 'inline_readonly',
            'sort_order': 10,
            'relation_name': '折旧记录',
            'relation_name_en': 'Depreciation Records',
        },
    ]

    for item in rows:
        key = {
            'parent_object_code': item['parent_object_code'],
            'relation_code': item['relation_code'],
        }
        defaults = {
            'target_object_code': item['target_object_code'],
            'relation_kind': item['relation_kind'],
            'target_fk_field': item.get('target_fk_field', ''),
            'through_object_code': item.get('through_object_code', ''),
            'through_parent_fk_field': item.get('through_parent_fk_field', ''),
            'through_target_fk_field': item.get('through_target_fk_field', ''),
            'derived_parent_key_field': item.get('derived_parent_key_field', ''),
            'derived_target_key_field': item.get('derived_target_key_field', ''),
            'display_mode': item.get('display_mode', 'inline_readonly'),
            'sort_order': item.get('sort_order', 0),
            'is_active': True,
            'relation_name': item.get('relation_name', ''),
            'relation_name_en': item.get('relation_name_en', ''),
        }
        relation, _ = ObjectRelationDefinition.objects.update_or_create(**key, defaults=defaults)

        next_extra = dict(relation.extra_config or {})
        next_extra['relation_name_i18n'] = _i18n_name(
            item.get('relation_name', '') or '',
            item.get('relation_name_en', '') or '',
        )
        if relation.extra_config != next_extra:
            relation.extra_config = next_extra
            relation.save(update_fields=['extra_config', 'updated_at'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_seed_relation_closed_loop_asset_domains'),
    ]

    operations = [
        migrations.RunPython(seed_relation_closed_loop_inventory_consumables, noop_reverse),
    ]
