# Generated by Django 5.2.10 on 2026-03-07 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        ('system', '0031_seed_relation_group_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='objectrelationdefinition',
            name='object_rela_created_11b960_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectrelationdefinition',
            name='object_rela_is_dele_4e121e_idx',
        ),
        migrations.RenameIndex(
            model_name='objectrelationdefinition',
            new_name='object_rela_parent__055ca1_idx',
            old_name='object_rela_parent__7fcf47_idx',
        ),
        migrations.RenameIndex(
            model_name='objectrelationdefinition',
            new_name='object_rela_parent__ec15ab_idx',
            old_name='object_rela_parent__772d85_idx',
        ),
        migrations.RenameIndex(
            model_name='objectrelationdefinition',
            new_name='object_rela_target__e68ee0_idx',
            old_name='object_rela_target__b817f2_idx',
        ),
        migrations.RenameIndex(
            model_name='objectrelationdefinition',
            new_name='object_rela_relatio_cd3bbe_idx',
            old_name='object_rela_relatio_be9e0a_idx',
        ),
        migrations.AddField(
            model_name='businessobject',
            name='is_menu_hidden',
            field=models.BooleanField(db_comment='Hide from automated sidebar menu', default=False),
        ),
        migrations.AddField(
            model_name='businessobject',
            name='menu_category',
            field=models.CharField(blank=True, db_comment='Menu category for automated routing', max_length=50),
        ),
        migrations.AlterField(
            model_name='objectrelationdefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='objectrelationdefinition',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AlterField(
            model_name='objectrelationdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='objectrelationdefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
