# Generated by Django 5.2.10 on 2026-03-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_remove_activitylog_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='view_mode',
            field=models.CharField(choices=[('Detail', 'Detail View'), ('Compact', 'Compact View')], db_comment='View mode (Detail or Compact)', default='Detail', max_length=20),
        ),
    ]
