# Generated by Django 5.0.1 on 2026-03-11 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_add_base_model_fields"),
        ("system", "0037_seed_display_tier_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="menuentry",
            name="menu_entries_created_8d1592_idx",
        ),
        migrations.RemoveIndex(
            model_name="menuentry",
            name="menu_entries_is_dele_56430b_idx",
        ),
        migrations.RemoveIndex(
            model_name="menugroup",
            name="menu_groups_created_at_b0fe26_idx",
        ),
        migrations.RemoveIndex(
            model_name="menugroup",
            name="menu_groups_is_delet_b80cab_idx",
        ),
        migrations.RenameIndex(
            model_name="menuentry",
            new_name="menu_entrie_source__42b4a4_idx",
            old_name="menu_entries_source__726de6_idx",
        ),
        migrations.RenameIndex(
            model_name="menuentry",
            new_name="menu_entrie_code_7e3967_idx",
            old_name="menu_entries_code_4f4f4e_idx",
        ),
        migrations.RenameIndex(
            model_name="menuentry",
            new_name="menu_entrie_sort_or_db30cb_idx",
            old_name="menu_entries_sort_o_a47a61_idx",
        ),
        migrations.RenameIndex(
            model_name="menuentry",
            new_name="menu_entrie_is_visi_8afb16_idx",
            old_name="menu_entries_is_vis_857d1d_idx",
        ),
        migrations.RenameIndex(
            model_name="menugroup",
            new_name="menu_groups_code_75bdcf_idx",
            old_name="menu_groups_code_b81254_idx",
        ),
        migrations.RenameIndex(
            model_name="menugroup",
            new_name="menu_groups_sort_or_528eeb_idx",
            old_name="menu_groups_sort_or_7b5ca8_idx",
        ),
        migrations.RenameIndex(
            model_name="menugroup",
            new_name="menu_groups_is_visi_02b0a4_idx",
            old_name="menu_groups_is_visi_2da8d0_idx",
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="is_reverse_relation",
            field=models.BooleanField(
                db_comment="[DEPRECATED] True if this field represents a reverse relation (related_name)",
                default=False,
                help_text="DEPRECATED: Use ObjectRelationDefinition instead.",
            ),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="relation_display_mode",
            field=models.CharField(
                choices=[
                    ("inline_editable", "Inline Editable Table"),
                    ("inline_readonly", "Inline Read-Only Table"),
                    ("tab_readonly", "Tab Read-Only Table"),
                    ("hidden", "Hidden"),
                ],
                db_comment="[DEPRECATED] How to display reverse relations",
                default="tab_readonly",
                help_text="DEPRECATED: Use ObjectRelationDefinition.display_mode instead.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="reverse_relation_field",
            field=models.CharField(
                blank=True,
                db_comment="[DEPRECATED] FK field name on related model",
                help_text="DEPRECATED: Use ObjectRelationDefinition.target_fk_field instead.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="reverse_relation_model",
            field=models.CharField(
                blank=True,
                db_comment="[DEPRECATED] Path to model that owns this relation",
                help_text="DEPRECATED: Use ObjectRelationDefinition.target_object_code instead.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="menuentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="menuentry",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="User who soft deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
        migrations.AlterField(
            model_name="menuentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Organization for multi-tenant data isolation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="menuentry",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterField(
            model_name="menugroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="menugroup",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="User who soft deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
        migrations.AlterField(
            model_name="menugroup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_comment="Organization for multi-tenant data isolation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="menugroup",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="User who last updated this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
    ]
