# Generated by Django 5.0.1 on 2026-03-27 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_add_base_model_fields"),
        ("system", "0051_object_history_convergence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedLoopDashboardSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "dashboard_code",
                    models.CharField(
                        db_comment="Dashboard identifier for future multi-dashboard snapshot support",
                        db_index=True,
                        default="closed_loop",
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(db_comment="Human-readable snapshot label", max_length=120),
                ),
                (
                    "window_key",
                    models.CharField(
                        db_comment="Closed-loop reporting window key", default="30d", max_length=10
                    ),
                ),
                (
                    "object_codes",
                    models.JSONField(
                        blank=True,
                        db_comment="Filtered object codes included in this snapshot",
                        default=list,
                    ),
                ),
                (
                    "overview_payload",
                    models.JSONField(
                        blank=True,
                        db_comment="Stored overview payload for the snapshot",
                        default=dict,
                    ),
                ),
                (
                    "by_object_payload",
                    models.JSONField(
                        blank=True,
                        db_comment="Stored by-object payload for the snapshot",
                        default=list,
                    ),
                ),
                (
                    "queues_payload",
                    models.JSONField(
                        blank=True,
                        db_comment="Stored queue ranking payload for the snapshot",
                        default=list,
                    ),
                ),
                (
                    "bottlenecks_payload",
                    models.JSONField(
                        blank=True,
                        db_comment="Stored bottleneck payload for the snapshot",
                        default=list,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who soft deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Closed-Loop Dashboard Snapshot",
                "verbose_name_plural": "Closed-Loop Dashboard Snapshots",
                "db_table": "closed_loop_dashboard_snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "dashboard_code", "-created_at"],
                        name="closed_loop_organiz_78bed4_idx",
                    ),
                    models.Index(
                        fields=["organization", "window_key", "-created_at"],
                        name="closed_loop_organiz_5c2d04_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"], name="closed_loop_created_d7640d_idx"
                    ),
                ],
            },
        ),
    ]
