# Generated by Django 5.0.1 on 2026-03-30 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0053_tagassignment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tagassignment",
            new_name="tag_assignm_organiz_a460fa_idx",
            old_name="tag_assignme_organiz_28e2da_idx",
        ),
        migrations.RenameIndex(
            model_name="tagassignment",
            new_name="tag_assignm_organiz_8c9a83_idx",
            old_name="tag_assignme_organiz_1df73a_idx",
        ),
        migrations.RenameIndex(
            model_name="tagassignment",
            new_name="tag_assignm_organiz_5ecd30_idx",
            old_name="tag_assignme_organiz_c92a07_idx",
        ),
    ]
