# Generated by Django 5.0.1 on 2026-01-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="error_code",
            field=models.CharField(
                blank=True,
                help_text="Error code from channel",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Detailed error message", null=True
            ),
        ),
    ]
