# Generated by Django 5.0.1 on 2026-01-19 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0002_alter_notificationlog_error_code_and_more"),
        ("organizations", "0003_organization_wework_dept_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InAppMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("system", "System"),
                            ("reminder", "Reminder"),
                            ("user", "User Message"),
                        ],
                        default="announcement",
                        help_text="Type of in-app message",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Message title", max_length=200)),
                (
                    "content",
                    models.TextField(help_text="Message content (supports Markdown)"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        default="normal",
                        help_text="Message priority level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Message publication status",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        default="all",
                        help_text="Target: all, users, roles, departments",
                        max_length=20,
                    ),
                ),
                (
                    "target_ids",
                    models.JSONField(default=list, help_text="List of target IDs"),
                ),
                (
                    "exclude_users",
                    models.JSONField(
                        default=list, help_text="List of user IDs to exclude"
                    ),
                ),
                (
                    "show_popup",
                    models.BooleanField(
                        default=False,
                        help_text="Show as popup/modal instead of notification",
                    ),
                ),
                (
                    "dismissible",
                    models.BooleanField(
                        default=True, help_text="Whether user can dismiss the message"
                    ),
                ),
                (
                    "requires_acknowledgment",
                    models.BooleanField(
                        default=False,
                        help_text="Require user acknowledgment to dismiss",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled publish time", null=True
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, help_text="Message expiration time", null=True
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, help_text="Number of times message was viewed"
                    ),
                ),
                (
                    "acknowledge_count",
                    models.IntegerField(
                        default=0, help_text="Number of acknowledgments received"
                    ),
                ),
                (
                    "dismiss_count",
                    models.IntegerField(
                        default=0, help_text="Number of times message was dismissed"
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, help_text="URL for action button"),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, help_text="Label for action button", max_length=50
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Related object ID", null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message author",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related object type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "In-App Message",
                "verbose_name_plural": "In-App Messages",
                "db_table": "in_app_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["message_type", "status"],
                        name="in_app_mess_message_996d2a_idx",
                    ),
                    models.Index(
                        fields=["status", "publish_at"],
                        name="in_app_mess_status_bd74c8_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="in_app_mess_priorit_723c0c_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="in_app_mess_created_40d964_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("wework", "WeWork"),
                            ("dingtalk", "DingTalk"),
                            ("feishu", "Feishu"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("inapp", "In-App"),
                        ],
                        db_index=True,
                        help_text="Channel type identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        help_text="Human-readable channel name", max_length=100
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Channel-specific configuration"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Channel priority (higher = preferred)"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this channel is enabled"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="active",
                        help_text="Channel operational status",
                        max_length=20,
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(
                        default=60, help_text="Maximum messages per minute"
                    ),
                ),
                (
                    "rate_limit_per_hour",
                    models.IntegerField(
                        default=1000, help_text="Maximum messages per hour"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, help_text="Maximum retry attempts for failed sends"
                    ),
                ),
                (
                    "retry_delay_seconds",
                    models.IntegerField(
                        default=60, help_text="Delay between retries in seconds"
                    ),
                ),
                (
                    "template_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="Notification type to template code mapping",
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, help_text="Last error timestamp", null=True
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, help_text="Last error message"),
                ),
                (
                    "consecutive_failures",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive failures"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL for delivery status callbacks",
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for webhook signature verification",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Channel",
                "verbose_name_plural": "Notification Channels",
                "db_table": "notification_channel",
                "ordering": ["-priority", "channel_type"],
                "indexes": [
                    models.Index(
                        fields=["channel_type"], name="notificatio_channel_53a11f_idx"
                    ),
                    models.Index(
                        fields=["is_enabled", "status"],
                        name="notificatio_is_enab_91ec97_idx",
                    ),
                    models.Index(
                        fields=["-priority"], name="notificatio_priorit_6183b4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "message_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique message identifier (auto-generated)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        db_index=True, help_text="Notification type code", max_length=50
                    ),
                ),
                ("title", models.CharField(help_text="Message title", max_length=200)),
                ("content", models.TextField(help_text="Message content body")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line (for email, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="Target type: user, role, department, or all",
                        max_length=20,
                    ),
                ),
                (
                    "target_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of target IDs (users, roles, departments)",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list, help_text="List of channel types to use"
                    ),
                ),
                (
                    "primary_channel",
                    models.CharField(
                        blank=True, help_text="Primary delivery channel", max_length=20
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        default="normal",
                        help_text="Message priority",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("partial", "Partially Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Message status",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled send time", null=True
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual send time", null=True
                    ),
                ),
                (
                    "total_recipients",
                    models.IntegerField(
                        default=0, help_text="Total number of recipients"
                    ),
                ),
                (
                    "sent_count",
                    models.IntegerField(default=0, help_text="Successfully sent count"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, help_text="Failed send count"),
                ),
                (
                    "read_count",
                    models.IntegerField(default=0, help_text="Read/acknowledged count"),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Delivery progress percentage (0-100)"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Additional message data and metadata"
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Related object ID", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Overall error message if send failed"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related object type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created/sent this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used for this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Message",
                "verbose_name_plural": "Notification Messages",
                "db_table": "notification_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["message_code"], name="notificatio_message_980b80_idx"
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_3c07cb_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="notificatio_status_71cfac_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="notificatio_priorit_f4f22e_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_fbd05d_idx"
                    ),
                ],
            },
        ),
    ]
