# Generated by Django 5.2.10 on 2026-01-25 05:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('voucher_no', models.CharField(db_index=True, help_text='Unique voucher number', max_length=50, unique=True)),
                ('voucher_date', models.DateField(help_text='Voucher date')),
                ('business_type', models.CharField(choices=[('purchase', 'Asset Purchase'), ('depreciation', 'Asset Depreciation'), ('disposal', 'Asset Disposal'), ('inventory', 'Asset Inventory'), ('other', 'Other')], help_text='Business type', max_length=50)),
                ('summary', models.CharField(help_text='Voucher summary', max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total voucher amount', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='draft', help_text='Voucher status', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('erp_voucher_no', models.CharField(blank=True, help_text='ERP voucher number after posting', max_length=100)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Timestamp when voucher was posted to ERP', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('posted_by', models.ForeignKey(blank=True, help_text='User who posted to ERP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_vouchers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Finance Voucher',
                'verbose_name_plural': 'Finance Vouchers',
                'db_table': 'finance_vouchers',
                'ordering': ['-voucher_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('account_code', models.CharField(db_index=True, help_text='Account code (chart of accounts)', max_length=50)),
                ('account_name', models.CharField(help_text='Account name', max_length=200)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(help_text='Entry description', max_length=500)),
                ('line_no', models.IntegerField(default=1, help_text='Line number for sorting')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('voucher', models.ForeignKey(help_text='Parent voucher', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.financevoucher')),
            ],
            options={
                'verbose_name': 'Voucher Entry',
                'verbose_name_plural': 'Voucher Entries',
                'db_table': 'voucher_entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Template code', max_length=50, unique=True)),
                ('business_type', models.CharField(choices=[('purchase', 'Asset Purchase'), ('depreciation', 'Asset Depreciation'), ('disposal', 'Asset Disposal'), ('inventory', 'Asset Inventory'), ('other', 'Other')], help_text='Business type', max_length=50)),
                ('template_config', models.JSONField(default=dict, help_text='Template configuration (accounts, amounts, formulas)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether template is active')),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Voucher Template',
                'verbose_name_plural': 'Voucher Templates',
                'db_table': 'voucher_templates',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='financevoucher',
            index=models.Index(fields=['organization', 'voucher_no'], name='finance_vou_organiz_cd355e_idx'),
        ),
        migrations.AddIndex(
            model_name='financevoucher',
            index=models.Index(fields=['organization', 'voucher_date'], name='finance_vou_organiz_1f66f2_idx'),
        ),
        migrations.AddIndex(
            model_name='financevoucher',
            index=models.Index(fields=['organization', 'business_type'], name='finance_vou_organiz_9b7501_idx'),
        ),
        migrations.AddIndex(
            model_name='financevoucher',
            index=models.Index(fields=['organization', 'status'], name='finance_vou_organiz_373917_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['organization', 'voucher'], name='voucher_ent_organiz_4ab1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['organization', 'account_code'], name='voucher_ent_organiz_1a64d2_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchertemplate',
            index=models.Index(fields=['organization', 'code'], name='voucher_tem_organiz_b02b41_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchertemplate',
            index=models.Index(fields=['organization', 'business_type'], name='voucher_tem_organiz_946ceb_idx'),
        ),
    ]
