# Generated by Django 5.0.1 on 2026-01-18 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeWorkConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "corp_id",
                    models.CharField(
                        db_index=True, help_text="WeWork Corp ID (企业ID)", max_length=100
                    ),
                ),
                (
                    "corp_name",
                    models.CharField(
                        help_text="WeWork Corp Name (企业名称)", max_length=200
                    ),
                ),
                ("agent_id", models.IntegerField(help_text="WeWork Agent ID (应用ID)")),
                (
                    "agent_secret",
                    models.CharField(
                        help_text="WeWork Agent Secret (应用Secret)", max_length=200
                    ),
                ),
                (
                    "sync_department",
                    models.BooleanField(
                        default=True, help_text="Sync departments from WeWork"
                    ),
                ),
                (
                    "sync_user",
                    models.BooleanField(
                        default=True, help_text="Sync users from WeWork"
                    ),
                ),
                (
                    "auto_create_user",
                    models.BooleanField(
                        default=True, help_text="Auto-create user on first SSO login"
                    ),
                ),
                (
                    "default_role_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Default role ID for auto-created users",
                        null=True,
                    ),
                ),
                (
                    "redirect_uri",
                    models.URLField(
                        blank=True,
                        help_text="Custom redirect URI for OAuth callback",
                        max_length=500,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether WeWork SSO is enabled",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "WeWork Config",
                "verbose_name_plural": "WeWork Configs",
                "db_table": "wework_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_index=True,
                        help_text="OAuth state token (防CSRF)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="Platform type (wework/dingtalk/feishu)",
                        max_length=20,
                    ),
                ),
                (
                    "session_data",
                    models.JSONField(
                        default=dict, help_text="Session data stored with state"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="State expiration time"
                    ),
                ),
                (
                    "consumed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether state has been consumed",
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, help_text="When state was consumed", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth State",
                "verbose_name_plural": "OAuth States",
                "db_table": "oauth_state",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "consumed"],
                        name="oauth_state_state_9513af_idx",
                    ),
                    models.Index(
                        fields=["platform", "expires_at"],
                        name="oauth_state_platfor_24d119_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("wework", "WeWork"),
                            ("dingtalk", "DingTalk"),
                            ("feishu", "Feishu"),
                        ],
                        db_index=True,
                        help_text="Platform type",
                        max_length=20,
                    ),
                ),
                (
                    "platform_userid",
                    models.CharField(
                        db_index=True, help_text="Platform user ID", max_length=100
                    ),
                ),
                (
                    "platform_unionid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Platform UnionID (cross-app unique ID)",
                        max_length=100,
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        blank=True, help_text="Platform display name", max_length=200
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        default=dict,
                        help_text="Extra platform data (avatar, position, etc.)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "system_user",
                    models.ForeignKey(
                        help_text="System user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Mapping",
                "verbose_name_plural": "User Mappings",
                "db_table": "user_mapping",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["system_user", "platform"],
                        name="user_mappin_system__2f6921_idx",
                    ),
                    models.Index(
                        fields=["platform", "platform_userid"],
                        name="user_mappin_platfor_e1c502_idx",
                    ),
                    models.Index(
                        fields=["platform", "platform_unionid"],
                        name="user_mappin_platfor_d2ff70_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usermapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("platform", "platform_userid", "is_deleted"),
                name="unique_platform_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="weworkconfig",
            index=models.Index(
                fields=["corp_id"], name="wework_conf_corp_id_3c1b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weworkconfig",
            index=models.Index(
                fields=["is_enabled"], name="wework_conf_is_enab_d165ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weworkconfig",
            index=models.Index(
                fields=["organization", "is_enabled"],
                name="wework_conf_organiz_3fc17f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="weworkconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organization", "is_deleted"),
                name="unique_active_wework_config_per_org",
            ),
        ),
    ]
