# Generated by Django 5.0.1 on 2026-01-19 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_wework_dept_id_and_more"),
        ("sso", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("department", "Department Sync"),
                            ("user", "User Sync"),
                            ("full", "Full Sync"),
                        ],
                        max_length=20,
                        verbose_name="Sync Type",
                    ),
                ),
                (
                    "sync_source",
                    models.CharField(
                        choices=[
                            ("wework", "WeWork"),
                            ("dingtalk", "DingTalk"),
                            ("feishu", "Feishu"),
                        ],
                        default="wework",
                        max_length=20,
                        verbose_name="Sync Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished At"
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="Total Count"),
                ),
                (
                    "created_count",
                    models.IntegerField(default=0, verbose_name="Created Count"),
                ),
                (
                    "updated_count",
                    models.IntegerField(default=0, verbose_name="Updated Count"),
                ),
                (
                    "deleted_count",
                    models.IntegerField(default=0, verbose_name="Deleted Count"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, verbose_name="Failed Count"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Error Details"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "db_table": "sso_sync_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "sync_type"],
                        name="sso_sync_lo_organiz_873010_idx",
                    ),
                    models.Index(
                        fields=["status"], name="sso_sync_lo_status_200092_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="sso_sync_lo_started_8d2c0e_idx"
                    ),
                ],
            },
        ),
    ]
