# Generated by Django 5.0.1 on 2026-01-18 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member'), ('auditor', 'Auditor')], db_comment='User role in this organization', default='member', max_length=20)),
                ('is_active', models.BooleanField(db_comment='Is this membership active', default=True)),
                ('is_primary', models.BooleanField(db_comment='Is this the user primary organization', default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_comment='When user joined the organization')),
            ],
            options={
                'verbose_name': 'User Organization',
                'verbose_name_plural': 'User Organizations',
                'db_table': 'user_organizations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.ForeignKey(blank=True, db_comment='User current selected organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='dingtalk_unionid',
            field=models.CharField(blank=True, db_comment='DingTalk Union ID', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dingtalk_userid',
            field=models.CharField(blank=True, db_comment='DingTalk User ID', db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feishu_unionid',
            field=models.CharField(blank=True, db_comment='Feishu Union ID', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='feishu_userid',
            field=models.CharField(blank=True, db_comment='Feishu User ID', db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wework_unionid',
            field=models.CharField(blank=True, db_comment='WeChat Work Union ID', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wework_userid',
            field=models.CharField(blank=True, db_comment='WeChat Work User ID', db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['wework_userid'], name='users_wework__eac125_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['dingtalk_userid'], name='users_dingtal_ffb476_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['feishu_userid'], name='users_feishu__fc2c72_idx'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='invited_by',
            field=models.ForeignKey(blank=True, db_comment='User who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='organization',
            field=models.ForeignKey(db_comment='Organization reference', on_delete=django.db.models.deletion.CASCADE, related_name='org_users', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='user',
            field=models.ForeignKey(db_comment='User reference', on_delete=django.db.models.deletion.CASCADE, related_name='user_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userorganization',
            index=models.Index(fields=['user', 'is_active'], name='user_organi_user_id_dd9759_idx'),
        ),
        migrations.AddIndex(
            model_name='userorganization',
            index=models.Index(fields=['organization', 'is_active'], name='user_organi_organiz_c40157_idx'),
        ),
        migrations.AddIndex(
            model_name='userorganization',
            index=models.Index(fields=['is_primary'], name='user_organi_is_prim_7f28c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userorganization',
            unique_together={('user', 'organization')},
        ),
    ]
