# Generated by Django 5.0.1 on 2026-01-19 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0004_delete_department_department_userdepartment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("all", "All Data"),
                            ("self", "Own Data Only"),
                            ("self_dept", "Own Department"),
                            ("self_and_sub", "Department and Sub-departments"),
                            ("specified", "Specified Departments"),
                            ("custom", "Custom Filter"),
                        ],
                        db_comment="Data access scope type",
                        default="self_dept",
                        max_length=20,
                        verbose_name="Scope Type",
                    ),
                ),
                (
                    "scope_value",
                    models.JSONField(
                        blank=True,
                        db_comment="Configuration for scope (dept IDs, custom filter, etc.)",
                        default=dict,
                        verbose_name="Scope Value",
                    ),
                ),
                (
                    "department_field",
                    models.CharField(
                        blank=True,
                        db_comment="Field name for department reference in the target model",
                        default="department",
                        max_length=100,
                        verbose_name="Department Field",
                    ),
                ),
                (
                    "user_field",
                    models.CharField(
                        blank=True,
                        db_comment="Field name for user reference in the target model",
                        default="created_by",
                        max_length=100,
                        verbose_name="User Field",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_comment="Description of what this permission controls",
                        verbose_name="Description",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        db_comment="Model this permission applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_permissions",
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="User this permission applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Permission",
                "verbose_name_plural": "Data Permissions",
                "db_table": "permissions_data_permission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataPermissionExpand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "filter_conditions",
                    models.JSONField(
                        blank=True,
                        db_comment="Additional filter conditions in JSON format",
                        default=dict,
                        verbose_name="Filter Conditions",
                    ),
                ),
                (
                    "allowed_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="List of field names that are accessible",
                        default=list,
                        verbose_name="Allowed Fields",
                    ),
                ),
                (
                    "denied_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="List of field names that are explicitly denied",
                        default=list,
                        verbose_name="Denied Fields",
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        blank=True,
                        db_comment="List of allowed actions (view, create, update, delete, export)",
                        default=list,
                        verbose_name="Allowed Actions",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_comment="Higher priority rules are evaluated first",
                        default=0,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Whether this expansion is currently active",
                        default=True,
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_comment="Description of what this expansion controls",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_permission",
                    models.ForeignKey(
                        db_comment="Base data permission this expands upon",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expansions",
                        to="permissions.datapermission",
                        verbose_name="Data Permission",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Permission Expansion",
                "verbose_name_plural": "Data Permission Expansions",
                "db_table": "permissions_data_permission_expand",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        db_comment="Name of the field this permission controls",
                        max_length=100,
                        verbose_name="Field Name",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("hidden", "Hidden"),
                            ("masked", "Masked"),
                        ],
                        db_comment="Type of permission: read/write/hidden/masked",
                        default="read",
                        max_length=20,
                        verbose_name="Permission Type",
                    ),
                ),
                (
                    "mask_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phone", "Phone - Keep first 3 and last 4 digits"),
                            ("id_card", "ID Card - Keep first 3 and last 4 digits"),
                            ("bank_card", "Bank Card - Keep last 4 digits"),
                            ("name", "Name - Keep last character"),
                            ("email", "Email - Mask local part"),
                            ("amount", "Amount - Show range only"),
                            ("custom", "Custom masking rule"),
                        ],
                        db_comment="Masking rule when permission_type is masked",
                        max_length=50,
                        null=True,
                        verbose_name="Mask Rule",
                    ),
                ),
                (
                    "custom_mask_pattern",
                    models.CharField(
                        blank=True,
                        db_comment="Custom regex pattern for masking (when mask_rule=custom)",
                        max_length=200,
                        null=True,
                        verbose_name="Custom Mask Pattern",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True,
                        db_comment="Conditional expression for when this permission applies",
                        null=True,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_comment="Higher priority permissions override lower ones",
                        default=0,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_comment="Description of what this permission controls",
                        verbose_name="Description",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        db_comment="Model this permission applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="User this permission applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Permission",
                "verbose_name_plural": "Field Permissions",
                "db_table": "permissions_field_permission",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("check", "Permission Check"),
                            ("grant", "Grant Permission"),
                            ("revoke", "Revoke Permission"),
                            ("modify", "Modify Permission"),
                            ("deny", "Access Denied"),
                        ],
                        db_comment="Type of operation performed",
                        max_length=20,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("field_permission", "Field Permission"),
                            ("data_permission", "Data Permission"),
                            ("user_permission", "User Permission"),
                        ],
                        db_comment="Type of permission target",
                        max_length=50,
                        verbose_name="Target Type",
                    ),
                ),
                (
                    "permission_details",
                    models.JSONField(
                        blank=True,
                        db_comment="Details about the permission (field, scope, etc.)",
                        default=dict,
                        verbose_name="Permission Details",
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Object ID"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("partial", "Partial Success"),
                        ],
                        db_comment="Result of the operation",
                        default="success",
                        max_length=20,
                        verbose_name="Result",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        db_comment="Error details if operation failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_comment="IP address from which the request originated",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        db_comment="User agent string of the request",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "request_metadata",
                    models.JSONField(
                        blank=True,
                        db_comment="Additional request metadata",
                        default=dict,
                        verbose_name="Request Metadata",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who performed this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audit_logs",
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User affected by this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Target User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Audit Log",
                "verbose_name_plural": "Permission Audit Logs",
                "db_table": "permissions_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="datapermission",
            index=models.Index(
                fields=["content_type", "scope_type"],
                name="permissions_content_458989_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datapermission",
            index=models.Index(
                fields=["user", "scope_type"], name="permissions_user_id_42ed54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datapermission",
            index=models.Index(
                fields=["-created_at"], name="permissions_created_251f01_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datapermission",
            unique_together={("user", "content_type")},
        ),
        migrations.AddIndex(
            model_name="datapermissionexpand",
            index=models.Index(
                fields=["data_permission", "priority"],
                name="permissions_data_pe_b5698e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datapermissionexpand",
            index=models.Index(
                fields=["is_active"], name="permissions_is_acti_e4ea0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datapermissionexpand",
            index=models.Index(
                fields=["-created_at"], name="permissions_created_16c719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldpermission",
            index=models.Index(
                fields=["content_type", "field_name"],
                name="permissions_content_6d8d04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldpermission",
            index=models.Index(
                fields=["user", "permission_type"],
                name="permissions_user_id_da837b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldpermission",
            index=models.Index(
                fields=["priority"], name="permissions_priorit_30fa43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldpermission",
            index=models.Index(
                fields=["-created_at"], name="permissions_created_7204eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fieldpermission",
            unique_together={("user", "content_type", "field_name")},
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="permissions_actor_i_b8d73e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["target_user", "-created_at"],
                name="permissions_target__5f25d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["operation_type", "-created_at"],
                name="permissions_operati_6778fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["result", "-created_at"], name="permissions_result_bd073b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="permissions_content_157096_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["-created_at"], name="permissions_created_83566a_idx"
            ),
        ),
    ]
