# Generated by Django 5.2.10 on 2026-01-20 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datapermission',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='datapermission',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='datapermissionexpand',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='datapermissionexpand',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='fieldpermission',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='fieldpermission',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
