import {
  assetReceiptActionApi,
  assetWarrantyActionApi,
  disposalRequestActionApi,
  maintenanceActionApi,
  maintenancePlanActionApi,
  maintenanceTaskActionApi,
  purchaseRequestActionApi
} from '@/api/lifecycleActionApi'

import type { LifecycleDetailStatusActionFactory } from './lifecycleDetailTypes'

const lifecycleDetailStatusActionRegistry: Record<string, LifecycleDetailStatusActionFactory> = {
  PurchaseRequest: (id, t) => [
    {
      key: 'submit',
      label: t('assets.lifecycle.purchaseRequest.actions.submit'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.purchaseRequest.actions.submit')}?`,
      apiCall: () => purchaseRequestActionApi.submit(id),
      visibleWhen: (status) => status === 'draft',
    },
    {
      key: 'approve',
      label: t('assets.lifecycle.purchaseRequest.actions.approve'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.purchaseRequest.actions.approve')}?`,
      apiCall: () => purchaseRequestActionApi.approve(id, 'approved'),
      visibleWhen: (status) => status === 'submitted',
    },
    {
      key: 'reject',
      label: t('assets.lifecycle.purchaseRequest.actions.reject'),
      type: 'danger',
      confirmMessage: `${t('assets.lifecycle.purchaseRequest.actions.reject')}?`,
      confirmType: 'warning',
      apiCall: () => purchaseRequestActionApi.approve(id, 'rejected'),
      visibleWhen: (status) => status === 'submitted',
    },
    {
      key: 'complete',
      label: t('assets.lifecycle.purchaseRequest.actions.complete'),
      type: 'success',
      confirmMessage: `${t('common.actions.complete')}?`,
      apiCall: () => purchaseRequestActionApi.complete(id),
      visibleWhen: (status) => status === 'processing',
    },
    {
      key: 'cancel',
      label: t('assets.lifecycle.purchaseRequest.actions.cancel'),
      type: 'default',
      confirmMessage: t('assets.lifecycle.purchaseRequest.messages.cancelConfirm'),
      confirmType: 'warning',
      apiCall: () => purchaseRequestActionApi.cancel(id),
      visibleWhen: (status) => ['draft', 'submitted'].includes(status),
    },
  ],
  AssetReceipt: (id, t) => [
    {
      key: 'submitInspection',
      label: t('assets.lifecycle.assetReceipt.actions.submitInspection'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.assetReceipt.actions.submitInspection')}?`,
      apiCall: () => assetReceiptActionApi.submitInspection(id),
      visibleWhen: (status) => status === 'draft',
    },
    {
      key: 'inspect',
      label: t('assets.lifecycle.assetReceipt.actions.inspect'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.assetReceipt.actions.inspect')}?`,
      apiCall: () => assetReceiptActionApi.inspect(id, '', true),
      visibleWhen: (status) => status === 'inspecting',
    },
    {
      key: 'generateAssets',
      label: t('assets.lifecycle.assetReceipt.actions.generateAssets'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.assetReceipt.actions.generateAssets')}?`,
      apiCall: () => assetReceiptActionApi.generateAssets(id),
      visibleWhen: (status) => status === 'passed',
    },
    {
      key: 'cancel',
      label: t('common.actions.cancel'),
      type: 'default',
      confirmMessage: t('common.messages.confirmCancel'),
      confirmType: 'warning',
      apiCall: () => assetReceiptActionApi.cancel(id),
      visibleWhen: (status) => ['draft', 'submitted'].includes(status),
    },
  ],
  Maintenance: (id, t) => [
    {
      key: 'assign',
      label: t('assets.lifecycle.maintenance.actions.assign'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.maintenance.actions.assign')}?`,
      apiCall: () => maintenanceActionApi.assign(id, ''),
      visibleWhen: (status) => status === 'pending',
    },
    {
      key: 'startWork',
      label: t('assets.lifecycle.maintenance.actions.startWork'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.maintenance.actions.startWork')}?`,
      apiCall: () => maintenanceActionApi.startWork(id),
      visibleWhen: (status) => status === 'assigned',
    },
    {
      key: 'complete',
      label: t('assets.lifecycle.maintenance.actions.complete'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.maintenance.actions.complete')}?`,
      apiCall: () => maintenanceActionApi.completeWork(id, {}),
      visibleWhen: (status) => status === 'in_progress',
    },
    {
      key: 'verify',
      label: t('assets.lifecycle.maintenance.actions.verify'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.maintenance.actions.verify')}?`,
      apiCall: () => maintenanceActionApi.verify(id, 'approved'),
      visibleWhen: (status) => status === 'completed',
    },
    {
      key: 'cancel',
      label: t('common.actions.cancel'),
      type: 'default',
      confirmMessage: t('common.messages.confirmCancel'),
      confirmType: 'warning',
      apiCall: () => maintenanceActionApi.cancel(id),
      visibleWhen: (status) => ['pending', 'assigned'].includes(status),
    },
  ],
  MaintenancePlan: (id, t) => [
    {
      key: 'activate',
      label: t('assets.lifecycle.maintenancePlan.actions.activate'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.maintenancePlan.actions.activate')}?`,
      apiCall: () => maintenancePlanActionApi.activate(id),
      visibleWhen: (status) => status === 'draft',
    },
    {
      key: 'pause',
      label: t('assets.lifecycle.maintenancePlan.actions.pause'),
      type: 'warning',
      confirmMessage: `${t('assets.lifecycle.maintenancePlan.actions.pause')}?`,
      apiCall: () => maintenancePlanActionApi.pause(id),
      visibleWhen: (status) => status === 'active',
    },
    {
      key: 'generateTasks',
      label: t('assets.lifecycle.maintenancePlan.actions.generateTasks'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.maintenancePlan.actions.generateTasks')}?`,
      apiCall: () => maintenancePlanActionApi.generateTasks(id),
      visibleWhen: (status) => status === 'active',
    },
  ],
  MaintenanceTask: (id, t) => [
    {
      key: 'execute',
      label: t('assets.lifecycle.maintenanceTask.actions.execute'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.maintenanceTask.actions.execute')}?`,
      apiCall: () => maintenanceTaskActionApi.execute(id, { execution_result: '', actual_hours: 0 }),
      visibleWhen: (status) => status === 'pending' || status === 'in_progress',
    },
    {
      key: 'verify',
      label: t('assets.lifecycle.maintenanceTask.actions.verify'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.maintenanceTask.actions.verify')}?`,
      apiCall: () => maintenanceTaskActionApi.verify(id, 'approved'),
      visibleWhen: (status) => status === 'completed',
    },
    {
      key: 'skip',
      label: t('assets.lifecycle.maintenanceTask.actions.skip'),
      type: 'default',
      confirmMessage: `${t('assets.lifecycle.maintenanceTask.actions.skip')}?`,
      confirmType: 'warning',
      apiCall: () => maintenanceTaskActionApi.skip(id, ''),
      visibleWhen: (status) => status === 'pending',
    },
  ],
  DisposalRequest: (id, t) => [
    {
      key: 'submit',
      label: t('assets.lifecycle.disposalRequest.actions.submit'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.disposalRequest.actions.submit')}?`,
      apiCall: () => disposalRequestActionApi.submit(id),
      visibleWhen: (status) => status === 'draft',
    },
    {
      key: 'startAppraisal',
      label: t('assets.lifecycle.disposalRequest.actions.startAppraisal'),
      type: 'primary',
      confirmMessage: `${t('assets.lifecycle.disposalRequest.actions.startAppraisal')}?`,
      apiCall: () => disposalRequestActionApi.startAppraisal(id),
      visibleWhen: (status) => status === 'submitted',
    },
    {
      key: 'approve',
      label: t('assets.lifecycle.disposalRequest.actions.approve'),
      type: 'success',
      confirmMessage: `${t('assets.lifecycle.disposalRequest.actions.approve')}?`,
      apiCall: () => disposalRequestActionApi.approve(id, 'approved'),
      visibleWhen: (status) => status === 'appraising',
    },
    {
      key: 'reject',
      label: t('assets.lifecycle.disposalRequest.actions.reject'),
      type: 'danger',
      confirmMessage: `${t('assets.lifecycle.disposalRequest.actions.reject')}?`,
      confirmType: 'warning',
      apiCall: () => disposalRequestActionApi.approve(id, 'rejected'),
      visibleWhen: (status) => status === 'appraising',
    },
    {
      key: 'cancel',
      label: t('common.actions.cancel'),
      type: 'default',
      confirmMessage: t('common.messages.confirmCancel'),
      confirmType: 'warning',
      apiCall: () => disposalRequestActionApi.cancel(id),
      visibleWhen: (status) => ['draft', 'submitted'].includes(status),
    },
  ],
  AssetWarranty: (id, t) => [
    {
      key: 'activate',
      label: t('assets.lifecycle.assetWarranty.actions.activate'),
      type: 'success',
      confirmMessage: t('assets.lifecycle.assetWarranty.messages.activateConfirm'),
      apiCall: () => assetWarrantyActionApi.activate(id),
      visibleWhen: (status) => status === 'draft',
    },
    {
      key: 'renew',
      label: t('assets.lifecycle.assetWarranty.actions.renew'),
      type: 'warning',
      prompt: {
        title: t('assets.lifecycle.assetWarranty.dialog.renewTitle'),
        fields: [
          {
            key: 'end_date',
            label: t('assets.lifecycle.assetWarranty.form.newEndDate'),
            type: 'date',
            required: true,
            valueFormat: 'YYYY-MM-DD',
          },
          {
            key: 'warranty_cost',
            label: t('assets.lifecycle.assetWarranty.columns.warrantyCost'),
            type: 'number',
            min: 0,
            precision: 2,
            defaultValue: 0,
          },
        ],
      },
      apiCall: ({ values } = { values: {} }) => assetWarrantyActionApi.renew(id, {
        end_date: String(values?.end_date || ''),
        warranty_cost: Number(values?.warranty_cost || 0),
      }),
      visibleWhen: (status) => ['active', 'expiring'].includes(status),
    },
    {
      key: 'recordClaim',
      label: t('assets.lifecycle.assetWarranty.actions.recordClaim'),
      type: 'primary',
      confirmMessage: t('assets.lifecycle.assetWarranty.messages.claimConfirm'),
      confirmType: 'warning',
      apiCall: () => assetWarrantyActionApi.recordClaim(id),
      visibleWhen: (status) => ['active', 'expiring'].includes(status),
    },
    {
      key: 'cancel',
      label: t('assets.lifecycle.assetWarranty.actions.cancel'),
      type: 'danger',
      confirmMessage: t('assets.lifecycle.assetWarranty.messages.cancelConfirm'),
      confirmType: 'warning',
      apiCall: () => assetWarrantyActionApi.cancel(id),
      visibleWhen: (status) => !['cancelled', 'expired'].includes(status),
    },
  ],
}

export const resolveLifecycleDetailStatusActions = (
  objectCode: string,
  id: string,
  t: (key: string) => string
) => {
  const factory = lifecycleDetailStatusActionRegistry[String(objectCode || '').trim()]
  return factory ? factory(id, t) : []
}
