# Generated by Django 5.0.1 on 2026-01-18 11:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique device identifier",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(help_text="Device name", max_length=100),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android"), ("h5", "H5")],
                        help_text="Device platform type",
                        max_length=20,
                    ),
                ),
                (
                    "os_version",
                    models.CharField(blank=True, help_text="OS version", max_length=50),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, help_text="App version", max_length=50
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        default=dict,
                        help_text="Device details including screen, CPU, memory, etc.",
                    ),
                ),
                (
                    "is_bound",
                    models.BooleanField(
                        default=True, help_text="Device binding status"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Device activation status"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Last login time"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Last login IP", null=True
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last sync time", null=True
                    ),
                ),
                (
                    "last_location",
                    models.JSONField(
                        blank=True,
                        help_text="Last location {latitude, longitude, address}",
                        null=True,
                    ),
                ),
                (
                    "enable_biometric",
                    models.BooleanField(
                        default=False, help_text="Enable biometric authentication"
                    ),
                ),
                (
                    "allow_offline",
                    models.BooleanField(default=True, help_text="Allow offline mode"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Device owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Device",
                "verbose_name_plural": "Mobile Devices",
                "db_table": "mobile_device",
                "ordering": ["-last_login_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceSecurityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("bind", "Bind"),
                            ("unbind", "Unbind"),
                            ("sync", "Sync"),
                            ("suspicious", "Suspicious"),
                        ],
                        help_text="Event type",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(help_text="IP address")),
                (
                    "location",
                    models.JSONField(
                        blank=True, help_text="Location information", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User Agent string"),
                ),
                ("details", models.JSONField(default=dict, help_text="Event details")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Associated device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_logs",
                        to="mobile.mobiledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Security Log",
                "verbose_name_plural": "Device Security Logs",
                "db_table": "mobile_device_security_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(help_text="Target table name", max_length=100),
                ),
                (
                    "record_id",
                    models.CharField(help_text="Record identifier", max_length=100),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="Operation type",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(help_text="Operation data")),
                (
                    "old_data",
                    models.JSONField(
                        blank=True,
                        help_text="Original data for update/delete",
                        null=True,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Synchronization status",
                        max_length=20,
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, help_text="Sync completion time", null=True
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, help_text="Sync error message"),
                ),
                (
                    "client_version",
                    models.IntegerField(help_text="Client data version"),
                ),
                (
                    "server_version",
                    models.IntegerField(
                        blank=True, help_text="Server data version", null=True
                    ),
                ),
                (
                    "client_created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Client creation time",
                    ),
                ),
                (
                    "client_updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Client update time",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Source device",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_data",
                        to="mobile.mobiledevice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Data owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Data",
                "verbose_name_plural": "Offline Data",
                "db_table": "mobile_offline_data",
                "ordering": ["client_created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("version_mismatch", "Version Mismatch"),
                            ("duplicate_create", "Duplicate Create"),
                            ("delete_modified", "Delete Modified"),
                            ("concurrent_modify", "Concurrent Modify"),
                        ],
                        help_text="Conflict type",
                        max_length=50,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(help_text="Affected table", max_length=100),
                ),
                (
                    "record_id",
                    models.CharField(help_text="Affected record ID", max_length=100),
                ),
                ("local_data", models.JSONField(help_text="Local (client) data")),
                ("server_data", models.JSONField(help_text="Server data")),
                (
                    "merged_data",
                    models.JSONField(blank=True, help_text="Merged data", null=True),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("server_wins", "Server Wins"),
                            ("client_wins", "Client Wins"),
                            ("merge", "Merge"),
                            ("manual", "Manual"),
                        ],
                        default="pending",
                        help_text="Resolution method",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="Resolution time", null=True
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, help_text="Resolution notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "offline_data",
                    models.OneToOneField(
                        help_text="Related offline data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict",
                        to="mobile.offlinedata",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        help_text="User who resolved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Affected user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Conflict",
                "verbose_name_plural": "Sync Conflicts",
                "db_table": "mobile_sync_conflict",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Sync"),
                            ("incremental", "Incremental Sync"),
                            ("manual", "Manual Sync"),
                        ],
                        help_text="Sync type",
                        max_length=20,
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        help_text="Sync direction",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial_success", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        help_text="Sync status",
                        max_length=20,
                    ),
                ),
                ("tables", models.JSONField(default=list, help_text="Synced tables")),
                (
                    "upload_count",
                    models.IntegerField(default=0, help_text="Uploaded records"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, help_text="Downloaded records"),
                ),
                (
                    "conflict_count",
                    models.IntegerField(default=0, help_text="Conflict count"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, help_text="Error count"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Start time"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, help_text="End time", null=True),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration (seconds)", null=True
                    ),
                ),
                (
                    "client_version",
                    models.IntegerField(default=0, help_text="Client version"),
                ),
                (
                    "server_version",
                    models.IntegerField(default=0, help_text="Server version"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message"),
                ),
                (
                    "error_details",
                    models.JSONField(blank=True, help_text="Error details", null=True),
                ),
                (
                    "network_type",
                    models.CharField(
                        blank=True, help_text="Network type", max_length=20
                    ),
                ),
                (
                    "data_size",
                    models.BigIntegerField(default=0, help_text="Data size (bytes)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Sync device",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="mobile.mobiledevice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Sync initiator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "db_table": "mobile_sync_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalDelegate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "delegate_type",
                    models.CharField(
                        choices=[
                            ("temporary", "Temporary"),
                            ("permanent", "Permanent"),
                        ],
                        default="temporary",
                        help_text="Delegation type",
                        max_length=20,
                    ),
                ),
                (
                    "delegate_scope",
                    models.CharField(
                        choices=[
                            ("all", "All Approvals"),
                            ("specific", "Specific Workflows"),
                            ("category", "Specific Categories"),
                        ],
                        default="all",
                        help_text="Delegation scope",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Start time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, help_text="End time", null=True),
                ),
                (
                    "scope_config",
                    models.JSONField(
                        default=dict,
                        help_text="Scope configuration based on scope_type",
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Delegation reason")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active status"),
                ),
                (
                    "is_revoked",
                    models.BooleanField(default=False, help_text="Revoked status"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="Revocation time", null=True
                    ),
                ),
                (
                    "revoked_reason",
                    models.TextField(blank=True, help_text="Revocation reason"),
                ),
                (
                    "approved_count",
                    models.IntegerField(default=0, help_text="Approved count"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        help_text="Delegation receiver",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        help_text="Delegation giver",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegated_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        help_text="Revoked by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Delegate",
                "verbose_name_plural": "Approval Delegates",
                "db_table": "mobile_approval_delegate",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["delegator", "is_active"],
                        name="mobile_appr_delegat_779af7_idx",
                    ),
                    models.Index(
                        fields=["delegate", "is_active"],
                        name="mobile_appr_delegat_ae5671_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="mobile_appr_created_99006a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(
                fields=["user", "is_bound"], name="mobile_devi_user_id_64a65c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(
                fields=["device_id"], name="mobile_devi_device__5174db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(
                fields=["-last_login_at"], name="mobile_devi_last_lo_573490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinedata",
            index=models.Index(
                fields=["user", "sync_status"], name="mobile_offl_user_id_cd1071_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinedata",
            index=models.Index(
                fields=["table_name", "record_id"],
                name="mobile_offl_table_n_c041dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinedata",
            index=models.Index(
                fields=["-client_created_at"], name="mobile_offl_client__e397b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["user", "resolution"], name="mobile_sync_user_id_405932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["-created_at"], name="mobile_sync_created_479972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["user", "-started_at"], name="mobile_sync_user_id_8f71cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(fields=["status"], name="mobile_sync_status_0dff9b_idx"),
        ),
    ]
