# Generated by Django 5.0 on 2026-03-29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_add_base_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('search_type', models.CharField(choices=[('asset', 'Asset'), ('project', 'Project'), ('loan', 'Loan')], default='asset', help_text='Search domain type', max_length=20)),
                ('keyword', models.CharField(blank=True, help_text='Original keyword entered by the user', max_length=200)),
                ('normalized_keyword', models.CharField(blank=True, db_index=True, help_text='Normalized keyword for deduplication', max_length=200)),
                ('query_signature', models.CharField(db_index=True, help_text='Stable signature for keyword and filters', max_length=64)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filter payload')),
                ('result_count', models.PositiveIntegerField(default=0, help_text='Number of results returned by the last execution')),
                ('search_count', models.PositiveIntegerField(default=1, help_text='How many times the same search was repeated')),
                ('last_searched_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the latest execution')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(help_text='User who executed the search', on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-last_searched_at', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('name', models.CharField(help_text='Display name for the saved search', max_length=100)),
                ('search_type', models.CharField(choices=[('asset', 'Asset'), ('project', 'Project'), ('loan', 'Loan')], default='asset', help_text='Search domain type', max_length=20)),
                ('keyword', models.CharField(blank=True, help_text='Default keyword for the saved search', max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Saved filter payload')),
                ('is_shared', models.BooleanField(default=False, help_text='Whether the search is visible to other users in the organization')),
                ('use_count', models.PositiveIntegerField(default=0, help_text='How many times the saved search was used')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(help_text='Owner of the saved search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'saved_search',
                'ordering': ['-updated_at', '-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('search_type', models.CharField(choices=[('asset', 'Asset'), ('project', 'Project'), ('loan', 'Loan')], default='asset', help_text='Search domain type', max_length=20)),
                ('query', models.CharField(help_text='Suggestion text displayed to users', max_length=200)),
                ('normalized_query', models.CharField(db_index=True, help_text='Normalized suggestion text used for matching', max_length=200)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Usage frequency for ranking suggestions')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Timestamp of the latest usage')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Search Suggestion',
                'verbose_name_plural': 'Search Suggestions',
                'db_table': 'search_suggestion',
                'ordering': ['-frequency', '-last_used', 'query'],
            },
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['organization', 'user', 'search_type'], name='sh_org_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['organization', 'search_type', 'last_searched_at'], name='sh_org_type_last_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['organization', 'normalized_keyword'], name='sh_org_keyword_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'user', 'search_type', 'query_signature'), name='uniq_search_history_signature_org_user'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['organization', 'user', 'search_type'], name='ss_org_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['organization', 'search_type', 'is_shared'], name='ss_org_type_shared_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'user', 'name'), name='uniq_saved_search_name_org_user'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['organization', 'search_type', 'normalized_query'], name='sg_org_type_query_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['organization', 'search_type', 'last_used'], name='sg_org_type_last_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'search_type', 'normalized_query'), name='uniq_search_suggestion_org_type_query'),
        ),
    ]
