# Generated by Django 5.0.1 on 2026-03-30 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="savedsearch",
            new_name="saved_searc_organiz_09ab89_idx",
            old_name="ss_org_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="savedsearch",
            new_name="saved_searc_organiz_161327_idx",
            old_name="ss_org_type_shared_idx",
        ),
        migrations.RenameIndex(
            model_name="searchhistory",
            new_name="search_hist_organiz_dd4757_idx",
            old_name="sh_org_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="searchhistory",
            new_name="search_hist_organiz_4552a8_idx",
            old_name="sh_org_type_last_idx",
        ),
        migrations.RenameIndex(
            model_name="searchhistory",
            new_name="search_hist_organiz_b55821_idx",
            old_name="sh_org_keyword_idx",
        ),
        migrations.RenameIndex(
            model_name="searchsuggestion",
            new_name="search_sugg_organiz_d82a49_idx",
            old_name="sg_org_type_query_idx",
        ),
        migrations.RenameIndex(
            model_name="searchsuggestion",
            new_name="search_sugg_organiz_33d567_idx",
            old_name="sg_org_type_last_idx",
        ),
    ]
