# Generated by Django 5.2.10 on 2026-01-24 03:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_migrate_unit_data'),
        ('organizations', '0005_add_base_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('code', models.CharField(db_index=True, help_text='Software code (e.g., WIN11, OFF365)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Software name', max_length=200)),
                ('version', models.CharField(blank=True, help_text='Software version', max_length=50)),
                ('vendor', models.CharField(blank=True, help_text='Software vendor', max_length=200)),
                ('software_type', models.CharField(choices=[('os', 'Operating System'), ('office', 'Office Suite'), ('professional', 'Professional Software'), ('development', 'Development Tool'), ('security', 'Security Software'), ('database', 'Database'), ('other', 'Other')], default='other', help_text='Software type', max_length=50)),
                ('license_type', models.CharField(blank=True, help_text='License type (perpetual, subscription, OEM, volume)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this software is actively tracked')),
                ('category', models.ForeignKey(blank=True, help_text='Related asset category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_items', to='assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software Catalog',
                'db_table': 'software_catalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('license_no', models.CharField(db_index=True, help_text='License number', max_length=100, unique=True)),
                ('license_key', models.CharField(blank=True, help_text='License key/serial (encrypted)', max_length=500)),
                ('total_units', models.IntegerField(default=1, help_text='Total licensed units', validators=[django.core.validators.MinValueValidator(1)])),
                ('used_units', models.IntegerField(default=0, help_text='Currently allocated units', validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateField(help_text='License purchase date')),
                ('expiry_date', models.DateField(blank=True, help_text='License expiration date (null for perpetual)', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='License purchase price', max_digits=14, null=True)),
                ('annual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Annual maintenance/subscription cost', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', help_text='License status', max_length=50)),
                ('license_type', models.CharField(blank=True, help_text='License type (perpetual, subscription, OEM, volume)', max_length=50)),
                ('agreement_no', models.CharField(blank=True, help_text='Enterprise agreement number', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='License notes')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('software', models.ForeignKey(help_text='Associated software', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='software_licenses.software')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('vendor', models.ForeignKey(blank=True, help_text='License vendor/supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_licenses', to='assets.supplier')),
            ],
            options={
                'verbose_name': 'Software License',
                'verbose_name_plural': 'Software Licenses',
                'db_table': 'software_licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('allocated_date', models.DateField(help_text='Allocation date')),
                ('allocation_key', models.CharField(blank=True, help_text='Specific license key for this allocation (encrypted)', max_length=500)),
                ('deallocated_date', models.DateField(blank=True, help_text='Deallocation date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this allocation is active')),
                ('notes', models.TextField(blank=True, help_text='Allocation notes')),
                ('allocated_by', models.ForeignKey(blank=True, help_text='User who made the allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_allocations', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(help_text='Asset with this software', on_delete=django.db.models.deletion.CASCADE, related_name='software_allocations', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deallocated_by', models.ForeignKey(blank=True, help_text='User who deallocated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_deallocations', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('license', models.ForeignKey(help_text='Allocated license', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='software_licenses.softwarelicense')),
            ],
            options={
                'verbose_name': 'License Allocation',
                'verbose_name_plural': 'License Allocations',
                'db_table': 'license_allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['organization', 'code'], name='software_ca_organiz_7c8286_idx'),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['organization', 'vendor'], name='software_ca_organiz_4b0e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarelicense',
            index=models.Index(fields=['organization', 'software'], name='software_li_organiz_39f1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarelicense',
            index=models.Index(fields=['organization', 'status'], name='software_li_organiz_cb7f99_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarelicense',
            index=models.Index(fields=['organization', 'expiry_date'], name='software_li_organiz_a9ab02_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseallocation',
            index=models.Index(fields=['organization', 'license'], name='license_all_organiz_f38b67_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseallocation',
            index=models.Index(fields=['organization', 'asset'], name='license_all_organiz_218e09_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseallocation',
            index=models.Index(fields=['organization', 'license', 'asset'], name='license_all_organiz_1f07e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='licenseallocation',
            unique_together={('organization', 'license', 'asset')},
        ),
    ]
