# Generated by Django 5.2.10 on 2026-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecord',
            name='claim_no',
            field=models.CharField(blank=True, db_index=True, help_text='Claim number assigned by insurer', max_length=100, null=True, unique=True),
        ),
    ]
