# Generated by Django 5.0.1 on 2026-03-11 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_alter_loanitem_unique_together_and_more"),
        ("insurance", "0002_alter_claimrecord_claim_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuredasset",
            name="asset",
            field=models.ForeignKey(
                help_text="Insured asset",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insurance_coverages",
                to="assets.asset",
            ),
        ),
    ]
