# Generated by Django 5.0.1 on 2026-01-18 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Organization name', max_length=200)),
                ('code', models.CharField(db_comment='Organization code (unique)', db_index=True, max_length=50, unique=True)),
                ('level', models.IntegerField(db_comment='Hierarchy level (0=root)', default=0, editable=False)),
                ('path', models.CharField(db_comment='Organization path (e.g., /group/company/branch)', editable=False, max_length=500)),
                ('org_type', models.CharField(choices=[('group', 'Group'), ('company', 'Company'), ('branch', 'Branch'), ('department', 'Department')], db_comment='Organization type', default='company', max_length=20)),
                ('contact_person', models.CharField(blank=True, db_comment='Contact person name', max_length=100)),
                ('contact_phone', models.CharField(blank=True, db_comment='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, db_comment='Organization email', max_length=254)),
                ('address', models.TextField(blank=True, db_comment='Organization address')),
                ('credit_code', models.CharField(blank=True, db_comment='Unified social credit code (for finance integration)', max_length=50)),
                ('is_active', models.BooleanField(db_comment='Is organization active', default=True)),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag', default=False)),
                ('settings', models.JSONField(db_comment='Organization-level settings', default=dict)),
                ('invite_code', models.CharField(blank=True, db_comment='Invite code for joining organization', max_length=20, null=True, unique=True)),
                ('invite_code_expires_at', models.DateTimeField(blank=True, db_comment='Invite code expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last update timestamp')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_comment='Parent organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['code'], name='organizatio_code_c5d604_idx'), models.Index(fields=['parent'], name='organizatio_parent__375f8b_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx'), models.Index(fields=['is_deleted'], name='organizatio_is_dele_77ea97_idx'), models.Index(fields=['invite_code'], name='organizatio_invite__075968_idx')],
            },
        ),
    ]
