# Generated by Django 5.0.1 on 2026-01-18 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": " Departments",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organizations.organization",),
        ),
    ]
