# Generated by Django 5.0.1 on 2026-01-19 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="wework_dept_id",
            field=models.CharField(
                blank=True,
                db_comment="WeWork department ID for sync",
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="wework_parent_id",
            field=models.IntegerField(
                blank=True, db_comment="WeWork parent department ID", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["wework_dept_id"], name="organizatio_wework__a306c8_idx"
            ),
        ),
    ]
