# Generated by Django 5.0.1 on 2026-01-19 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_wework_dept_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="Department code (unique per organization)",
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(db_comment="Department name", max_length=100),
                ),
                (
                    "level",
                    models.IntegerField(
                        db_comment="Hierarchy level (0=root)", default=0, editable=False
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_comment="Department code path (e.g., /HQ/TECH)",
                        default="",
                        editable=False,
                        max_length=500,
                    ),
                ),
                ("order", models.IntegerField(db_comment="Display order", default=0)),
                (
                    "full_path",
                    models.CharField(
                        db_comment="Full path for display",
                        default="",
                        editable=False,
                        max_length=500,
                    ),
                ),
                (
                    "full_path_name",
                    models.CharField(
                        db_comment='Full path with names (e.g., "Headquarters/Technology/Backend")',
                        default="",
                        editable=False,
                        max_length=1000,
                    ),
                ),
                (
                    "wework_dept_id",
                    models.CharField(
                        blank=True,
                        db_comment="WeWork department ID for sync",
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "wework_leader_id",
                    models.CharField(
                        blank=True,
                        db_comment="WeWork leader user ID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "dingtalk_dept_id",
                    models.CharField(
                        blank=True,
                        db_comment="DingTalk department ID for sync",
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dingtalk_leader_id",
                    models.CharField(
                        blank=True,
                        db_comment="DingTalk leader user ID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "feishu_dept_id",
                    models.CharField(
                        blank=True,
                        db_comment="Feishu department ID for sync",
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "feishu_leader_id",
                    models.CharField(
                        blank=True,
                        db_comment="Feishu leader user ID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Is department active", default=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Department leader",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Parent department",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organizations.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="UserDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="Soft delete flag, records are filtered out by default",
                        db_index=True,
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Timestamp when record was soft deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Timestamp when record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Timestamp when record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        db_comment="Dynamic fields for metadata-driven extensions",
                        default=dict,
                        verbose_name="Custom Fields",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_comment="Is primary department for asset ownership",
                        default=False,
                    ),
                ),
                (
                    "is_asset_department",
                    models.BooleanField(
                        db_comment="Is department for asset management purposes",
                        default=False,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        db_comment="Job position in this department",
                        max_length=100,
                    ),
                ),
                (
                    "is_leader",
                    models.BooleanField(
                        db_comment="Is user a leader in this department", default=False
                    ),
                ),
                (
                    "wework_department_order",
                    models.IntegerField(
                        blank=True, db_comment="WeWork department order", null=True
                    ),
                ),
                (
                    "is_primary_in_wework",
                    models.BooleanField(
                        db_comment="Is primary department in WeWork", default=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Organization for multi-tenant data isolation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="Associated user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_comment="Associated department",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_departments",
                        to="organizations.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Department",
                "verbose_name_plural": "User Departments",
                "db_table": "user_departments",
                "indexes": [
                    models.Index(
                        fields=["user", "organization"],
                        name="user_depart_user_id_011916_idx",
                    ),
                    models.Index(
                        fields=["department"], name="user_depart_departm_fdaeed_idx"
                    ),
                    models.Index(
                        fields=["is_primary"], name="user_depart_is_prim_ef0759_idx"
                    ),
                    models.Index(
                        fields=["is_leader"], name="user_depart_is_lead_46d20e_idx"
                    ),
                ],
                "unique_together": {("user", "organization", "department")},
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organization", "parent"], name="departments_organiz_83cdb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organization", "wework_dept_id"],
                name="departments_organiz_10b590_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["level"], name="departments_level_002fcb_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active"], name="departments_is_acti_a777bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "code")},
        ),
    ]
