# Generated by Django 5.2.10 on 2026-01-25 05:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_migrate_unit_data'),
        ('organizations', '0005_add_base_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line Method'), ('double_declining', 'Double Declining Balance Method'), ('sum_of_years', 'Sum of Years Digits Method'), ('units_of_production', 'Units of Production Method')], default='straight_line', help_text='Depreciation calculation method', max_length=50)),
                ('useful_life', models.IntegerField(help_text='Useful life in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('salvage_value_rate', models.DecimalField(decimal_places=2, help_text='Salvage value rate as percentage (e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('notes', models.TextField(blank=True, help_text='Configuration notes')),
                ('category', models.ForeignKey(help_text='Asset category for this depreciation configuration', on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_configs', to='assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Depreciation Configuration',
                'verbose_name_plural': 'Depreciation Configurations',
                'db_table': 'depreciation_configs',
                'ordering': ['category__name'],
                'indexes': [models.Index(fields=['organization', 'category'], name='depreciatio_organiz_bcc85e_idx'), models.Index(fields=['organization', 'is_active'], name='depreciatio_organiz_ce6d87_idx')],
                'unique_together': {('organization', 'category')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('period', models.CharField(db_index=True, help_text='Depreciation period in YYYY-MM format', max_length=7)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, help_text='Depreciation amount for this period', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('accumulated_amount', models.DecimalField(decimal_places=2, help_text='Total accumulated depreciation amount', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_value', models.DecimalField(decimal_places=2, help_text='Net book value after depreciation', max_digits=14)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='calculated', help_text='Depreciation record status', max_length=50)),
                ('post_date', models.DateField(blank=True, help_text='Date when depreciation was posted to accounting', null=True)),
                ('notes', models.TextField(blank=True, help_text='Record notes')),
                ('asset', models.ForeignKey(help_text='Asset being depreciated', on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Depreciation Record',
                'verbose_name_plural': 'Depreciation Records',
                'db_table': 'depreciation_records',
                'ordering': ['-period', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'asset'], name='depreciatio_organiz_9f54b8_idx'), models.Index(fields=['organization', 'period'], name='depreciatio_organiz_628603_idx'), models.Index(fields=['organization', 'status'], name='depreciatio_organiz_fa9507_idx'), models.Index(fields=['organization', 'asset', 'period'], name='depreciatio_organiz_1d45f1_idx')],
                'unique_together': {('organization', 'asset', 'period')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_comment='Soft delete flag, records are filtered out by default', db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='Timestamp when record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Timestamp when record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Timestamp when record was last updated', verbose_name='Updated At')),
                ('custom_fields', models.JSONField(blank=True, db_comment='Dynamic fields for metadata-driven extensions', default=dict, verbose_name='Custom Fields')),
                ('period', models.CharField(db_index=True, help_text='Depreciation period in YYYY-MM format', max_length=7)),
                ('run_date', models.DateField(help_text='Date when depreciation calculation was executed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Depreciation run status', max_length=50)),
                ('total_assets', models.IntegerField(default=0, help_text='Total number of assets processed', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total depreciation amount for this run', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('error_message', models.TextField(blank=True, help_text='Error message if run failed')),
                ('notes', models.TextField(blank=True, help_text='Run notes')),
                ('created_by', models.ForeignKey(blank=True, db_comment='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_comment='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('organization', models.ForeignKey(blank=True, db_comment='Organization for multi-tenant data isolation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Depreciation Run',
                'verbose_name_plural': 'Depreciation Runs',
                'db_table': 'depreciation_runs',
                'ordering': ['-run_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'period'], name='depreciatio_organiz_8272b1_idx'), models.Index(fields=['organization', 'status'], name='depreciatio_organiz_431950_idx')],
            },
        ),
    ]
