"""
Serializers for Asset models.
"""
from .category import (
    AssetCategorySerializer,
    AssetCategoryTreeSerializer,
    AssetCategoryCreateSerializer,
    AssetCategoryListSerializer,
    AddChildSerializer,
)
from .asset import (
    SupplierSerializer,
    SupplierListSerializer,
    LocationSerializer,
    LocationListSerializer,
    AssetStatusLogSerializer,
    AssetStatusLogListSerializer,
    AssetListSerializer,
    AssetDetailSerializer,
    AssetCreateSerializer,
    AssetUpdateSerializer,
    AssetStatusSerializer,
    AssetSerializer,
    AssetBulkImportSerializer,
    AssetBulkExportSerializer,
)
from .operation import (
    # Pickup serializers
    PickupItemSerializer,
    PickupItemListSerializer,
    AssetPickupListSerializer,
    AssetPickupDetailSerializer,
    AssetPickupCreateSerializer,
    AssetPickupUpdateSerializer,
    AssetPickupSerializer,
    PickupApprovalSerializer,
    # Transfer serializers
    TransferItemSerializer,
    TransferItemListSerializer,
    AssetTransferListSerializer,
    AssetTransferDetailSerializer,
    AssetTransferCreateSerializer,
    AssetTransferSerializer,
    TransferApprovalSerializer,
    # Return serializers
    ReturnItemSerializer,
    ReturnItemListSerializer,
    AssetReturnListSerializer,
    AssetReturnDetailSerializer,
    AssetReturnCreateSerializer,
    AssetReturnSerializer,
    ReturnConfirmSerializer,
    # Loan serializers
    LoanItemSerializer,
    LoanItemListSerializer,
    AssetLoanListSerializer,
    AssetLoanDetailSerializer,
    AssetLoanCreateSerializer,
    AssetLoanSerializer,
    LoanApprovalSerializer,
    LoanReturnConfirmSerializer,
)

__all__ = [
    # Category serializers
    'AssetCategorySerializer',
    'AssetCategoryTreeSerializer',
    'AssetCategoryCreateSerializer',
    'AssetCategoryListSerializer',
    'AddChildSerializer',
    # Asset serializers
    'SupplierSerializer',
    'SupplierListSerializer',
    'LocationSerializer',
    'LocationListSerializer',
    'AssetStatusLogSerializer',
    'AssetStatusLogListSerializer',
    'AssetListSerializer',
    'AssetDetailSerializer',
    'AssetCreateSerializer',
    'AssetUpdateSerializer',
    'AssetStatusSerializer',
    'AssetSerializer',
    'AssetBulkImportSerializer',
    'AssetBulkExportSerializer',
    # Operation serializers - Pickup
    'PickupItemSerializer',
    'PickupItemListSerializer',
    'AssetPickupListSerializer',
    'AssetPickupDetailSerializer',
    'AssetPickupCreateSerializer',
    'AssetPickupUpdateSerializer',
    'AssetPickupSerializer',
    'PickupApprovalSerializer',
    # Operation serializers - Transfer
    'TransferItemSerializer',
    'TransferItemListSerializer',
    'AssetTransferListSerializer',
    'AssetTransferDetailSerializer',
    'AssetTransferCreateSerializer',
    'AssetTransferSerializer',
    'TransferApprovalSerializer',
    # Operation serializers - Return
    'ReturnItemSerializer',
    'ReturnItemListSerializer',
    'AssetReturnListSerializer',
    'AssetReturnDetailSerializer',
    'AssetReturnCreateSerializer',
    'AssetReturnSerializer',
    'ReturnConfirmSerializer',
    # Operation serializers - Loan
    'LoanItemSerializer',
    'LoanItemListSerializer',
    'AssetLoanListSerializer',
    'AssetLoanDetailSerializer',
    'AssetLoanCreateSerializer',
    'AssetLoanSerializer',
    'LoanApprovalSerializer',
    'LoanReturnConfirmSerializer',
]
